// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: complaints.sql

package complaints

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countComplaintsByDateRange = `-- name: CountComplaintsByDateRange :one
SELECT count(*)::bigint
FROM complaints
WHERE complaint_date >= $1
    AND complaint_date <= $2
`

type CountComplaintsByDateRangeParams struct {
	StartAt sql.NullTime `json:"start_at"`
	EndAt   sql.NullTime `json:"end_at"`
}

func (q *Queries) CountComplaintsByDateRange(ctx context.Context, arg CountComplaintsByDateRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countComplaintsByDateRange, arg.StartAt, arg.EndAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrUpdateComplaint = `-- name: CreateOrUpdateComplaint :one
INSERT INTO complaints (
        id,
        notification_id,
        service_id,
        ses_feedback_id,
        complaint_type,
        complaint_date,
        created_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    ) ON CONFLICT (id) DO
UPDATE
SET ses_feedback_id = EXCLUDED.ses_feedback_id,
    complaint_type = EXCLUDED.complaint_type,
    complaint_date = EXCLUDED.complaint_date
RETURNING id, notification_id, service_id, ses_feedback_id, complaint_type, complaint_date, created_at
`

type CreateOrUpdateComplaintParams struct {
	ID             uuid.UUID      `json:"id"`
	NotificationID uuid.UUID      `json:"notification_id"`
	ServiceID      uuid.UUID      `json:"service_id"`
	SesFeedbackID  sql.NullString `json:"ses_feedback_id"`
	ComplaintType  sql.NullString `json:"complaint_type"`
	ComplaintDate  sql.NullTime   `json:"complaint_date"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (q *Queries) CreateOrUpdateComplaint(ctx context.Context, arg CreateOrUpdateComplaintParams) (Complaint, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateComplaint,
		arg.ID,
		arg.NotificationID,
		arg.ServiceID,
		arg.SesFeedbackID,
		arg.ComplaintType,
		arg.ComplaintDate,
		arg.CreatedAt,
	)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.ServiceID,
		&i.SesFeedbackID,
		&i.ComplaintType,
		&i.ComplaintDate,
		&i.CreatedAt,
	)
	return i, err
}

const getComplaintsPage = `-- name: GetComplaintsPage :many
SELECT id, notification_id, service_id, ses_feedback_id, complaint_type, complaint_date, created_at
FROM complaints
WHERE complaint_date >= $1
    AND complaint_date <= $2
ORDER BY complaint_date DESC NULLS LAST,
    created_at DESC
LIMIT $4 OFFSET $3
`

type GetComplaintsPageParams struct {
	StartAt     sql.NullTime `json:"start_at"`
	EndAt       sql.NullTime `json:"end_at"`
	OffsetCount int32        `json:"offset_count"`
	LimitCount  int32        `json:"limit_count"`
}

func (q *Queries) GetComplaintsPage(ctx context.Context, arg GetComplaintsPageParams) ([]Complaint, error) {
	rows, err := q.db.QueryContext(ctx, getComplaintsPage,
		arg.StartAt,
		arg.EndAt,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Complaint
	for rows.Next() {
		var i Complaint
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ServiceID,
			&i.SesFeedbackID,
			&i.ComplaintType,
			&i.ComplaintDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
