// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package jobs

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const archiveOldJobs = `-- name: ArchiveOldJobs :execrows
UPDATE jobs
SET archived = true,
    updated_at = now()
WHERE archived = false
    AND processing_finished < $1
`

func (q *Queries) ArchiveOldJobs(ctx context.Context, cutoff sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveOldJobs, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
        id,
        original_file_name,
        service_id,
        template_id,
        created_at,
        updated_at,
        notification_count,
        notifications_sent,
        processing_started,
        processing_finished,
        created_by_id,
        template_version,
        notifications_delivered,
        notifications_failed,
        job_status,
        scheduled_for,
        archived,
        api_key_id,
        sender_id
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19
    )
RETURNING id, original_file_name, service_id, template_id, created_at, updated_at, notification_count, notifications_sent, processing_started, processing_finished, created_by_id, template_version, notifications_delivered, notifications_failed, job_status, scheduled_for, archived, api_key_id, sender_id
`

type CreateJobParams struct {
	ID                     uuid.UUID     `json:"id"`
	OriginalFileName       string        `json:"original_file_name"`
	ServiceID              uuid.UUID     `json:"service_id"`
	TemplateID             uuid.NullUUID `json:"template_id"`
	CreatedAt              time.Time     `json:"created_at"`
	UpdatedAt              sql.NullTime  `json:"updated_at"`
	NotificationCount      int32         `json:"notification_count"`
	NotificationsSent      int32         `json:"notifications_sent"`
	ProcessingStarted      sql.NullTime  `json:"processing_started"`
	ProcessingFinished     sql.NullTime  `json:"processing_finished"`
	CreatedByID            uuid.NullUUID `json:"created_by_id"`
	TemplateVersion        int32         `json:"template_version"`
	NotificationsDelivered int32         `json:"notifications_delivered"`
	NotificationsFailed    int32         `json:"notifications_failed"`
	JobStatus              string        `json:"job_status"`
	ScheduledFor           sql.NullTime  `json:"scheduled_for"`
	Archived               bool          `json:"archived"`
	ApiKeyID               uuid.NullUUID `json:"api_key_id"`
	SenderID               uuid.NullUUID `json:"sender_id"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.ID,
		arg.OriginalFileName,
		arg.ServiceID,
		arg.TemplateID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.NotificationCount,
		arg.NotificationsSent,
		arg.ProcessingStarted,
		arg.ProcessingFinished,
		arg.CreatedByID,
		arg.TemplateVersion,
		arg.NotificationsDelivered,
		arg.NotificationsFailed,
		arg.JobStatus,
		arg.ScheduledFor,
		arg.Archived,
		arg.ApiKeyID,
		arg.SenderID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OriginalFileName,
		&i.ServiceID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NotificationCount,
		&i.NotificationsSent,
		&i.ProcessingStarted,
		&i.ProcessingFinished,
		&i.CreatedByID,
		&i.TemplateVersion,
		&i.NotificationsDelivered,
		&i.NotificationsFailed,
		&i.JobStatus,
		&i.ScheduledFor,
		&i.Archived,
		&i.ApiKeyID,
		&i.SenderID,
	)
	return i, err
}

const getInProgressJobs = `-- name: GetInProgressJobs :many
SELECT id, original_file_name, service_id, template_id, created_at, updated_at, notification_count, notifications_sent, processing_started, processing_finished, created_by_id, template_version, notifications_delivered, notifications_failed, job_status, scheduled_for, archived, api_key_id, sender_id
FROM jobs
WHERE job_status = 'in progress'
    AND archived = false
ORDER BY processing_started ASC NULLS LAST
`

func (q *Queries) GetInProgressJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getInProgressJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFileName,
			&i.ServiceID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NotificationCount,
			&i.NotificationsSent,
			&i.ProcessingStarted,
			&i.ProcessingFinished,
			&i.CreatedByID,
			&i.TemplateVersion,
			&i.NotificationsDelivered,
			&i.NotificationsFailed,
			&i.JobStatus,
			&i.ScheduledFor,
			&i.Archived,
			&i.ApiKeyID,
			&i.SenderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, original_file_name, service_id, template_id, created_at, updated_at, notification_count, notifications_sent, processing_started, processing_finished, created_by_id, template_version, notifications_delivered, notifications_failed, job_status, scheduled_for, archived, api_key_id, sender_id
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OriginalFileName,
		&i.ServiceID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NotificationCount,
		&i.NotificationsSent,
		&i.ProcessingStarted,
		&i.ProcessingFinished,
		&i.CreatedByID,
		&i.TemplateVersion,
		&i.NotificationsDelivered,
		&i.NotificationsFailed,
		&i.JobStatus,
		&i.ScheduledFor,
		&i.Archived,
		&i.ApiKeyID,
		&i.SenderID,
	)
	return i, err
}

const getJobsByServiceID = `-- name: GetJobsByServiceID :many
SELECT id, original_file_name, service_id, template_id, created_at, updated_at, notification_count, notifications_sent, processing_started, processing_finished, created_by_id, template_version, notifications_delivered, notifications_failed, job_status, scheduled_for, archived, api_key_id, sender_id
FROM jobs
WHERE service_id = $1
    AND archived = false
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetJobsByServiceIDParams struct {
	ServiceID   uuid.UUID `json:"service_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

func (q *Queries) GetJobsByServiceID(ctx context.Context, arg GetJobsByServiceIDParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getJobsByServiceID, arg.ServiceID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFileName,
			&i.ServiceID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NotificationCount,
			&i.NotificationsSent,
			&i.ProcessingStarted,
			&i.ProcessingFinished,
			&i.CreatedByID,
			&i.TemplateVersion,
			&i.NotificationsDelivered,
			&i.NotificationsFailed,
			&i.JobStatus,
			&i.ScheduledFor,
			&i.Archived,
			&i.ApiKeyID,
			&i.SenderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStalledJobs = `-- name: GetStalledJobs :many
SELECT id, original_file_name, service_id, template_id, created_at, updated_at, notification_count, notifications_sent, processing_started, processing_finished, created_by_id, template_version, notifications_delivered, notifications_failed, job_status, scheduled_for, archived, api_key_id, sender_id
FROM jobs
WHERE job_status = 'in progress'
    AND archived = false
    AND processing_started >= $1
    AND processing_started <= $2
ORDER BY processing_started ASC
`

type GetStalledJobsParams struct {
	OlderThan sql.NullTime `json:"older_than"`
	NewerThan sql.NullTime `json:"newer_than"`
}

func (q *Queries) GetStalledJobs(ctx context.Context, arg GetStalledJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getStalledJobs, arg.OlderThan, arg.NewerThan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFileName,
			&i.ServiceID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NotificationCount,
			&i.NotificationsSent,
			&i.ProcessingStarted,
			&i.ProcessingFinished,
			&i.CreatedByID,
			&i.TemplateVersion,
			&i.NotificationsDelivered,
			&i.NotificationsFailed,
			&i.JobStatus,
			&i.ScheduledFor,
			&i.Archived,
			&i.ApiKeyID,
			&i.SenderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasJobs = `-- name: HasJobs :one
SELECT EXISTS(
        SELECT 1
        FROM jobs
        WHERE service_id = $1
            AND archived = false
    ) AS has_jobs
`

func (q *Queries) HasJobs(ctx context.Context, serviceID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasJobs, serviceID)
	var has_jobs bool
	err := row.Scan(&has_jobs)
	return has_jobs, err
}

const setScheduledJobsToPending = `-- name: SetScheduledJobsToPending :many
UPDATE jobs
SET job_status = 'pending',
    updated_at = now()
WHERE job_status = 'scheduled'
    AND scheduled_for <= now()
    AND archived = false
RETURNING id, original_file_name, service_id, template_id, created_at, updated_at, notification_count, notifications_sent, processing_started, processing_finished, created_by_id, template_version, notifications_delivered, notifications_failed, job_status, scheduled_for, archived, api_key_id, sender_id
`

func (q *Queries) SetScheduledJobsToPending(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, setScheduledJobsToPending)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFileName,
			&i.ServiceID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NotificationCount,
			&i.NotificationsSent,
			&i.ProcessingStarted,
			&i.ProcessingFinished,
			&i.CreatedByID,
			&i.TemplateVersion,
			&i.NotificationsDelivered,
			&i.NotificationsFailed,
			&i.JobStatus,
			&i.ScheduledFor,
			&i.Archived,
			&i.ApiKeyID,
			&i.SenderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET original_file_name = $1,
    template_id = $2,
    updated_at = $3,
    notification_count = $4,
    notifications_sent = $5,
    processing_started = $6,
    processing_finished = $7,
    created_by_id = $8,
    template_version = $9,
    notifications_delivered = $10,
    notifications_failed = $11,
    job_status = $12,
    scheduled_for = $13,
    archived = $14,
    api_key_id = $15,
    sender_id = $16
WHERE id = $17
RETURNING id, original_file_name, service_id, template_id, created_at, updated_at, notification_count, notifications_sent, processing_started, processing_finished, created_by_id, template_version, notifications_delivered, notifications_failed, job_status, scheduled_for, archived, api_key_id, sender_id
`

type UpdateJobParams struct {
	OriginalFileName       string        `json:"original_file_name"`
	TemplateID             uuid.NullUUID `json:"template_id"`
	UpdatedAt              sql.NullTime  `json:"updated_at"`
	NotificationCount      int32         `json:"notification_count"`
	NotificationsSent      int32         `json:"notifications_sent"`
	ProcessingStarted      sql.NullTime  `json:"processing_started"`
	ProcessingFinished     sql.NullTime  `json:"processing_finished"`
	CreatedByID            uuid.NullUUID `json:"created_by_id"`
	TemplateVersion        int32         `json:"template_version"`
	NotificationsDelivered int32         `json:"notifications_delivered"`
	NotificationsFailed    int32         `json:"notifications_failed"`
	JobStatus              string        `json:"job_status"`
	ScheduledFor           sql.NullTime  `json:"scheduled_for"`
	Archived               bool          `json:"archived"`
	ApiKeyID               uuid.NullUUID `json:"api_key_id"`
	SenderID               uuid.NullUUID `json:"sender_id"`
	ID                     uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJob,
		arg.OriginalFileName,
		arg.TemplateID,
		arg.UpdatedAt,
		arg.NotificationCount,
		arg.NotificationsSent,
		arg.ProcessingStarted,
		arg.ProcessingFinished,
		arg.CreatedByID,
		arg.TemplateVersion,
		arg.NotificationsDelivered,
		arg.NotificationsFailed,
		arg.JobStatus,
		arg.ScheduledFor,
		arg.Archived,
		arg.ApiKeyID,
		arg.SenderID,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OriginalFileName,
		&i.ServiceID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NotificationCount,
		&i.NotificationsSent,
		&i.ProcessingStarted,
		&i.ProcessingFinished,
		&i.CreatedByID,
		&i.TemplateVersion,
		&i.NotificationsDelivered,
		&i.NotificationsFailed,
		&i.JobStatus,
		&i.ScheduledFor,
		&i.Archived,
		&i.ApiKeyID,
		&i.SenderID,
	)
	return i, err
}
