// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organisations.sql

package organisations

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addUserToOrganisation = `-- name: AddUserToOrganisation :exec
INSERT INTO user_to_organisation (user_id, organisation_id)
VALUES ($1, $2)
`

type AddUserToOrganisationParams struct {
	UserID         uuid.NullUUID `json:"user_id"`
	OrganisationID uuid.NullUUID `json:"organisation_id"`
}

func (q *Queries) AddUserToOrganisation(ctx context.Context, arg AddUserToOrganisationParams) error {
	_, err := q.db.ExecContext(ctx, addUserToOrganisation, arg.UserID, arg.OrganisationID)
	return err
}

const createInvitedOrgUser = `-- name: CreateInvitedOrgUser :one
INSERT INTO invited_organisation_users (
        id,
        email_address,
        invited_by_id,
        organisation_id,
        created_at,
        status
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
RETURNING id, email_address, invited_by_id, organisation_id, created_at, status
`

type CreateInvitedOrgUserParams struct {
	ID             uuid.UUID `json:"id"`
	EmailAddress   string    `json:"email_address"`
	InvitedByID    uuid.UUID `json:"invited_by_id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	CreatedAt      time.Time `json:"created_at"`
	Status         string    `json:"status"`
}

func (q *Queries) CreateInvitedOrgUser(ctx context.Context, arg CreateInvitedOrgUserParams) (InvitedOrganisationUser, error) {
	row := q.db.QueryRowContext(ctx, createInvitedOrgUser,
		arg.ID,
		arg.EmailAddress,
		arg.InvitedByID,
		arg.OrganisationID,
		arg.CreatedAt,
		arg.Status,
	)
	var i InvitedOrganisationUser
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.InvitedByID,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const createOrganisation = `-- name: CreateOrganisation :one
INSERT INTO organisation (
        id,
        name,
        active,
        created_at,
        updated_at,
        email_branding_id,
        letter_branding_id,
        agreement_signed,
        agreement_signed_at,
        agreement_signed_by_id,
        agreement_signed_version,
        crown,
        organisation_type,
        request_to_go_live_notes,
        agreement_signed_on_behalf_of_email_address,
        agreement_signed_on_behalf_of_name,
        default_branding_is_french
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17
    )
RETURNING id, name, active, created_at, updated_at, email_branding_id, letter_branding_id, agreement_signed, agreement_signed_at, agreement_signed_by_id, agreement_signed_version, crown, organisation_type, request_to_go_live_notes, agreement_signed_on_behalf_of_email_address, agreement_signed_on_behalf_of_name, default_branding_is_french
`

type CreateOrganisationParams struct {
	ID                                    uuid.UUID       `json:"id"`
	Name                                  string          `json:"name"`
	Active                                bool            `json:"active"`
	CreatedAt                             time.Time       `json:"created_at"`
	UpdatedAt                             sql.NullTime    `json:"updated_at"`
	EmailBrandingID                       uuid.NullUUID   `json:"email_branding_id"`
	LetterBrandingID                      uuid.NullUUID   `json:"letter_branding_id"`
	AgreementSigned                       sql.NullBool    `json:"agreement_signed"`
	AgreementSignedAt                     sql.NullTime    `json:"agreement_signed_at"`
	AgreementSignedByID                   uuid.NullUUID   `json:"agreement_signed_by_id"`
	AgreementSignedVersion                sql.NullFloat64 `json:"agreement_signed_version"`
	Crown                                 sql.NullBool    `json:"crown"`
	OrganisationType                      sql.NullString  `json:"organisation_type"`
	RequestToGoLiveNotes                  sql.NullString  `json:"request_to_go_live_notes"`
	AgreementSignedOnBehalfOfEmailAddress sql.NullString  `json:"agreement_signed_on_behalf_of_email_address"`
	AgreementSignedOnBehalfOfName         sql.NullString  `json:"agreement_signed_on_behalf_of_name"`
	DefaultBrandingIsFrench               sql.NullBool    `json:"default_branding_is_french"`
}

func (q *Queries) CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRowContext(ctx, createOrganisation,
		arg.ID,
		arg.Name,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.EmailBrandingID,
		arg.LetterBrandingID,
		arg.AgreementSigned,
		arg.AgreementSignedAt,
		arg.AgreementSignedByID,
		arg.AgreementSignedVersion,
		arg.Crown,
		arg.OrganisationType,
		arg.RequestToGoLiveNotes,
		arg.AgreementSignedOnBehalfOfEmailAddress,
		arg.AgreementSignedOnBehalfOfName,
		arg.DefaultBrandingIsFrench,
	)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailBrandingID,
		&i.LetterBrandingID,
		&i.AgreementSigned,
		&i.AgreementSignedAt,
		&i.AgreementSignedByID,
		&i.AgreementSignedVersion,
		&i.Crown,
		&i.OrganisationType,
		&i.RequestToGoLiveNotes,
		&i.AgreementSignedOnBehalfOfEmailAddress,
		&i.AgreementSignedOnBehalfOfName,
		&i.DefaultBrandingIsFrench,
	)
	return i, err
}

const getAllOrganisations = `-- name: GetAllOrganisations :many
SELECT id, name, active, created_at, updated_at, email_branding_id, letter_branding_id, agreement_signed, agreement_signed_at, agreement_signed_by_id, agreement_signed_version, crown, organisation_type, request_to_go_live_notes, agreement_signed_on_behalf_of_email_address, agreement_signed_on_behalf_of_name, default_branding_is_french
FROM organisation
ORDER BY name ASC
`

func (q *Queries) GetAllOrganisations(ctx context.Context) ([]Organisation, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrganisations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organisation
	for rows.Next() {
		var i Organisation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailBrandingID,
			&i.LetterBrandingID,
			&i.AgreementSigned,
			&i.AgreementSignedAt,
			&i.AgreementSignedByID,
			&i.AgreementSignedVersion,
			&i.Crown,
			&i.OrganisationType,
			&i.RequestToGoLiveNotes,
			&i.AgreementSignedOnBehalfOfEmailAddress,
			&i.AgreementSignedOnBehalfOfName,
			&i.DefaultBrandingIsFrench,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvitedOrgUsers = `-- name: GetInvitedOrgUsers :many
SELECT id, email_address, invited_by_id, organisation_id, created_at, status
FROM invited_organisation_users
WHERE organisation_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetInvitedOrgUsers(ctx context.Context, organisationID uuid.UUID) ([]InvitedOrganisationUser, error) {
	rows, err := q.db.QueryContext(ctx, getInvitedOrgUsers, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvitedOrganisationUser
	for rows.Next() {
		var i InvitedOrganisationUser
		if err := rows.Scan(
			&i.ID,
			&i.EmailAddress,
			&i.InvitedByID,
			&i.OrganisationID,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganisationByDomain = `-- name: GetOrganisationByDomain :one
SELECT o.id, o.name, o.active, o.created_at, o.updated_at, o.email_branding_id, o.letter_branding_id, o.agreement_signed, o.agreement_signed_at, o.agreement_signed_by_id, o.agreement_signed_version, o.crown, o.organisation_type, o.request_to_go_live_notes, o.agreement_signed_on_behalf_of_email_address, o.agreement_signed_on_behalf_of_name, o.default_branding_is_french
FROM organisation AS o
    JOIN domain AS d ON d.organisation_id = o.id
WHERE d.domain = $1
LIMIT 1
`

func (q *Queries) GetOrganisationByDomain(ctx context.Context, domain string) (Organisation, error) {
	row := q.db.QueryRowContext(ctx, getOrganisationByDomain, domain)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailBrandingID,
		&i.LetterBrandingID,
		&i.AgreementSigned,
		&i.AgreementSignedAt,
		&i.AgreementSignedByID,
		&i.AgreementSignedVersion,
		&i.Crown,
		&i.OrganisationType,
		&i.RequestToGoLiveNotes,
		&i.AgreementSignedOnBehalfOfEmailAddress,
		&i.AgreementSignedOnBehalfOfName,
		&i.DefaultBrandingIsFrench,
	)
	return i, err
}

const getOrganisationByID = `-- name: GetOrganisationByID :one
SELECT id, name, active, created_at, updated_at, email_branding_id, letter_branding_id, agreement_signed, agreement_signed_at, agreement_signed_by_id, agreement_signed_version, crown, organisation_type, request_to_go_live_notes, agreement_signed_on_behalf_of_email_address, agreement_signed_on_behalf_of_name, default_branding_is_french
FROM organisation
WHERE id = $1
`

func (q *Queries) GetOrganisationByID(ctx context.Context, id uuid.UUID) (Organisation, error) {
	row := q.db.QueryRowContext(ctx, getOrganisationByID, id)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailBrandingID,
		&i.LetterBrandingID,
		&i.AgreementSigned,
		&i.AgreementSignedAt,
		&i.AgreementSignedByID,
		&i.AgreementSignedVersion,
		&i.Crown,
		&i.OrganisationType,
		&i.RequestToGoLiveNotes,
		&i.AgreementSignedOnBehalfOfEmailAddress,
		&i.AgreementSignedOnBehalfOfName,
		&i.DefaultBrandingIsFrench,
	)
	return i, err
}

const getServicesByOrganisationID = `-- name: GetServicesByOrganisationID :many
SELECT id, name, created_at, updated_at, active, message_limit, restricted, email_from, created_by_id, version, research_mode, organisation_type, prefix_sms, crown, rate_limit, contact_link, consent_to_research, volume_email, volume_letter, volume_sms, count_as_live, go_live_at, go_live_user_id, organisation_id, sending_domain, default_branding_is_french, sms_daily_limit, organisation_notes, sensitive_service, email_annual_limit, sms_annual_limit, suspended_by_id, suspended_at
FROM services
WHERE organisation_id = $1
ORDER BY name ASC
`

func (q *Queries) GetServicesByOrganisationID(ctx context.Context, organisationID uuid.NullUUID) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getServicesByOrganisationID, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Active,
			&i.MessageLimit,
			&i.Restricted,
			&i.EmailFrom,
			&i.CreatedByID,
			&i.Version,
			&i.ResearchMode,
			&i.OrganisationType,
			&i.PrefixSms,
			&i.Crown,
			&i.RateLimit,
			&i.ContactLink,
			&i.ConsentToResearch,
			&i.VolumeEmail,
			&i.VolumeLetter,
			&i.VolumeSms,
			&i.CountAsLive,
			&i.GoLiveAt,
			&i.GoLiveUserID,
			&i.OrganisationID,
			&i.SendingDomain,
			&i.DefaultBrandingIsFrench,
			&i.SmsDailyLimit,
			&i.OrganisationNotes,
			&i.SensitiveService,
			&i.EmailAnnualLimit,
			&i.SmsAnnualLimit,
			&i.SuspendedByID,
			&i.SuspendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByOrganisationID = `-- name: GetUsersByOrganisationID :many
SELECT u.id, u.name, u.email_address, u.created_at, u.updated_at, u._password, u.mobile_number, u.password_changed_at, u.logged_in_at, u.failed_login_count, u.state, u.platform_admin, u.current_session_id, u.auth_type, u.blocked, u.additional_information, u.password_expired, u.verified_phonenumber, u.default_editor_is_rte
FROM users AS u
    JOIN user_to_organisation AS uto ON uto.user_id = u.id
WHERE uto.organisation_id = $1
ORDER BY u.name ASC
`

func (q *Queries) GetUsersByOrganisationID(ctx context.Context, organisationID uuid.NullUUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByOrganisationID, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EmailAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Password,
			&i.MobileNumber,
			&i.PasswordChangedAt,
			&i.LoggedInAt,
			&i.FailedLoginCount,
			&i.State,
			&i.PlatformAdmin,
			&i.CurrentSessionID,
			&i.AuthType,
			&i.Blocked,
			&i.AdditionalInformation,
			&i.PasswordExpired,
			&i.VerifiedPhonenumber,
			&i.DefaultEditorIsRte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isOrganisationNameUnique = `-- name: IsOrganisationNameUnique :one
SELECT NOT EXISTS(
        SELECT 1
        FROM organisation
        WHERE lower(name) = lower($1)
            AND id <> coalesce($2, id)
    ) AS is_unique
`

type IsOrganisationNameUniqueParams struct {
	Name      string        `json:"name"`
	ExcludeID uuid.NullUUID `json:"exclude_id"`
}

func (q *Queries) IsOrganisationNameUnique(ctx context.Context, arg IsOrganisationNameUniqueParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isOrganisationNameUnique, arg.Name, arg.ExcludeID)
	var is_unique bool
	err := row.Scan(&is_unique)
	return is_unique, err
}

const linkServiceToOrganisation = `-- name: LinkServiceToOrganisation :one
UPDATE services
SET organisation_id = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, name, created_at, updated_at, active, message_limit, restricted, email_from, created_by_id, version, research_mode, organisation_type, prefix_sms, crown, rate_limit, contact_link, consent_to_research, volume_email, volume_letter, volume_sms, count_as_live, go_live_at, go_live_user_id, organisation_id, sending_domain, default_branding_is_french, sms_daily_limit, organisation_notes, sensitive_service, email_annual_limit, sms_annual_limit, suspended_by_id, suspended_at
`

type LinkServiceToOrganisationParams struct {
	OrganisationID uuid.NullUUID `json:"organisation_id"`
	ServiceID      uuid.UUID     `json:"service_id"`
}

func (q *Queries) LinkServiceToOrganisation(ctx context.Context, arg LinkServiceToOrganisationParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, linkServiceToOrganisation, arg.OrganisationID, arg.ServiceID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.MessageLimit,
		&i.Restricted,
		&i.EmailFrom,
		&i.CreatedByID,
		&i.Version,
		&i.ResearchMode,
		&i.OrganisationType,
		&i.PrefixSms,
		&i.Crown,
		&i.RateLimit,
		&i.ContactLink,
		&i.ConsentToResearch,
		&i.VolumeEmail,
		&i.VolumeLetter,
		&i.VolumeSms,
		&i.CountAsLive,
		&i.GoLiveAt,
		&i.GoLiveUserID,
		&i.OrganisationID,
		&i.SendingDomain,
		&i.DefaultBrandingIsFrench,
		&i.SmsDailyLimit,
		&i.OrganisationNotes,
		&i.SensitiveService,
		&i.EmailAnnualLimit,
		&i.SmsAnnualLimit,
		&i.SuspendedByID,
		&i.SuspendedAt,
	)
	return i, err
}

const updateInvitedOrgUser = `-- name: UpdateInvitedOrgUser :one
UPDATE invited_organisation_users
SET email_address = $1,
    status = $2
WHERE id = $3
RETURNING id, email_address, invited_by_id, organisation_id, created_at, status
`

type UpdateInvitedOrgUserParams struct {
	EmailAddress string    `json:"email_address"`
	Status       string    `json:"status"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateInvitedOrgUser(ctx context.Context, arg UpdateInvitedOrgUserParams) (InvitedOrganisationUser, error) {
	row := q.db.QueryRowContext(ctx, updateInvitedOrgUser, arg.EmailAddress, arg.Status, arg.ID)
	var i InvitedOrganisationUser
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.InvitedByID,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const updateOrganisation = `-- name: UpdateOrganisation :one
UPDATE organisation
SET name = $1,
    active = $2,
    updated_at = $3,
    email_branding_id = $4,
    letter_branding_id = $5,
    agreement_signed = $6,
    agreement_signed_at = $7,
    agreement_signed_by_id = $8,
    agreement_signed_version = $9,
    crown = $10,
    organisation_type = $11,
    request_to_go_live_notes = $12,
    agreement_signed_on_behalf_of_email_address = $13,
    agreement_signed_on_behalf_of_name = $14,
    default_branding_is_french = $15
WHERE id = $16
RETURNING id, name, active, created_at, updated_at, email_branding_id, letter_branding_id, agreement_signed, agreement_signed_at, agreement_signed_by_id, agreement_signed_version, crown, organisation_type, request_to_go_live_notes, agreement_signed_on_behalf_of_email_address, agreement_signed_on_behalf_of_name, default_branding_is_french
`

type UpdateOrganisationParams struct {
	Name                                  string          `json:"name"`
	Active                                bool            `json:"active"`
	UpdatedAt                             sql.NullTime    `json:"updated_at"`
	EmailBrandingID                       uuid.NullUUID   `json:"email_branding_id"`
	LetterBrandingID                      uuid.NullUUID   `json:"letter_branding_id"`
	AgreementSigned                       sql.NullBool    `json:"agreement_signed"`
	AgreementSignedAt                     sql.NullTime    `json:"agreement_signed_at"`
	AgreementSignedByID                   uuid.NullUUID   `json:"agreement_signed_by_id"`
	AgreementSignedVersion                sql.NullFloat64 `json:"agreement_signed_version"`
	Crown                                 sql.NullBool    `json:"crown"`
	OrganisationType                      sql.NullString  `json:"organisation_type"`
	RequestToGoLiveNotes                  sql.NullString  `json:"request_to_go_live_notes"`
	AgreementSignedOnBehalfOfEmailAddress sql.NullString  `json:"agreement_signed_on_behalf_of_email_address"`
	AgreementSignedOnBehalfOfName         sql.NullString  `json:"agreement_signed_on_behalf_of_name"`
	DefaultBrandingIsFrench               sql.NullBool    `json:"default_branding_is_french"`
	ID                                    uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateOrganisation(ctx context.Context, arg UpdateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRowContext(ctx, updateOrganisation,
		arg.Name,
		arg.Active,
		arg.UpdatedAt,
		arg.EmailBrandingID,
		arg.LetterBrandingID,
		arg.AgreementSigned,
		arg.AgreementSignedAt,
		arg.AgreementSignedByID,
		arg.AgreementSignedVersion,
		arg.Crown,
		arg.OrganisationType,
		arg.RequestToGoLiveNotes,
		arg.AgreementSignedOnBehalfOfEmailAddress,
		arg.AgreementSignedOnBehalfOfName,
		arg.DefaultBrandingIsFrench,
		arg.ID,
	)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailBrandingID,
		&i.LetterBrandingID,
		&i.AgreementSigned,
		&i.AgreementSignedAt,
		&i.AgreementSignedByID,
		&i.AgreementSignedVersion,
		&i.Crown,
		&i.OrganisationType,
		&i.RequestToGoLiveNotes,
		&i.AgreementSignedOnBehalfOfEmailAddress,
		&i.AgreementSignedOnBehalfOfName,
		&i.DefaultBrandingIsFrench,
	)
	return i, err
}
