// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package providers

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getAllProviders = `-- name: GetAllProviders :many
SELECT id, display_name, identifier, priority, notification_type, active, updated_at, version, created_by_id, supports_international
FROM provider_details
ORDER BY notification_type ASC,
    priority ASC,
    display_name ASC
`

func (q *Queries) GetAllProviders(ctx context.Context) ([]ProviderDetail, error) {
	rows, err := q.db.QueryContext(ctx, getAllProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderDetail
	for rows.Next() {
		var i ProviderDetail
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Identifier,
			&i.Priority,
			&i.NotificationType,
			&i.Active,
			&i.UpdatedAt,
			&i.Version,
			&i.CreatedByID,
			&i.SupportsInternational,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, display_name, identifier, priority, notification_type, active, updated_at, version, created_by_id, supports_international
FROM provider_details
WHERE id = $1
`

func (q *Queries) GetProviderByID(ctx context.Context, id uuid.UUID) (ProviderDetail, error) {
	row := q.db.QueryRowContext(ctx, getProviderByID, id)
	var i ProviderDetail
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Identifier,
		&i.Priority,
		&i.NotificationType,
		&i.Active,
		&i.UpdatedAt,
		&i.Version,
		&i.CreatedByID,
		&i.SupportsInternational,
	)
	return i, err
}

const getProviderVersions = `-- name: GetProviderVersions :many
SELECT id, display_name, identifier, priority, notification_type, active, version, updated_at, created_by_id, supports_international
FROM provider_details_history
WHERE id = $1
ORDER BY version DESC
`

func (q *Queries) GetProviderVersions(ctx context.Context, id uuid.UUID) ([]ProviderDetailsHistory, error) {
	rows, err := q.db.QueryContext(ctx, getProviderVersions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderDetailsHistory
	for rows.Next() {
		var i ProviderDetailsHistory
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Identifier,
			&i.Priority,
			&i.NotificationType,
			&i.Active,
			&i.Version,
			&i.UpdatedAt,
			&i.CreatedByID,
			&i.SupportsInternational,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProviderHistory = `-- name: InsertProviderHistory :exec
INSERT INTO provider_details_history (
        id,
        display_name,
        identifier,
        priority,
        notification_type,
        active,
        version,
        updated_at,
        created_by_id,
        supports_international
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10
    )
`

type InsertProviderHistoryParams struct {
	ID                    uuid.UUID        `json:"id"`
	DisplayName           string           `json:"display_name"`
	Identifier            string           `json:"identifier"`
	Priority              int32            `json:"priority"`
	NotificationType      NotificationType `json:"notification_type"`
	Active                bool             `json:"active"`
	Version               int32            `json:"version"`
	UpdatedAt             sql.NullTime     `json:"updated_at"`
	CreatedByID           uuid.NullUUID    `json:"created_by_id"`
	SupportsInternational bool             `json:"supports_international"`
}

func (q *Queries) InsertProviderHistory(ctx context.Context, arg InsertProviderHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertProviderHistory,
		arg.ID,
		arg.DisplayName,
		arg.Identifier,
		arg.Priority,
		arg.NotificationType,
		arg.Active,
		arg.Version,
		arg.UpdatedAt,
		arg.CreatedByID,
		arg.SupportsInternational,
	)
	return err
}

const toggleSMSProvider = `-- name: ToggleSMSProvider :many
UPDATE provider_details
SET active = CASE
        WHEN id = $1 THEN true
        ELSE false
    END,
    updated_at = now()
WHERE notification_type = 'sms'
RETURNING id, display_name, identifier, priority, notification_type, active, updated_at, version, created_by_id, supports_international
`

func (q *Queries) ToggleSMSProvider(ctx context.Context, id uuid.UUID) ([]ProviderDetail, error) {
	rows, err := q.db.QueryContext(ctx, toggleSMSProvider, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderDetail
	for rows.Next() {
		var i ProviderDetail
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Identifier,
			&i.Priority,
			&i.NotificationType,
			&i.Active,
			&i.UpdatedAt,
			&i.Version,
			&i.CreatedByID,
			&i.SupportsInternational,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE provider_details
SET display_name = $1,
    identifier = $2,
    priority = $3,
    notification_type = $4,
    active = $5,
    updated_at = $6,
    version = $7,
    created_by_id = $8,
    supports_international = $9
WHERE id = $10
RETURNING id, display_name, identifier, priority, notification_type, active, updated_at, version, created_by_id, supports_international
`

type UpdateProviderParams struct {
	DisplayName           string           `json:"display_name"`
	Identifier            string           `json:"identifier"`
	Priority              int32            `json:"priority"`
	NotificationType      NotificationType `json:"notification_type"`
	Active                bool             `json:"active"`
	UpdatedAt             sql.NullTime     `json:"updated_at"`
	Version               int32            `json:"version"`
	CreatedByID           uuid.NullUUID    `json:"created_by_id"`
	SupportsInternational bool             `json:"supports_international"`
	ID                    uuid.UUID        `json:"id"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (ProviderDetail, error) {
	row := q.db.QueryRowContext(ctx, updateProvider,
		arg.DisplayName,
		arg.Identifier,
		arg.Priority,
		arg.NotificationType,
		arg.Active,
		arg.UpdatedAt,
		arg.Version,
		arg.CreatedByID,
		arg.SupportsInternational,
		arg.ID,
	)
	var i ProviderDetail
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Identifier,
		&i.Priority,
		&i.NotificationType,
		&i.Active,
		&i.UpdatedAt,
		&i.Version,
		&i.CreatedByID,
		&i.SupportsInternational,
	)
	return i, err
}
