// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: annual_limits.sql

package annual_limits

import (
	"context"

	"github.com/google/uuid"
)

const getAnnualLimitsDataByPeriod = `-- name: GetAnnualLimitsDataByPeriod :many
SELECT service_id, time_period, annual_email_limit, annual_sms_limit, notification_type, notification_count
FROM annual_limits_data
WHERE time_period = $1
ORDER BY service_id,
    notification_type
`

func (q *Queries) GetAnnualLimitsDataByPeriod(ctx context.Context, timePeriod string) ([]AnnualLimitsDatum, error) {
	rows, err := q.db.QueryContext(ctx, getAnnualLimitsDataByPeriod, timePeriod)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnnualLimitsDatum
	for rows.Next() {
		var i AnnualLimitsDatum
		if err := rows.Scan(
			&i.ServiceID,
			&i.TimePeriod,
			&i.AnnualEmailLimit,
			&i.AnnualSmsLimit,
			&i.NotificationType,
			&i.NotificationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnnualLimitsDataByServiceAndPeriod = `-- name: GetAnnualLimitsDataByServiceAndPeriod :many
SELECT service_id, time_period, annual_email_limit, annual_sms_limit, notification_type, notification_count
FROM annual_limits_data
WHERE service_id = $1
    AND time_period = $2
ORDER BY notification_type
`

type GetAnnualLimitsDataByServiceAndPeriodParams struct {
	ServiceID  uuid.UUID `json:"service_id"`
	TimePeriod string    `json:"time_period"`
}

func (q *Queries) GetAnnualLimitsDataByServiceAndPeriod(ctx context.Context, arg GetAnnualLimitsDataByServiceAndPeriodParams) ([]AnnualLimitsDatum, error) {
	rows, err := q.db.QueryContext(ctx, getAnnualLimitsDataByServiceAndPeriod, arg.ServiceID, arg.TimePeriod)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnnualLimitsDatum
	for rows.Next() {
		var i AnnualLimitsDatum
		if err := rows.Scan(
			&i.ServiceID,
			&i.TimePeriod,
			&i.AnnualEmailLimit,
			&i.AnnualSmsLimit,
			&i.NotificationType,
			&i.NotificationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertQuarterData = `-- name: InsertQuarterData :exec
INSERT INTO annual_limits_data (
        service_id,
        time_period,
        annual_email_limit,
        annual_sms_limit,
        notification_type,
        notification_count
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    ) ON CONFLICT (service_id, notification_type, time_period) DO
UPDATE
SET annual_email_limit = EXCLUDED.annual_email_limit,
    annual_sms_limit = EXCLUDED.annual_sms_limit,
    notification_count = EXCLUDED.notification_count
`

type InsertQuarterDataParams struct {
	ServiceID         uuid.UUID `json:"service_id"`
	TimePeriod        string    `json:"time_period"`
	AnnualEmailLimit  int64     `json:"annual_email_limit"`
	AnnualSmsLimit    int64     `json:"annual_sms_limit"`
	NotificationType  string    `json:"notification_type"`
	NotificationCount int64     `json:"notification_count"`
}

func (q *Queries) InsertQuarterData(ctx context.Context, arg InsertQuarterDataParams) error {
	_, err := q.db.ExecContext(ctx, insertQuarterData,
		arg.ServiceID,
		arg.TimePeriod,
		arg.AnnualEmailLimit,
		arg.AnnualSmsLimit,
		arg.NotificationType,
		arg.NotificationCount,
	)
	return err
}
