// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package annual_limits

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type InvitedUsersStatusTypes string

const (
	InvitedUsersStatusTypesPending   InvitedUsersStatusTypes = "pending"
	InvitedUsersStatusTypesAccepted  InvitedUsersStatusTypes = "accepted"
	InvitedUsersStatusTypesCancelled InvitedUsersStatusTypes = "cancelled"
)

func (e *InvitedUsersStatusTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitedUsersStatusTypes(s)
	case string:
		*e = InvitedUsersStatusTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitedUsersStatusTypes: %T", src)
	}
	return nil
}

type NullInvitedUsersStatusTypes struct {
	InvitedUsersStatusTypes InvitedUsersStatusTypes `json:"invited_users_status_types"`
	Valid                   bool                    `json:"valid"` // Valid is true if InvitedUsersStatusTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitedUsersStatusTypes) Scan(value interface{}) error {
	if value == nil {
		ns.InvitedUsersStatusTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitedUsersStatusTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitedUsersStatusTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitedUsersStatusTypes), nil
}

func (e InvitedUsersStatusTypes) Valid() bool {
	switch e {
	case InvitedUsersStatusTypesPending,
		InvitedUsersStatusTypesAccepted,
		InvitedUsersStatusTypesCancelled:
		return true
	}
	return false
}

func AllInvitedUsersStatusTypesValues() []InvitedUsersStatusTypes {
	return []InvitedUsersStatusTypes{
		InvitedUsersStatusTypesPending,
		InvitedUsersStatusTypesAccepted,
		InvitedUsersStatusTypesCancelled,
	}
}

type JobStatusTypes string

const (
	JobStatusTypesPending               JobStatusTypes = "pending"
	JobStatusTypesInprogress            JobStatusTypes = "in progress"
	JobStatusTypesFinished              JobStatusTypes = "finished"
	JobStatusTypesSendinglimitsexceeded JobStatusTypes = "sending limits exceeded"
)

func (e *JobStatusTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatusTypes(s)
	case string:
		*e = JobStatusTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatusTypes: %T", src)
	}
	return nil
}

type NullJobStatusTypes struct {
	JobStatusTypes JobStatusTypes `json:"job_status_types"`
	Valid          bool           `json:"valid"` // Valid is true if JobStatusTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatusTypes) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatusTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatusTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatusTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatusTypes), nil
}

func (e JobStatusTypes) Valid() bool {
	switch e {
	case JobStatusTypesPending,
		JobStatusTypesInprogress,
		JobStatusTypesFinished,
		JobStatusTypesSendinglimitsexceeded:
		return true
	}
	return false
}

func AllJobStatusTypesValues() []JobStatusTypes {
	return []JobStatusTypes{
		JobStatusTypesPending,
		JobStatusTypesInprogress,
		JobStatusTypesFinished,
		JobStatusTypesSendinglimitsexceeded,
	}
}

type NotificationFeedbackSubtypes string

const (
	NotificationFeedbackSubtypesGeneral                  NotificationFeedbackSubtypes = "general"
	NotificationFeedbackSubtypesNoEmail                  NotificationFeedbackSubtypes = "no-email"
	NotificationFeedbackSubtypesSuppressed               NotificationFeedbackSubtypes = "suppressed"
	NotificationFeedbackSubtypesOnAccountSuppressionList NotificationFeedbackSubtypes = "on-account-suppression-list"
	NotificationFeedbackSubtypesMailboxFull              NotificationFeedbackSubtypes = "mailbox-full"
	NotificationFeedbackSubtypesMessageTooLarge          NotificationFeedbackSubtypes = "message-too-large"
	NotificationFeedbackSubtypesContentRejected          NotificationFeedbackSubtypes = "content-rejected"
	NotificationFeedbackSubtypesAttachmentRejected       NotificationFeedbackSubtypes = "attachment-rejected"
	NotificationFeedbackSubtypesUnknownBounceSubtype     NotificationFeedbackSubtypes = "unknown-bounce-subtype"
)

func (e *NotificationFeedbackSubtypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationFeedbackSubtypes(s)
	case string:
		*e = NotificationFeedbackSubtypes(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationFeedbackSubtypes: %T", src)
	}
	return nil
}

type NullNotificationFeedbackSubtypes struct {
	NotificationFeedbackSubtypes NotificationFeedbackSubtypes `json:"notification_feedback_subtypes"`
	Valid                        bool                         `json:"valid"` // Valid is true if NotificationFeedbackSubtypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationFeedbackSubtypes) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationFeedbackSubtypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationFeedbackSubtypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationFeedbackSubtypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationFeedbackSubtypes), nil
}

func (e NotificationFeedbackSubtypes) Valid() bool {
	switch e {
	case NotificationFeedbackSubtypesGeneral,
		NotificationFeedbackSubtypesNoEmail,
		NotificationFeedbackSubtypesSuppressed,
		NotificationFeedbackSubtypesOnAccountSuppressionList,
		NotificationFeedbackSubtypesMailboxFull,
		NotificationFeedbackSubtypesMessageTooLarge,
		NotificationFeedbackSubtypesContentRejected,
		NotificationFeedbackSubtypesAttachmentRejected,
		NotificationFeedbackSubtypesUnknownBounceSubtype:
		return true
	}
	return false
}

func AllNotificationFeedbackSubtypesValues() []NotificationFeedbackSubtypes {
	return []NotificationFeedbackSubtypes{
		NotificationFeedbackSubtypesGeneral,
		NotificationFeedbackSubtypesNoEmail,
		NotificationFeedbackSubtypesSuppressed,
		NotificationFeedbackSubtypesOnAccountSuppressionList,
		NotificationFeedbackSubtypesMailboxFull,
		NotificationFeedbackSubtypesMessageTooLarge,
		NotificationFeedbackSubtypesContentRejected,
		NotificationFeedbackSubtypesAttachmentRejected,
		NotificationFeedbackSubtypesUnknownBounceSubtype,
	}
}

type NotificationFeedbackTypes string

const (
	NotificationFeedbackTypesHardBounce    NotificationFeedbackTypes = "hard-bounce"
	NotificationFeedbackTypesSoftBounce    NotificationFeedbackTypes = "soft-bounce"
	NotificationFeedbackTypesUnknownBounce NotificationFeedbackTypes = "unknown-bounce"
)

func (e *NotificationFeedbackTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationFeedbackTypes(s)
	case string:
		*e = NotificationFeedbackTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationFeedbackTypes: %T", src)
	}
	return nil
}

type NullNotificationFeedbackTypes struct {
	NotificationFeedbackTypes NotificationFeedbackTypes `json:"notification_feedback_types"`
	Valid                     bool                      `json:"valid"` // Valid is true if NotificationFeedbackTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationFeedbackTypes) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationFeedbackTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationFeedbackTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationFeedbackTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationFeedbackTypes), nil
}

func (e NotificationFeedbackTypes) Valid() bool {
	switch e {
	case NotificationFeedbackTypesHardBounce,
		NotificationFeedbackTypesSoftBounce,
		NotificationFeedbackTypesUnknownBounce:
		return true
	}
	return false
}

func AllNotificationFeedbackTypesValues() []NotificationFeedbackTypes {
	return []NotificationFeedbackTypes{
		NotificationFeedbackTypesHardBounce,
		NotificationFeedbackTypesSoftBounce,
		NotificationFeedbackTypesUnknownBounce,
	}
}

type NotificationType string

const (
	NotificationTypeEmail  NotificationType = "email"
	NotificationTypeSms    NotificationType = "sms"
	NotificationTypeLetter NotificationType = "letter"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

func (e NotificationType) Valid() bool {
	switch e {
	case NotificationTypeEmail,
		NotificationTypeSms,
		NotificationTypeLetter:
		return true
	}
	return false
}

func AllNotificationTypeValues() []NotificationType {
	return []NotificationType{
		NotificationTypeEmail,
		NotificationTypeSms,
		NotificationTypeLetter,
	}
}

type NotifyStatusType string

const (
	NotifyStatusTypeCreated          NotifyStatusType = "created"
	NotifyStatusTypeSending          NotifyStatusType = "sending"
	NotifyStatusTypeDelivered        NotifyStatusType = "delivered"
	NotifyStatusTypePending          NotifyStatusType = "pending"
	NotifyStatusTypeFailed           NotifyStatusType = "failed"
	NotifyStatusTypeTechnicalFailure NotifyStatusType = "technical-failure"
	NotifyStatusTypeTemporaryFailure NotifyStatusType = "temporary-failure"
	NotifyStatusTypePermanentFailure NotifyStatusType = "permanent-failure"
	NotifyStatusTypeSent             NotifyStatusType = "sent"
)

func (e *NotifyStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotifyStatusType(s)
	case string:
		*e = NotifyStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotifyStatusType: %T", src)
	}
	return nil
}

type NullNotifyStatusType struct {
	NotifyStatusType NotifyStatusType `json:"notify_status_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotifyStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotifyStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.NotifyStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotifyStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotifyStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotifyStatusType), nil
}

func (e NotifyStatusType) Valid() bool {
	switch e {
	case NotifyStatusTypeCreated,
		NotifyStatusTypeSending,
		NotifyStatusTypeDelivered,
		NotifyStatusTypePending,
		NotifyStatusTypeFailed,
		NotifyStatusTypeTechnicalFailure,
		NotifyStatusTypeTemporaryFailure,
		NotifyStatusTypePermanentFailure,
		NotifyStatusTypeSent:
		return true
	}
	return false
}

func AllNotifyStatusTypeValues() []NotifyStatusType {
	return []NotifyStatusType{
		NotifyStatusTypeCreated,
		NotifyStatusTypeSending,
		NotifyStatusTypeDelivered,
		NotifyStatusTypePending,
		NotifyStatusTypeFailed,
		NotifyStatusTypeTechnicalFailure,
		NotifyStatusTypeTemporaryFailure,
		NotifyStatusTypePermanentFailure,
		NotifyStatusTypeSent,
	}
}

type PermissionTypes string

const (
	PermissionTypesManageUsers     PermissionTypes = "manage_users"
	PermissionTypesManageTemplates PermissionTypes = "manage_templates"
	PermissionTypesManageSettings  PermissionTypes = "manage_settings"
	PermissionTypesSendTexts       PermissionTypes = "send_texts"
	PermissionTypesSendEmails      PermissionTypes = "send_emails"
	PermissionTypesSendLetters     PermissionTypes = "send_letters"
	PermissionTypesManageApiKeys   PermissionTypes = "manage_api_keys"
	PermissionTypesPlatformAdmin   PermissionTypes = "platform_admin"
	PermissionTypesViewActivity    PermissionTypes = "view_activity"
)

func (e *PermissionTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionTypes(s)
	case string:
		*e = PermissionTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionTypes: %T", src)
	}
	return nil
}

type NullPermissionTypes struct {
	PermissionTypes PermissionTypes `json:"permission_types"`
	Valid           bool            `json:"valid"` // Valid is true if PermissionTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionTypes) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionTypes), nil
}

func (e PermissionTypes) Valid() bool {
	switch e {
	case PermissionTypesManageUsers,
		PermissionTypesManageTemplates,
		PermissionTypesManageSettings,
		PermissionTypesSendTexts,
		PermissionTypesSendEmails,
		PermissionTypesSendLetters,
		PermissionTypesManageApiKeys,
		PermissionTypesPlatformAdmin,
		PermissionTypesViewActivity:
		return true
	}
	return false
}

func AllPermissionTypesValues() []PermissionTypes {
	return []PermissionTypes{
		PermissionTypesManageUsers,
		PermissionTypesManageTemplates,
		PermissionTypesManageSettings,
		PermissionTypesSendTexts,
		PermissionTypesSendEmails,
		PermissionTypesSendLetters,
		PermissionTypesManageApiKeys,
		PermissionTypesPlatformAdmin,
		PermissionTypesViewActivity,
	}
}

type RecipientType string

const (
	RecipientTypeMobile RecipientType = "mobile"
	RecipientTypeEmail  RecipientType = "email"
)

func (e *RecipientType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecipientType(s)
	case string:
		*e = RecipientType(s)
	default:
		return fmt.Errorf("unsupported scan type for RecipientType: %T", src)
	}
	return nil
}

type NullRecipientType struct {
	RecipientType RecipientType `json:"recipient_type"`
	Valid         bool          `json:"valid"` // Valid is true if RecipientType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecipientType) Scan(value interface{}) error {
	if value == nil {
		ns.RecipientType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecipientType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecipientType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecipientType), nil
}

func (e RecipientType) Valid() bool {
	switch e {
	case RecipientTypeMobile,
		RecipientTypeEmail:
		return true
	}
	return false
}

func AllRecipientTypeValues() []RecipientType {
	return []RecipientType{
		RecipientTypeMobile,
		RecipientTypeEmail,
	}
}

type SmsSendingVehicle string

const (
	SmsSendingVehicleShortCode SmsSendingVehicle = "short_code"
	SmsSendingVehicleLongCode  SmsSendingVehicle = "long_code"
)

func (e *SmsSendingVehicle) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SmsSendingVehicle(s)
	case string:
		*e = SmsSendingVehicle(s)
	default:
		return fmt.Errorf("unsupported scan type for SmsSendingVehicle: %T", src)
	}
	return nil
}

type NullSmsSendingVehicle struct {
	SmsSendingVehicle SmsSendingVehicle `json:"sms_sending_vehicle"`
	Valid             bool              `json:"valid"` // Valid is true if SmsSendingVehicle is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSmsSendingVehicle) Scan(value interface{}) error {
	if value == nil {
		ns.SmsSendingVehicle, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SmsSendingVehicle.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSmsSendingVehicle) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SmsSendingVehicle), nil
}

func (e SmsSendingVehicle) Valid() bool {
	switch e {
	case SmsSendingVehicleShortCode,
		SmsSendingVehicleLongCode:
		return true
	}
	return false
}

func AllSmsSendingVehicleValues() []SmsSendingVehicle {
	return []SmsSendingVehicle{
		SmsSendingVehicleShortCode,
		SmsSendingVehicleLongCode,
	}
}

type TemplateType string

const (
	TemplateTypeSms    TemplateType = "sms"
	TemplateTypeEmail  TemplateType = "email"
	TemplateTypeLetter TemplateType = "letter"
)

func (e *TemplateType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TemplateType(s)
	case string:
		*e = TemplateType(s)
	default:
		return fmt.Errorf("unsupported scan type for TemplateType: %T", src)
	}
	return nil
}

type NullTemplateType struct {
	TemplateType TemplateType `json:"template_type"`
	Valid        bool         `json:"valid"` // Valid is true if TemplateType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTemplateType) Scan(value interface{}) error {
	if value == nil {
		ns.TemplateType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TemplateType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTemplateType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TemplateType), nil
}

func (e TemplateType) Valid() bool {
	switch e {
	case TemplateTypeSms,
		TemplateTypeEmail,
		TemplateTypeLetter:
		return true
	}
	return false
}

func AllTemplateTypeValues() []TemplateType {
	return []TemplateType{
		TemplateTypeSms,
		TemplateTypeEmail,
		TemplateTypeLetter,
	}
}

type VerifyCodeTypes string

const (
	VerifyCodeTypesEmail VerifyCodeTypes = "email"
	VerifyCodeTypesSms   VerifyCodeTypes = "sms"
)

func (e *VerifyCodeTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerifyCodeTypes(s)
	case string:
		*e = VerifyCodeTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for VerifyCodeTypes: %T", src)
	}
	return nil
}

type NullVerifyCodeTypes struct {
	VerifyCodeTypes VerifyCodeTypes `json:"verify_code_types"`
	Valid           bool            `json:"valid"` // Valid is true if VerifyCodeTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerifyCodeTypes) Scan(value interface{}) error {
	if value == nil {
		ns.VerifyCodeTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerifyCodeTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerifyCodeTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerifyCodeTypes), nil
}

func (e VerifyCodeTypes) Valid() bool {
	switch e {
	case VerifyCodeTypesEmail,
		VerifyCodeTypesSms:
		return true
	}
	return false
}

func AllVerifyCodeTypesValues() []VerifyCodeTypes {
	return []VerifyCodeTypes{
		VerifyCodeTypesEmail,
		VerifyCodeTypesSms,
	}
}

type AlembicVersion struct {
	VersionNum string `json:"version_num"`
}

type AnnualBilling struct {
	ID                   uuid.UUID    `json:"id"`
	ServiceID            uuid.UUID    `json:"service_id"`
	FinancialYearStart   int32        `json:"financial_year_start"`
	FreeSmsFragmentLimit int32        `json:"free_sms_fragment_limit"`
	UpdatedAt            sql.NullTime `json:"updated_at"`
	CreatedAt            time.Time    `json:"created_at"`
}

type AnnualLimitsDatum struct {
	ServiceID         uuid.UUID `json:"service_id"`
	TimePeriod        string    `json:"time_period"`
	AnnualEmailLimit  int64     `json:"annual_email_limit"`
	AnnualSmsLimit    int64     `json:"annual_sms_limit"`
	NotificationType  string    `json:"notification_type"`
	NotificationCount int64     `json:"notification_count"`
}

type ApiKey struct {
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	Secret             string          `json:"secret"`
	ServiceID          uuid.UUID       `json:"service_id"`
	ExpiryDate         sql.NullTime    `json:"expiry_date"`
	CreatedAt          time.Time       `json:"created_at"`
	CreatedByID        uuid.UUID       `json:"created_by_id"`
	UpdatedAt          sql.NullTime    `json:"updated_at"`
	Version            int32           `json:"version"`
	KeyType            string          `json:"key_type"`
	CompromisedKeyInfo json.RawMessage `json:"compromised_key_info"`
	LastUsedTimestamp  sql.NullTime    `json:"last_used_timestamp"`
}

type ApiKeysHistory struct {
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	Secret             string          `json:"secret"`
	ServiceID          uuid.UUID       `json:"service_id"`
	ExpiryDate         sql.NullTime    `json:"expiry_date"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          sql.NullTime    `json:"updated_at"`
	CreatedByID        uuid.UUID       `json:"created_by_id"`
	Version            int32           `json:"version"`
	KeyType            string          `json:"key_type"`
	CompromisedKeyInfo json.RawMessage `json:"compromised_key_info"`
	LastUsedTimestamp  sql.NullTime    `json:"last_used_timestamp"`
}

type AuthType struct {
	Name string `json:"name"`
}

type BrandingType struct {
	Name string `json:"name"`
}

type Complaint struct {
	ID             uuid.UUID      `json:"id"`
	NotificationID uuid.UUID      `json:"notification_id"`
	ServiceID      uuid.UUID      `json:"service_id"`
	SesFeedbackID  sql.NullString `json:"ses_feedback_id"`
	ComplaintType  sql.NullString `json:"complaint_type"`
	ComplaintDate  sql.NullTime   `json:"complaint_date"`
	CreatedAt      time.Time      `json:"created_at"`
}

type DailySortedLetter struct {
	ID            uuid.UUID      `json:"id"`
	BillingDay    time.Time      `json:"billing_day"`
	UnsortedCount int32          `json:"unsorted_count"`
	SortedCount   int32          `json:"sorted_count"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	FileName      sql.NullString `json:"file_name"`
}

type DmDatetime struct {
	BstDate          time.Time `json:"bst_date"`
	Year             int32     `json:"year"`
	Month            int32     `json:"month"`
	MonthName        string    `json:"month_name"`
	Day              int32     `json:"day"`
	BstDay           int32     `json:"bst_day"`
	DayOfYear        int32     `json:"day_of_year"`
	WeekDayName      string    `json:"week_day_name"`
	CalendarWeek     int32     `json:"calendar_week"`
	Quartal          string    `json:"quartal"`
	YearQuartal      string    `json:"year_quartal"`
	YearMonth        string    `json:"year_month"`
	YearCalendarWeek string    `json:"year_calendar_week"`
	FinancialYear    int32     `json:"financial_year"`
	UtcDaytimeStart  time.Time `json:"utc_daytime_start"`
	UtcDaytimeEnd    time.Time `json:"utc_daytime_end"`
}

type Domain struct {
	Domain         string    `json:"domain"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

type EmailBranding struct {
	ID             uuid.UUID      `json:"id"`
	Colour         sql.NullString `json:"colour"`
	Logo           sql.NullString `json:"logo"`
	Name           string         `json:"name"`
	Text           sql.NullString `json:"text"`
	BrandType      string         `json:"brand_type"`
	OrganisationID uuid.NullUUID  `json:"organisation_id"`
	AltTextEn      sql.NullString `json:"alt_text_en"`
	AltTextFr      sql.NullString `json:"alt_text_fr"`
	CreatedByID    uuid.UUID      `json:"created_by_id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedByID    uuid.NullUUID  `json:"updated_by_id"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type Event struct {
	ID        uuid.UUID       `json:"id"`
	EventType string          `json:"event_type"`
	CreatedAt time.Time       `json:"created_at"`
	Data      json.RawMessage `json:"data"`
}

type Fido2Key struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Name      string       `json:"name"`
	Key       string       `json:"key"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Fido2Session struct {
	UserID    uuid.UUID `json:"user_id"`
	Session   string    `json:"session"`
	CreatedAt time.Time `json:"created_at"`
}

type FtBilling struct {
	BstDate           time.Time         `json:"bst_date"`
	TemplateID        uuid.UUID         `json:"template_id"`
	ServiceID         uuid.UUID         `json:"service_id"`
	NotificationType  string            `json:"notification_type"`
	Provider          string            `json:"provider"`
	RateMultiplier    int32             `json:"rate_multiplier"`
	International     bool              `json:"international"`
	Rate              string            `json:"rate"`
	BillableUnits     sql.NullInt32     `json:"billable_units"`
	NotificationsSent sql.NullInt32     `json:"notifications_sent"`
	UpdatedAt         sql.NullTime      `json:"updated_at"`
	CreatedAt         time.Time         `json:"created_at"`
	Postage           string            `json:"postage"`
	SmsSendingVehicle SmsSendingVehicle `json:"sms_sending_vehicle"`
	BillingTotal      sql.NullString    `json:"billing_total"`
}

type FtNotificationStatus struct {
	BstDate            time.Time    `json:"bst_date"`
	TemplateID         uuid.UUID    `json:"template_id"`
	ServiceID          uuid.UUID    `json:"service_id"`
	JobID              uuid.UUID    `json:"job_id"`
	NotificationType   string       `json:"notification_type"`
	KeyType            string       `json:"key_type"`
	NotificationStatus string       `json:"notification_status"`
	NotificationCount  int32        `json:"notification_count"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          sql.NullTime `json:"updated_at"`
	BillableUnits      int32        `json:"billable_units"`
}

type InboundNumber struct {
	ID        uuid.UUID     `json:"id"`
	Number    string        `json:"number"`
	Provider  string        `json:"provider"`
	ServiceID uuid.NullUUID `json:"service_id"`
	Active    bool          `json:"active"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type InboundSm struct {
	ID                uuid.UUID      `json:"id"`
	ServiceID         uuid.UUID      `json:"service_id"`
	Content           string         `json:"content"`
	NotifyNumber      string         `json:"notify_number"`
	UserNumber        string         `json:"user_number"`
	CreatedAt         time.Time      `json:"created_at"`
	ProviderDate      sql.NullTime   `json:"provider_date"`
	ProviderReference sql.NullString `json:"provider_reference"`
	Provider          string         `json:"provider"`
}

type InviteStatusType struct {
	Name string `json:"name"`
}

type InvitedOrganisationUser struct {
	ID             uuid.UUID `json:"id"`
	EmailAddress   string    `json:"email_address"`
	InvitedByID    uuid.UUID `json:"invited_by_id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	CreatedAt      time.Time `json:"created_at"`
	Status         string    `json:"status"`
}

type InvitedUser struct {
	ID                uuid.UUID               `json:"id"`
	EmailAddress      string                  `json:"email_address"`
	UserID            uuid.UUID               `json:"user_id"`
	ServiceID         uuid.NullUUID           `json:"service_id"`
	CreatedAt         time.Time               `json:"created_at"`
	Status            InvitedUsersStatusTypes `json:"status"`
	Permissions       string                  `json:"permissions"`
	AuthType          string                  `json:"auth_type"`
	FolderPermissions json.RawMessage         `json:"folder_permissions"`
}

type Job struct {
	ID                     uuid.UUID     `json:"id"`
	OriginalFileName       string        `json:"original_file_name"`
	ServiceID              uuid.UUID     `json:"service_id"`
	TemplateID             uuid.NullUUID `json:"template_id"`
	CreatedAt              time.Time     `json:"created_at"`
	UpdatedAt              sql.NullTime  `json:"updated_at"`
	NotificationCount      int32         `json:"notification_count"`
	NotificationsSent      int32         `json:"notifications_sent"`
	ProcessingStarted      sql.NullTime  `json:"processing_started"`
	ProcessingFinished     sql.NullTime  `json:"processing_finished"`
	CreatedByID            uuid.NullUUID `json:"created_by_id"`
	TemplateVersion        int32         `json:"template_version"`
	NotificationsDelivered int32         `json:"notifications_delivered"`
	NotificationsFailed    int32         `json:"notifications_failed"`
	JobStatus              string        `json:"job_status"`
	ScheduledFor           sql.NullTime  `json:"scheduled_for"`
	Archived               bool          `json:"archived"`
	ApiKeyID               uuid.NullUUID `json:"api_key_id"`
	SenderID               uuid.NullUUID `json:"sender_id"`
}

type JobStatus struct {
	Name string `json:"name"`
}

type KeyType struct {
	Name string `json:"name"`
}

type LetterBranding struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Filename string    `json:"filename"`
}

type LetterRate struct {
	ID         uuid.UUID    `json:"id"`
	StartDate  time.Time    `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
	SheetCount int32        `json:"sheet_count"`
	Rate       string       `json:"rate"`
	Crown      bool         `json:"crown"`
	PostClass  string       `json:"post_class"`
}

type LoginEvent struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	Data      json.RawMessage `json:"data"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}

type MonthlyNotificationStatsSummary struct {
	Month             string    `json:"month"`
	ServiceID         uuid.UUID `json:"service_id"`
	NotificationType  string    `json:"notification_type"`
	NotificationCount int32     `json:"notification_count"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Notification struct {
	ID                        uuid.UUID                        `json:"id"`
	To                        string                           `json:"to"`
	JobID                     uuid.NullUUID                    `json:"job_id"`
	ServiceID                 uuid.NullUUID                    `json:"service_id"`
	TemplateID                uuid.NullUUID                    `json:"template_id"`
	CreatedAt                 time.Time                        `json:"created_at"`
	SentAt                    sql.NullTime                     `json:"sent_at"`
	SentBy                    sql.NullString                   `json:"sent_by"`
	UpdatedAt                 sql.NullTime                     `json:"updated_at"`
	Reference                 sql.NullString                   `json:"reference"`
	TemplateVersion           int32                            `json:"template_version"`
	JobRowNumber              sql.NullInt32                    `json:"job_row_number"`
	Personalisation           sql.NullString                   `json:"_personalisation"`
	ApiKeyID                  uuid.NullUUID                    `json:"api_key_id"`
	KeyType                   string                           `json:"key_type"`
	NotificationType          NotificationType                 `json:"notification_type"`
	BillableUnits             int32                            `json:"billable_units"`
	ClientReference           sql.NullString                   `json:"client_reference"`
	International             sql.NullBool                     `json:"international"`
	PhonePrefix               sql.NullString                   `json:"phone_prefix"`
	RateMultiplier            sql.NullString                   `json:"rate_multiplier"`
	NotificationStatus        sql.NullString                   `json:"notification_status"`
	NormalisedTo              sql.NullString                   `json:"normalised_to"`
	CreatedByID               uuid.NullUUID                    `json:"created_by_id"`
	ReplyToText               sql.NullString                   `json:"reply_to_text"`
	Postage                   sql.NullString                   `json:"postage"`
	ProviderResponse          sql.NullString                   `json:"provider_response"`
	QueueName                 sql.NullString                   `json:"queue_name"`
	FeedbackType              NullNotificationFeedbackTypes    `json:"feedback_type"`
	FeedbackSubtype           NullNotificationFeedbackSubtypes `json:"feedback_subtype"`
	SesFeedbackID             sql.NullString                   `json:"ses_feedback_id"`
	SesFeedbackDate           sql.NullTime                     `json:"ses_feedback_date"`
	SmsTotalMessagePrice      sql.NullFloat64                  `json:"sms_total_message_price"`
	SmsTotalCarrierFee        sql.NullFloat64                  `json:"sms_total_carrier_fee"`
	SmsIsoCountryCode         sql.NullString                   `json:"sms_iso_country_code"`
	SmsCarrierName            sql.NullString                   `json:"sms_carrier_name"`
	SmsMessageEncoding        sql.NullString                   `json:"sms_message_encoding"`
	SmsOriginationPhoneNumber sql.NullString                   `json:"sms_origination_phone_number"`
	FeedbackReason            sql.NullString                   `json:"feedback_reason"`
}

type NotificationHistory struct {
	ID                        uuid.UUID                        `json:"id"`
	JobID                     uuid.NullUUID                    `json:"job_id"`
	JobRowNumber              sql.NullInt32                    `json:"job_row_number"`
	ServiceID                 uuid.NullUUID                    `json:"service_id"`
	TemplateID                uuid.NullUUID                    `json:"template_id"`
	TemplateVersion           int32                            `json:"template_version"`
	ApiKeyID                  uuid.NullUUID                    `json:"api_key_id"`
	KeyType                   string                           `json:"key_type"`
	NotificationType          NotificationType                 `json:"notification_type"`
	CreatedAt                 time.Time                        `json:"created_at"`
	SentAt                    sql.NullTime                     `json:"sent_at"`
	SentBy                    sql.NullString                   `json:"sent_by"`
	UpdatedAt                 sql.NullTime                     `json:"updated_at"`
	Reference                 sql.NullString                   `json:"reference"`
	BillableUnits             int32                            `json:"billable_units"`
	ClientReference           sql.NullString                   `json:"client_reference"`
	International             sql.NullBool                     `json:"international"`
	PhonePrefix               sql.NullString                   `json:"phone_prefix"`
	RateMultiplier            sql.NullString                   `json:"rate_multiplier"`
	NotificationStatus        sql.NullString                   `json:"notification_status"`
	CreatedByID               uuid.NullUUID                    `json:"created_by_id"`
	Postage                   sql.NullString                   `json:"postage"`
	QueueName                 sql.NullString                   `json:"queue_name"`
	FeedbackType              NullNotificationFeedbackTypes    `json:"feedback_type"`
	FeedbackSubtype           NullNotificationFeedbackSubtypes `json:"feedback_subtype"`
	SesFeedbackID             sql.NullString                   `json:"ses_feedback_id"`
	SesFeedbackDate           sql.NullTime                     `json:"ses_feedback_date"`
	SmsTotalMessagePrice      sql.NullFloat64                  `json:"sms_total_message_price"`
	SmsTotalCarrierFee        sql.NullFloat64                  `json:"sms_total_carrier_fee"`
	SmsIsoCountryCode         sql.NullString                   `json:"sms_iso_country_code"`
	SmsCarrierName            sql.NullString                   `json:"sms_carrier_name"`
	SmsMessageEncoding        sql.NullString                   `json:"sms_message_encoding"`
	SmsOriginationPhoneNumber sql.NullString                   `json:"sms_origination_phone_number"`
	FeedbackReason            sql.NullString                   `json:"feedback_reason"`
}

type NotificationStatusType struct {
	Name string `json:"name"`
}

type Organisation struct {
	ID                                    uuid.UUID       `json:"id"`
	Name                                  string          `json:"name"`
	Active                                bool            `json:"active"`
	CreatedAt                             time.Time       `json:"created_at"`
	UpdatedAt                             sql.NullTime    `json:"updated_at"`
	EmailBrandingID                       uuid.NullUUID   `json:"email_branding_id"`
	LetterBrandingID                      uuid.NullUUID   `json:"letter_branding_id"`
	AgreementSigned                       sql.NullBool    `json:"agreement_signed"`
	AgreementSignedAt                     sql.NullTime    `json:"agreement_signed_at"`
	AgreementSignedByID                   uuid.NullUUID   `json:"agreement_signed_by_id"`
	AgreementSignedVersion                sql.NullFloat64 `json:"agreement_signed_version"`
	Crown                                 sql.NullBool    `json:"crown"`
	OrganisationType                      sql.NullString  `json:"organisation_type"`
	RequestToGoLiveNotes                  sql.NullString  `json:"request_to_go_live_notes"`
	AgreementSignedOnBehalfOfEmailAddress sql.NullString  `json:"agreement_signed_on_behalf_of_email_address"`
	AgreementSignedOnBehalfOfName         sql.NullString  `json:"agreement_signed_on_behalf_of_name"`
	DefaultBrandingIsFrench               sql.NullBool    `json:"default_branding_is_french"`
}

type OrganisationType struct {
	Name                       string       `json:"name"`
	IsCrown                    sql.NullBool `json:"is_crown"`
	AnnualFreeSmsFragmentLimit int64        `json:"annual_free_sms_fragment_limit"`
}

type Permission struct {
	ID         uuid.UUID       `json:"id"`
	ServiceID  uuid.NullUUID   `json:"service_id"`
	UserID     uuid.UUID       `json:"user_id"`
	Permission PermissionTypes `json:"permission"`
	CreatedAt  time.Time       `json:"created_at"`
}

type ProviderDetail struct {
	ID                    uuid.UUID        `json:"id"`
	DisplayName           string           `json:"display_name"`
	Identifier            string           `json:"identifier"`
	Priority              int32            `json:"priority"`
	NotificationType      NotificationType `json:"notification_type"`
	Active                bool             `json:"active"`
	UpdatedAt             sql.NullTime     `json:"updated_at"`
	Version               int32            `json:"version"`
	CreatedByID           uuid.NullUUID    `json:"created_by_id"`
	SupportsInternational bool             `json:"supports_international"`
}

type ProviderDetailsHistory struct {
	ID                    uuid.UUID        `json:"id"`
	DisplayName           string           `json:"display_name"`
	Identifier            string           `json:"identifier"`
	Priority              int32            `json:"priority"`
	NotificationType      NotificationType `json:"notification_type"`
	Active                bool             `json:"active"`
	Version               int32            `json:"version"`
	UpdatedAt             sql.NullTime     `json:"updated_at"`
	CreatedByID           uuid.NullUUID    `json:"created_by_id"`
	SupportsInternational bool             `json:"supports_international"`
}

type ProviderRate struct {
	ID         uuid.UUID `json:"id"`
	ValidFrom  time.Time `json:"valid_from"`
	Rate       string    `json:"rate"`
	ProviderID uuid.UUID `json:"provider_id"`
}

type Rate struct {
	ID                uuid.UUID         `json:"id"`
	ValidFrom         time.Time         `json:"valid_from"`
	Rate              string            `json:"rate"`
	NotificationType  NotificationType  `json:"notification_type"`
	SmsSendingVehicle SmsSendingVehicle `json:"sms_sending_vehicle"`
}

type Report struct {
	ID               uuid.UUID      `json:"id"`
	ReportType       string         `json:"report_type"`
	RequestedAt      time.Time      `json:"requested_at"`
	CompletedAt      sql.NullTime   `json:"completed_at"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	RequestingUserID uuid.NullUUID  `json:"requesting_user_id"`
	ServiceID        uuid.UUID      `json:"service_id"`
	JobID            uuid.NullUUID  `json:"job_id"`
	Url              sql.NullString `json:"url"`
	Status           string         `json:"status"`
	Language         sql.NullString `json:"language"`
}

type ScheduledNotification struct {
	ID             uuid.UUID `json:"id"`
	NotificationID uuid.UUID `json:"notification_id"`
	ScheduledFor   time.Time `json:"scheduled_for"`
	Pending        bool      `json:"pending"`
}

type Service struct {
	ID                      uuid.UUID      `json:"id"`
	Name                    string         `json:"name"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               sql.NullTime   `json:"updated_at"`
	Active                  bool           `json:"active"`
	MessageLimit            int64          `json:"message_limit"`
	Restricted              bool           `json:"restricted"`
	EmailFrom               string         `json:"email_from"`
	CreatedByID             uuid.UUID      `json:"created_by_id"`
	Version                 int32          `json:"version"`
	ResearchMode            bool           `json:"research_mode"`
	OrganisationType        sql.NullString `json:"organisation_type"`
	PrefixSms               bool           `json:"prefix_sms"`
	Crown                   sql.NullBool   `json:"crown"`
	RateLimit               int32          `json:"rate_limit"`
	ContactLink             sql.NullString `json:"contact_link"`
	ConsentToResearch       sql.NullBool   `json:"consent_to_research"`
	VolumeEmail             sql.NullInt32  `json:"volume_email"`
	VolumeLetter            sql.NullInt32  `json:"volume_letter"`
	VolumeSms               sql.NullInt32  `json:"volume_sms"`
	CountAsLive             bool           `json:"count_as_live"`
	GoLiveAt                sql.NullTime   `json:"go_live_at"`
	GoLiveUserID            uuid.NullUUID  `json:"go_live_user_id"`
	OrganisationID          uuid.NullUUID  `json:"organisation_id"`
	SendingDomain           sql.NullString `json:"sending_domain"`
	DefaultBrandingIsFrench sql.NullBool   `json:"default_branding_is_french"`
	SmsDailyLimit           int64          `json:"sms_daily_limit"`
	OrganisationNotes       sql.NullString `json:"organisation_notes"`
	SensitiveService        sql.NullBool   `json:"sensitive_service"`
	EmailAnnualLimit        int64          `json:"email_annual_limit"`
	SmsAnnualLimit          int64          `json:"sms_annual_limit"`
	SuspendedByID           uuid.NullUUID  `json:"suspended_by_id"`
	SuspendedAt             sql.NullTime   `json:"suspended_at"`
}

type ServiceCallbackApi struct {
	ID           uuid.UUID      `json:"id"`
	ServiceID    uuid.UUID      `json:"service_id"`
	Url          string         `json:"url"`
	BearerToken  string         `json:"bearer_token"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	UpdatedByID  uuid.UUID      `json:"updated_by_id"`
	Version      int32          `json:"version"`
	CallbackType sql.NullString `json:"callback_type"`
	IsSuspended  sql.NullBool   `json:"is_suspended"`
	SuspendedAt  sql.NullTime   `json:"suspended_at"`
}

type ServiceCallbackApiHistory struct {
	ID           uuid.UUID      `json:"id"`
	ServiceID    uuid.UUID      `json:"service_id"`
	Url          string         `json:"url"`
	BearerToken  string         `json:"bearer_token"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	UpdatedByID  uuid.UUID      `json:"updated_by_id"`
	Version      int32          `json:"version"`
	CallbackType sql.NullString `json:"callback_type"`
	IsSuspended  sql.NullBool   `json:"is_suspended"`
	SuspendedAt  sql.NullTime   `json:"suspended_at"`
}

type ServiceCallbackType struct {
	Name string `json:"name"`
}

type ServiceDataRetention struct {
	ID               uuid.UUID        `json:"id"`
	ServiceID        uuid.UUID        `json:"service_id"`
	NotificationType NotificationType `json:"notification_type"`
	DaysOfRetention  int32            `json:"days_of_retention"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        sql.NullTime     `json:"updated_at"`
}

type ServiceEmailBranding struct {
	ServiceID       uuid.UUID `json:"service_id"`
	EmailBrandingID uuid.UUID `json:"email_branding_id"`
}

type ServiceEmailReplyTo struct {
	ID           uuid.UUID    `json:"id"`
	ServiceID    uuid.UUID    `json:"service_id"`
	EmailAddress string       `json:"email_address"`
	IsDefault    bool         `json:"is_default"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	Archived     bool         `json:"archived"`
}

type ServiceInboundApi struct {
	ID          uuid.UUID    `json:"id"`
	ServiceID   uuid.UUID    `json:"service_id"`
	Url         string       `json:"url"`
	BearerToken string       `json:"bearer_token"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	UpdatedByID uuid.UUID    `json:"updated_by_id"`
	Version     int32        `json:"version"`
}

type ServiceInboundApiHistory struct {
	ID          uuid.UUID    `json:"id"`
	ServiceID   uuid.UUID    `json:"service_id"`
	Url         string       `json:"url"`
	BearerToken string       `json:"bearer_token"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	UpdatedByID uuid.UUID    `json:"updated_by_id"`
	Version     int32        `json:"version"`
}

type ServiceLetterBranding struct {
	ServiceID        uuid.UUID `json:"service_id"`
	LetterBrandingID uuid.UUID `json:"letter_branding_id"`
}

type ServiceLetterContact struct {
	ID           uuid.UUID    `json:"id"`
	ServiceID    uuid.UUID    `json:"service_id"`
	ContactBlock string       `json:"contact_block"`
	IsDefault    bool         `json:"is_default"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	Archived     bool         `json:"archived"`
}

type ServicePermission struct {
	ServiceID  uuid.UUID `json:"service_id"`
	Permission string    `json:"permission"`
	CreatedAt  time.Time `json:"created_at"`
}

type ServicePermissionType struct {
	Name string `json:"name"`
}

type ServiceSafelist struct {
	ID            uuid.UUID     `json:"id"`
	ServiceID     uuid.UUID     `json:"service_id"`
	RecipientType RecipientType `json:"recipient_type"`
	Recipient     string        `json:"recipient"`
	CreatedAt     sql.NullTime  `json:"created_at"`
}

type ServiceSmsSender struct {
	ID              uuid.UUID     `json:"id"`
	SmsSender       string        `json:"sms_sender"`
	ServiceID       uuid.UUID     `json:"service_id"`
	IsDefault       bool          `json:"is_default"`
	InboundNumberID uuid.NullUUID `json:"inbound_number_id"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       sql.NullTime  `json:"updated_at"`
	Archived        bool          `json:"archived"`
}

type ServicesHistory struct {
	ID                      uuid.UUID      `json:"id"`
	Name                    string         `json:"name"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               sql.NullTime   `json:"updated_at"`
	Active                  bool           `json:"active"`
	MessageLimit            int64          `json:"message_limit"`
	Restricted              bool           `json:"restricted"`
	EmailFrom               string         `json:"email_from"`
	CreatedByID             uuid.UUID      `json:"created_by_id"`
	Version                 int32          `json:"version"`
	ResearchMode            bool           `json:"research_mode"`
	OrganisationType        sql.NullString `json:"organisation_type"`
	PrefixSms               sql.NullBool   `json:"prefix_sms"`
	Crown                   sql.NullBool   `json:"crown"`
	RateLimit               int32          `json:"rate_limit"`
	ContactLink             sql.NullString `json:"contact_link"`
	ConsentToResearch       sql.NullBool   `json:"consent_to_research"`
	VolumeEmail             sql.NullInt32  `json:"volume_email"`
	VolumeLetter            sql.NullInt32  `json:"volume_letter"`
	VolumeSms               sql.NullInt32  `json:"volume_sms"`
	CountAsLive             bool           `json:"count_as_live"`
	GoLiveAt                sql.NullTime   `json:"go_live_at"`
	GoLiveUserID            uuid.NullUUID  `json:"go_live_user_id"`
	OrganisationID          uuid.NullUUID  `json:"organisation_id"`
	SendingDomain           sql.NullString `json:"sending_domain"`
	DefaultBrandingIsFrench sql.NullBool   `json:"default_branding_is_french"`
	SmsDailyLimit           int64          `json:"sms_daily_limit"`
	OrganisationNotes       sql.NullString `json:"organisation_notes"`
	SensitiveService        sql.NullBool   `json:"sensitive_service"`
	EmailAnnualLimit        int64          `json:"email_annual_limit"`
	SmsAnnualLimit          int64          `json:"sms_annual_limit"`
	SuspendedByID           uuid.NullUUID  `json:"suspended_by_id"`
	SuspendedAt             sql.NullTime   `json:"suspended_at"`
}

type Template struct {
	ID                     uuid.UUID      `json:"id"`
	Name                   string         `json:"name"`
	TemplateType           TemplateType   `json:"template_type"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
	Content                string         `json:"content"`
	ServiceID              uuid.UUID      `json:"service_id"`
	Subject                sql.NullString `json:"subject"`
	CreatedByID            uuid.UUID      `json:"created_by_id"`
	Version                int32          `json:"version"`
	Archived               bool           `json:"archived"`
	ProcessType            sql.NullString `json:"process_type"`
	ServiceLetterContactID uuid.NullUUID  `json:"service_letter_contact_id"`
	Hidden                 bool           `json:"hidden"`
	Postage                sql.NullString `json:"postage"`
	TemplateCategoryID     uuid.NullUUID  `json:"template_category_id"`
	TextDirectionRtl       bool           `json:"text_direction_rtl"`
}

type TemplateCategory struct {
	ID                uuid.UUID         `json:"id"`
	NameEn            string            `json:"name_en"`
	NameFr            string            `json:"name_fr"`
	DescriptionEn     sql.NullString    `json:"description_en"`
	DescriptionFr     sql.NullString    `json:"description_fr"`
	SmsProcessType    string            `json:"sms_process_type"`
	EmailProcessType  string            `json:"email_process_type"`
	Hidden            bool              `json:"hidden"`
	CreatedAt         time.Time         `json:"created_at"`
	UpdatedAt         sql.NullTime      `json:"updated_at"`
	SmsSendingVehicle SmsSendingVehicle `json:"sms_sending_vehicle"`
	CreatedByID       uuid.UUID         `json:"created_by_id"`
	UpdatedByID       uuid.NullUUID     `json:"updated_by_id"`
}

type TemplateFolder struct {
	ID        uuid.UUID     `json:"id"`
	ServiceID uuid.UUID     `json:"service_id"`
	Name      string        `json:"name"`
	ParentID  uuid.NullUUID `json:"parent_id"`
}

type TemplateFolderMap struct {
	TemplateID       uuid.UUID `json:"template_id"`
	TemplateFolderID uuid.UUID `json:"template_folder_id"`
}

type TemplateProcessType struct {
	Name string `json:"name"`
}

type TemplateRedacted struct {
	TemplateID            uuid.UUID `json:"template_id"`
	RedactPersonalisation bool      `json:"redact_personalisation"`
	UpdatedAt             time.Time `json:"updated_at"`
	UpdatedByID           uuid.UUID `json:"updated_by_id"`
}

type TemplatesHistory struct {
	ID                     uuid.UUID      `json:"id"`
	Name                   string         `json:"name"`
	TemplateType           TemplateType   `json:"template_type"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
	Content                string         `json:"content"`
	ServiceID              uuid.UUID      `json:"service_id"`
	Subject                sql.NullString `json:"subject"`
	CreatedByID            uuid.UUID      `json:"created_by_id"`
	Version                int32          `json:"version"`
	Archived               bool           `json:"archived"`
	ProcessType            sql.NullString `json:"process_type"`
	ServiceLetterContactID uuid.NullUUID  `json:"service_letter_contact_id"`
	Hidden                 bool           `json:"hidden"`
	Postage                sql.NullString `json:"postage"`
	TemplateCategoryID     uuid.NullUUID  `json:"template_category_id"`
	TextDirectionRtl       bool           `json:"text_direction_rtl"`
}

type User struct {
	ID                    uuid.UUID       `json:"id"`
	Name                  string          `json:"name"`
	EmailAddress          string          `json:"email_address"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             sql.NullTime    `json:"updated_at"`
	Password              string          `json:"_password"`
	MobileNumber          sql.NullString  `json:"mobile_number"`
	PasswordChangedAt     time.Time       `json:"password_changed_at"`
	LoggedInAt            sql.NullTime    `json:"logged_in_at"`
	FailedLoginCount      int32           `json:"failed_login_count"`
	State                 string          `json:"state"`
	PlatformAdmin         bool            `json:"platform_admin"`
	CurrentSessionID      uuid.NullUUID   `json:"current_session_id"`
	AuthType              string          `json:"auth_type"`
	Blocked               bool            `json:"blocked"`
	AdditionalInformation json.RawMessage `json:"additional_information"`
	PasswordExpired       bool            `json:"password_expired"`
	VerifiedPhonenumber   sql.NullBool    `json:"verified_phonenumber"`
	DefaultEditorIsRte    bool            `json:"default_editor_is_rte"`
}

type UserFolderPermission struct {
	UserID           uuid.UUID `json:"user_id"`
	TemplateFolderID uuid.UUID `json:"template_folder_id"`
	ServiceID        uuid.UUID `json:"service_id"`
}

type UserToOrganisation struct {
	UserID         uuid.NullUUID `json:"user_id"`
	OrganisationID uuid.NullUUID `json:"organisation_id"`
}

type UserToService struct {
	UserID    uuid.NullUUID `json:"user_id"`
	ServiceID uuid.NullUUID `json:"service_id"`
}

type VerifyCode struct {
	ID             uuid.UUID       `json:"id"`
	UserID         uuid.UUID       `json:"user_id"`
	Code           string          `json:"_code"`
	CodeType       VerifyCodeTypes `json:"code_type"`
	ExpiryDatetime time.Time       `json:"expiry_datetime"`
	CodeUsed       sql.NullBool    `json:"code_used"`
	CreatedAt      time.Time       `json:"created_at"`
}
