// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package billing

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getAnnualLimitsData = `-- name: GetAnnualLimitsData :many
SELECT service_id, time_period, annual_email_limit, annual_sms_limit, notification_type, notification_count
FROM annual_limits_data
WHERE service_id = $1
ORDER BY time_period,
    notification_type
`

func (q *Queries) GetAnnualLimitsData(ctx context.Context, serviceID uuid.UUID) ([]AnnualLimitsDatum, error) {
	rows, err := q.db.QueryContext(ctx, getAnnualLimitsData, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnnualLimitsDatum
	for rows.Next() {
		var i AnnualLimitsDatum
		if err := rows.Scan(
			&i.ServiceID,
			&i.TimePeriod,
			&i.AnnualEmailLimit,
			&i.AnnualSmsLimit,
			&i.NotificationType,
			&i.NotificationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveredNotificationsByMonth = `-- name: GetDeliveredNotificationsByMonth :many
SELECT month,
    service_id,
    notification_type,
    notification_count
FROM monthly_notification_stats_summary
WHERE service_id = $1
ORDER BY month DESC,
    notification_type ASC
`

type GetDeliveredNotificationsByMonthRow struct {
	Month             string    `json:"month"`
	ServiceID         uuid.UUID `json:"service_id"`
	NotificationType  string    `json:"notification_type"`
	NotificationCount int32     `json:"notification_count"`
}

func (q *Queries) GetDeliveredNotificationsByMonth(ctx context.Context, serviceID uuid.UUID) ([]GetDeliveredNotificationsByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeliveredNotificationsByMonth, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeliveredNotificationsByMonthRow
	for rows.Next() {
		var i GetDeliveredNotificationsByMonthRow
		if err := rows.Scan(
			&i.Month,
			&i.ServiceID,
			&i.NotificationType,
			&i.NotificationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFactNotificationStatusForDay = `-- name: GetFactNotificationStatusForDay :many
SELECT bst_date, template_id, service_id, job_id, notification_type, key_type, notification_status, notification_count, created_at, updated_at, billable_units
FROM ft_notification_status
WHERE bst_date = $1
    AND service_id = $2
ORDER BY template_id,
    job_id,
    notification_status
`

type GetFactNotificationStatusForDayParams struct {
	BstDate   time.Time `json:"bst_date"`
	ServiceID uuid.UUID `json:"service_id"`
}

func (q *Queries) GetFactNotificationStatusForDay(ctx context.Context, arg GetFactNotificationStatusForDayParams) ([]FtNotificationStatus, error) {
	rows, err := q.db.QueryContext(ctx, getFactNotificationStatusForDay, arg.BstDate, arg.ServiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FtNotificationStatus
	for rows.Next() {
		var i FtNotificationStatus
		if err := rows.Scan(
			&i.BstDate,
			&i.TemplateID,
			&i.ServiceID,
			&i.JobID,
			&i.NotificationType,
			&i.KeyType,
			&i.NotificationStatus,
			&i.NotificationCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BillableUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFreeSMSFragmentLimit = `-- name: GetFreeSMSFragmentLimit :one
SELECT id, service_id, financial_year_start, free_sms_fragment_limit, updated_at, created_at
FROM annual_billing
WHERE service_id = $1
    AND financial_year_start = $2
LIMIT 1
`

type GetFreeSMSFragmentLimitParams struct {
	ServiceID          uuid.UUID `json:"service_id"`
	FinancialYearStart int32     `json:"financial_year_start"`
}

func (q *Queries) GetFreeSMSFragmentLimit(ctx context.Context, arg GetFreeSMSFragmentLimitParams) (AnnualBilling, error) {
	row := q.db.QueryRowContext(ctx, getFreeSMSFragmentLimit, arg.ServiceID, arg.FinancialYearStart)
	var i AnnualBilling
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.FinancialYearStart,
		&i.FreeSmsFragmentLimit,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMonthlyBillingUsage = `-- name: GetMonthlyBillingUsage :many
SELECT date_trunc('month', bst_date)::date AS month,
    sum(coalesce(billing_total, 0)) AS billing_total,
    sum(coalesce(notifications_sent, 0))::bigint AS notifications_sent
FROM ft_billing
WHERE service_id = $1
    AND extract(
        year
        FROM bst_date
    ) = $2
GROUP BY 1
ORDER BY 1
`

type GetMonthlyBillingUsageParams struct {
	ServiceID uuid.UUID `json:"service_id"`
	Year      time.Time `json:"year"`
}

type GetMonthlyBillingUsageRow struct {
	Month             time.Time `json:"month"`
	BillingTotal      int64     `json:"billing_total"`
	NotificationsSent int64     `json:"notifications_sent"`
}

func (q *Queries) GetMonthlyBillingUsage(ctx context.Context, arg GetMonthlyBillingUsageParams) ([]GetMonthlyBillingUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyBillingUsage, arg.ServiceID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyBillingUsageRow
	for rows.Next() {
		var i GetMonthlyBillingUsageRow
		if err := rows.Scan(&i.Month, &i.BillingTotal, &i.NotificationsSent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlatformStatsByDateRange = `-- name: GetPlatformStatsByDateRange :many
SELECT bst_date,
    sum(coalesce(billing_total, 0)) AS billing_total,
    sum(coalesce(notifications_sent, 0))::bigint AS notifications_sent
FROM ft_billing
WHERE bst_date >= $1
    AND bst_date <= $2
GROUP BY bst_date
ORDER BY bst_date
`

type GetPlatformStatsByDateRangeParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type GetPlatformStatsByDateRangeRow struct {
	BstDate           time.Time `json:"bst_date"`
	BillingTotal      int64     `json:"billing_total"`
	NotificationsSent int64     `json:"notifications_sent"`
}

func (q *Queries) GetPlatformStatsByDateRange(ctx context.Context, arg GetPlatformStatsByDateRangeParams) ([]GetPlatformStatsByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlatformStatsByDateRange, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlatformStatsByDateRangeRow
	for rows.Next() {
		var i GetPlatformStatsByDateRangeRow
		if err := rows.Scan(&i.BstDate, &i.BillingTotal, &i.NotificationsSent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageForAllServices = `-- name: GetUsageForAllServices :many
SELECT s.id AS service_id,
    s.name,
    sum(coalesce(f.notifications_sent, 0))::bigint AS notifications_sent
FROM services AS s
    LEFT JOIN ft_billing AS f ON f.service_id = s.id
GROUP BY s.id,
    s.name
ORDER BY notifications_sent DESC,
    s.name ASC
`

type GetUsageForAllServicesRow struct {
	ServiceID         uuid.UUID `json:"service_id"`
	Name              string    `json:"name"`
	NotificationsSent int64     `json:"notifications_sent"`
}

func (q *Queries) GetUsageForAllServices(ctx context.Context) ([]GetUsageForAllServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsageForAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsageForAllServicesRow
	for rows.Next() {
		var i GetUsageForAllServicesRow
		if err := rows.Scan(&i.ServiceID, &i.Name, &i.NotificationsSent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageForTrialServices = `-- name: GetUsageForTrialServices :many
SELECT s.id AS service_id,
    s.name,
    sum(coalesce(f.notifications_sent, 0))::bigint AS notifications_sent
FROM services AS s
    LEFT JOIN ft_billing AS f ON f.service_id = s.id
WHERE s.restricted = true
GROUP BY s.id,
    s.name
ORDER BY notifications_sent DESC,
    s.name ASC
`

type GetUsageForTrialServicesRow struct {
	ServiceID         uuid.UUID `json:"service_id"`
	Name              string    `json:"name"`
	NotificationsSent int64     `json:"notifications_sent"`
}

func (q *Queries) GetUsageForTrialServices(ctx context.Context) ([]GetUsageForTrialServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsageForTrialServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsageForTrialServicesRow
	for rows.Next() {
		var i GetUsageForTrialServicesRow
		if err := rows.Scan(&i.ServiceID, &i.Name, &i.NotificationsSent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYearlyBillingUsage = `-- name: GetYearlyBillingUsage :many
SELECT id, service_id, financial_year_start, free_sms_fragment_limit, updated_at, created_at
FROM annual_billing
WHERE service_id = $1
ORDER BY financial_year_start DESC
`

func (q *Queries) GetYearlyBillingUsage(ctx context.Context, serviceID uuid.UUID) ([]AnnualBilling, error) {
	rows, err := q.db.QueryContext(ctx, getYearlyBillingUsage, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnnualBilling
	for rows.Next() {
		var i AnnualBilling
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.FinancialYearStart,
			&i.FreeSmsFragmentLimit,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFactBillingForDay = `-- name: UpsertFactBillingForDay :one
INSERT INTO ft_billing (
        bst_date,
        template_id,
        service_id,
        notification_type,
        provider,
        rate_multiplier,
        international,
        rate,
        billable_units,
        notifications_sent,
        updated_at,
        created_at,
        postage,
        sms_sending_vehicle,
        billing_total
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15
    ) ON CONFLICT (
        bst_date,
        template_id,
        service_id,
        notification_type,
        provider,
        rate_multiplier,
        international,
        rate,
        postage,
        sms_sending_vehicle
    ) DO
UPDATE
SET billable_units = EXCLUDED.billable_units,
    notifications_sent = EXCLUDED.notifications_sent,
    billing_total = EXCLUDED.billing_total,
    updated_at = EXCLUDED.updated_at
RETURNING bst_date, template_id, service_id, notification_type, provider, rate_multiplier, international, rate, billable_units, notifications_sent, updated_at, created_at, postage, sms_sending_vehicle, billing_total
`

type UpsertFactBillingForDayParams struct {
	BstDate           time.Time         `json:"bst_date"`
	TemplateID        uuid.UUID         `json:"template_id"`
	ServiceID         uuid.UUID         `json:"service_id"`
	NotificationType  string            `json:"notification_type"`
	Provider          string            `json:"provider"`
	RateMultiplier    int32             `json:"rate_multiplier"`
	International     bool              `json:"international"`
	Rate              string            `json:"rate"`
	BillableUnits     sql.NullInt32     `json:"billable_units"`
	NotificationsSent sql.NullInt32     `json:"notifications_sent"`
	UpdatedAt         sql.NullTime      `json:"updated_at"`
	CreatedAt         time.Time         `json:"created_at"`
	Postage           string            `json:"postage"`
	SmsSendingVehicle SmsSendingVehicle `json:"sms_sending_vehicle"`
	BillingTotal      sql.NullString    `json:"billing_total"`
}

func (q *Queries) UpsertFactBillingForDay(ctx context.Context, arg UpsertFactBillingForDayParams) (FtBilling, error) {
	row := q.db.QueryRowContext(ctx, upsertFactBillingForDay,
		arg.BstDate,
		arg.TemplateID,
		arg.ServiceID,
		arg.NotificationType,
		arg.Provider,
		arg.RateMultiplier,
		arg.International,
		arg.Rate,
		arg.BillableUnits,
		arg.NotificationsSent,
		arg.UpdatedAt,
		arg.CreatedAt,
		arg.Postage,
		arg.SmsSendingVehicle,
		arg.BillingTotal,
	)
	var i FtBilling
	err := row.Scan(
		&i.BstDate,
		&i.TemplateID,
		&i.ServiceID,
		&i.NotificationType,
		&i.Provider,
		&i.RateMultiplier,
		&i.International,
		&i.Rate,
		&i.BillableUnits,
		&i.NotificationsSent,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Postage,
		&i.SmsSendingVehicle,
		&i.BillingTotal,
	)
	return i, err
}

const upsertFactNotificationStatus = `-- name: UpsertFactNotificationStatus :one
INSERT INTO ft_notification_status (
        bst_date,
        template_id,
        service_id,
        job_id,
        notification_type,
        key_type,
        notification_status,
        notification_count,
        created_at,
        updated_at,
        billable_units
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11
    ) ON CONFLICT (
        bst_date,
        template_id,
        service_id,
        job_id,
        notification_type,
        key_type,
        notification_status
    ) DO
UPDATE
SET notification_count = EXCLUDED.notification_count,
    billable_units = EXCLUDED.billable_units,
    updated_at = EXCLUDED.updated_at
RETURNING bst_date, template_id, service_id, job_id, notification_type, key_type, notification_status, notification_count, created_at, updated_at, billable_units
`

type UpsertFactNotificationStatusParams struct {
	BstDate            time.Time    `json:"bst_date"`
	TemplateID         uuid.UUID    `json:"template_id"`
	ServiceID          uuid.UUID    `json:"service_id"`
	JobID              uuid.UUID    `json:"job_id"`
	NotificationType   string       `json:"notification_type"`
	KeyType            string       `json:"key_type"`
	NotificationStatus string       `json:"notification_status"`
	NotificationCount  int32        `json:"notification_count"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          sql.NullTime `json:"updated_at"`
	BillableUnits      int32        `json:"billable_units"`
}

func (q *Queries) UpsertFactNotificationStatus(ctx context.Context, arg UpsertFactNotificationStatusParams) (FtNotificationStatus, error) {
	row := q.db.QueryRowContext(ctx, upsertFactNotificationStatus,
		arg.BstDate,
		arg.TemplateID,
		arg.ServiceID,
		arg.JobID,
		arg.NotificationType,
		arg.KeyType,
		arg.NotificationStatus,
		arg.NotificationCount,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.BillableUnits,
	)
	var i FtNotificationStatus
	err := row.Scan(
		&i.BstDate,
		&i.TemplateID,
		&i.ServiceID,
		&i.JobID,
		&i.NotificationType,
		&i.KeyType,
		&i.NotificationStatus,
		&i.NotificationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillableUnits,
	)
	return i, err
}

const upsertFreeSMSFragmentLimit = `-- name: UpsertFreeSMSFragmentLimit :one
WITH updated AS (
    UPDATE annual_billing
    SET free_sms_fragment_limit = $4,
        updated_at = now()
    WHERE service_id = $2
        AND financial_year_start = $3
    RETURNING id, service_id, financial_year_start, free_sms_fragment_limit, updated_at, created_at
)
INSERT INTO annual_billing (
        id,
        service_id,
        financial_year_start,
        free_sms_fragment_limit,
        updated_at,
        created_at
    )
SELECT $1,
    $2,
    $3,
    $4,
    $5,
    $6
WHERE NOT EXISTS (
        SELECT 1
        FROM updated
    )
RETURNING id, service_id, financial_year_start, free_sms_fragment_limit, updated_at, created_at
`

type UpsertFreeSMSFragmentLimitParams struct {
	ID                   uuid.UUID    `json:"id"`
	ServiceID            uuid.UUID    `json:"service_id"`
	FinancialYearStart   int32        `json:"financial_year_start"`
	FreeSmsFragmentLimit int32        `json:"free_sms_fragment_limit"`
	UpdatedAt            sql.NullTime `json:"updated_at"`
	CreatedAt            time.Time    `json:"created_at"`
}

func (q *Queries) UpsertFreeSMSFragmentLimit(ctx context.Context, arg UpsertFreeSMSFragmentLimitParams) (AnnualBilling, error) {
	row := q.db.QueryRowContext(ctx, upsertFreeSMSFragmentLimit,
		arg.ID,
		arg.ServiceID,
		arg.FinancialYearStart,
		arg.FreeSmsFragmentLimit,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	var i AnnualBilling
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.FinancialYearStart,
		&i.FreeSmsFragmentLimit,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMonthlyNotificationStatsSummary = `-- name: UpsertMonthlyNotificationStatsSummary :one
INSERT INTO monthly_notification_stats_summary (
        month,
        service_id,
        notification_type,
        notification_count,
        updated_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        coalesce($5, now())
    ) ON CONFLICT (month, service_id, notification_type) DO
UPDATE
SET notification_count = EXCLUDED.notification_count,
    updated_at = EXCLUDED.updated_at
RETURNING month, service_id, notification_type, notification_count, updated_at
`

type UpsertMonthlyNotificationStatsSummaryParams struct {
	Month             string      `json:"month"`
	ServiceID         uuid.UUID   `json:"service_id"`
	NotificationType  string      `json:"notification_type"`
	NotificationCount int32       `json:"notification_count"`
	UpdatedAt         interface{} `json:"updated_at"`
}

func (q *Queries) UpsertMonthlyNotificationStatsSummary(ctx context.Context, arg UpsertMonthlyNotificationStatsSummaryParams) (MonthlyNotificationStatsSummary, error) {
	row := q.db.QueryRowContext(ctx, upsertMonthlyNotificationStatsSummary,
		arg.Month,
		arg.ServiceID,
		arg.NotificationType,
		arg.NotificationCount,
		arg.UpdatedAt,
	)
	var i MonthlyNotificationStatsSummary
	err := row.Scan(
		&i.Month,
		&i.ServiceID,
		&i.NotificationType,
		&i.NotificationCount,
		&i.UpdatedAt,
	)
	return i, err
}
