// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package reports

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
        id,
        report_type,
        requested_at,
        completed_at,
        expires_at,
        requesting_user_id,
        service_id,
        job_id,
        url,
        status,
        language
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11
    )
RETURNING id, report_type, requested_at, completed_at, expires_at, requesting_user_id, service_id, job_id, url, status, language
`

type CreateReportParams struct {
	ID               uuid.UUID      `json:"id"`
	ReportType       string         `json:"report_type"`
	RequestedAt      time.Time      `json:"requested_at"`
	CompletedAt      sql.NullTime   `json:"completed_at"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	RequestingUserID uuid.NullUUID  `json:"requesting_user_id"`
	ServiceID        uuid.UUID      `json:"service_id"`
	JobID            uuid.NullUUID  `json:"job_id"`
	Url              sql.NullString `json:"url"`
	Status           string         `json:"status"`
	Language         sql.NullString `json:"language"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport,
		arg.ID,
		arg.ReportType,
		arg.RequestedAt,
		arg.CompletedAt,
		arg.ExpiresAt,
		arg.RequestingUserID,
		arg.ServiceID,
		arg.JobID,
		arg.Url,
		arg.Status,
		arg.Language,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReportType,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.RequestingUserID,
		&i.ServiceID,
		&i.JobID,
		&i.Url,
		&i.Status,
		&i.Language,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, report_type, requested_at, completed_at, expires_at, requesting_user_id, service_id, job_id, url, status, language
FROM reports
WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRowContext(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReportType,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.RequestingUserID,
		&i.ServiceID,
		&i.JobID,
		&i.Url,
		&i.Status,
		&i.Language,
	)
	return i, err
}

const getReportsByServiceID = `-- name: GetReportsByServiceID :many
SELECT id, report_type, requested_at, completed_at, expires_at, requesting_user_id, service_id, job_id, url, status, language
FROM reports
WHERE service_id = $1
ORDER BY requested_at DESC
`

func (q *Queries) GetReportsByServiceID(ctx context.Context, serviceID uuid.UUID) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, getReportsByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReportType,
			&i.RequestedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.RequestingUserID,
			&i.ServiceID,
			&i.JobID,
			&i.Url,
			&i.Status,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReport = `-- name: UpdateReport :one
UPDATE reports
SET report_type = $1,
    requested_at = $2,
    completed_at = $3,
    expires_at = $4,
    requesting_user_id = $5,
    service_id = $6,
    job_id = $7,
    url = $8,
    status = $9,
    language = $10
WHERE id = $11
RETURNING id, report_type, requested_at, completed_at, expires_at, requesting_user_id, service_id, job_id, url, status, language
`

type UpdateReportParams struct {
	ReportType       string         `json:"report_type"`
	RequestedAt      time.Time      `json:"requested_at"`
	CompletedAt      sql.NullTime   `json:"completed_at"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	RequestingUserID uuid.NullUUID  `json:"requesting_user_id"`
	ServiceID        uuid.UUID      `json:"service_id"`
	JobID            uuid.NullUUID  `json:"job_id"`
	Url              sql.NullString `json:"url"`
	Status           string         `json:"status"`
	Language         sql.NullString `json:"language"`
	ID               uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateReport(ctx context.Context, arg UpdateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, updateReport,
		arg.ReportType,
		arg.RequestedAt,
		arg.CompletedAt,
		arg.ExpiresAt,
		arg.RequestingUserID,
		arg.ServiceID,
		arg.JobID,
		arg.Url,
		arg.Status,
		arg.Language,
		arg.ID,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReportType,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.RequestingUserID,
		&i.ServiceID,
		&i.JobID,
		&i.Url,
		&i.Status,
		&i.Language,
	)
	return i, err
}
