// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package users

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const activateUser = `-- name: ActivateUser :one
UPDATE users
SET blocked = false,
    updated_at = now()
WHERE id = $1
RETURNING id, name, email_address, created_at, updated_at, _password, mobile_number, password_changed_at, logged_in_at, failed_login_count, state, platform_admin, current_session_id, auth_type, blocked, additional_information, password_expired, verified_phonenumber, default_editor_is_rte
`

func (q *Queries) ActivateUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, activateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.MobileNumber,
		&i.PasswordChangedAt,
		&i.LoggedInAt,
		&i.FailedLoginCount,
		&i.State,
		&i.PlatformAdmin,
		&i.CurrentSessionID,
		&i.AuthType,
		&i.Blocked,
		&i.AdditionalInformation,
		&i.PasswordExpired,
		&i.VerifiedPhonenumber,
		&i.DefaultEditorIsRte,
	)
	return i, err
}

const archiveUser = `-- name: ArchiveUser :one
UPDATE users
SET state = 'archived',
    blocked = true,
    updated_at = now()
WHERE id = $1
RETURNING id, name, email_address, created_at, updated_at, _password, mobile_number, password_changed_at, logged_in_at, failed_login_count, state, platform_admin, current_session_id, auth_type, blocked, additional_information, password_expired, verified_phonenumber, default_editor_is_rte
`

func (q *Queries) ArchiveUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, archiveUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.MobileNumber,
		&i.PasswordChangedAt,
		&i.LoggedInAt,
		&i.FailedLoginCount,
		&i.State,
		&i.PlatformAdmin,
		&i.CurrentSessionID,
		&i.AuthType,
		&i.Blocked,
		&i.AdditionalInformation,
		&i.PasswordExpired,
		&i.VerifiedPhonenumber,
		&i.DefaultEditorIsRte,
	)
	return i, err
}

const createFido2Key = `-- name: CreateFido2Key :one
INSERT INTO fido2_keys (
        id,
        user_id,
        name,
        key,
        created_at,
        updated_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
RETURNING id, user_id, name, key, created_at, updated_at
`

type CreateFido2KeyParams struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Name      string       `json:"name"`
	Key       string       `json:"key"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) CreateFido2Key(ctx context.Context, arg CreateFido2KeyParams) (Fido2Key, error) {
	row := q.db.QueryRowContext(ctx, createFido2Key,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Key,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Fido2Key
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFido2Session = `-- name: CreateFido2Session :one
INSERT INTO fido2_sessions (user_id, session, created_at)
VALUES (
        $1,
        $2,
        $3
    ) ON CONFLICT (user_id) DO
UPDATE
SET session = EXCLUDED.session,
    created_at = EXCLUDED.created_at
RETURNING user_id, session, created_at
`

type CreateFido2SessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Session   string    `json:"session"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateFido2Session(ctx context.Context, arg CreateFido2SessionParams) (Fido2Session, error) {
	row := q.db.QueryRowContext(ctx, createFido2Session, arg.UserID, arg.Session, arg.CreatedAt)
	var i Fido2Session
	err := row.Scan(&i.UserID, &i.Session, &i.CreatedAt)
	return i, err
}

const createLoginEvent = `-- name: CreateLoginEvent :one
INSERT INTO login_events (
        id,
        user_id,
        data,
        created_at,
        updated_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5
    )
RETURNING id, user_id, data, created_at, updated_at
`

type CreateLoginEventParams struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	Data      json.RawMessage `json:"data"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}

func (q *Queries) CreateLoginEvent(ctx context.Context, arg CreateLoginEventParams) (LoginEvent, error) {
	row := q.db.QueryRowContext(ctx, createLoginEvent,
		arg.ID,
		arg.UserID,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LoginEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
        id,
        name,
        email_address,
        created_at,
        updated_at,
        _password,
        mobile_number,
        password_changed_at,
        logged_in_at,
        failed_login_count,
        state,
        platform_admin,
        current_session_id,
        auth_type,
        blocked,
        additional_information,
        password_expired,
        verified_phonenumber,
        default_editor_is_rte
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19
    )
RETURNING id, name, email_address, created_at, updated_at, _password, mobile_number, password_changed_at, logged_in_at, failed_login_count, state, platform_admin, current_session_id, auth_type, blocked, additional_information, password_expired, verified_phonenumber, default_editor_is_rte
`

type CreateUserParams struct {
	ID                    uuid.UUID       `json:"id"`
	Name                  string          `json:"name"`
	EmailAddress          string          `json:"email_address"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             sql.NullTime    `json:"updated_at"`
	Password              string          `json:"password"`
	MobileNumber          sql.NullString  `json:"mobile_number"`
	PasswordChangedAt     time.Time       `json:"password_changed_at"`
	LoggedInAt            sql.NullTime    `json:"logged_in_at"`
	FailedLoginCount      int32           `json:"failed_login_count"`
	State                 string          `json:"state"`
	PlatformAdmin         bool            `json:"platform_admin"`
	CurrentSessionID      uuid.NullUUID   `json:"current_session_id"`
	AuthType              string          `json:"auth_type"`
	Blocked               bool            `json:"blocked"`
	AdditionalInformation json.RawMessage `json:"additional_information"`
	PasswordExpired       bool            `json:"password_expired"`
	VerifiedPhonenumber   sql.NullBool    `json:"verified_phonenumber"`
	DefaultEditorIsRte    bool            `json:"default_editor_is_rte"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.EmailAddress,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Password,
		arg.MobileNumber,
		arg.PasswordChangedAt,
		arg.LoggedInAt,
		arg.FailedLoginCount,
		arg.State,
		arg.PlatformAdmin,
		arg.CurrentSessionID,
		arg.AuthType,
		arg.Blocked,
		arg.AdditionalInformation,
		arg.PasswordExpired,
		arg.VerifiedPhonenumber,
		arg.DefaultEditorIsRte,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.MobileNumber,
		&i.PasswordChangedAt,
		&i.LoggedInAt,
		&i.FailedLoginCount,
		&i.State,
		&i.PlatformAdmin,
		&i.CurrentSessionID,
		&i.AuthType,
		&i.Blocked,
		&i.AdditionalInformation,
		&i.PasswordExpired,
		&i.VerifiedPhonenumber,
		&i.DefaultEditorIsRte,
	)
	return i, err
}

const createVerifyCode = `-- name: CreateVerifyCode :one
INSERT INTO verify_codes (
        id,
        user_id,
        _code,
        code_type,
        expiry_datetime,
        code_used,
        created_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    )
RETURNING id, user_id, _code, code_type, expiry_datetime, code_used, created_at
`

type CreateVerifyCodeParams struct {
	ID             uuid.UUID       `json:"id"`
	UserID         uuid.UUID       `json:"user_id"`
	Code           string          `json:"code"`
	CodeType       VerifyCodeTypes `json:"code_type"`
	ExpiryDatetime time.Time       `json:"expiry_datetime"`
	CodeUsed       sql.NullBool    `json:"code_used"`
	CreatedAt      time.Time       `json:"created_at"`
}

func (q *Queries) CreateVerifyCode(ctx context.Context, arg CreateVerifyCodeParams) (VerifyCode, error) {
	row := q.db.QueryRowContext(ctx, createVerifyCode,
		arg.ID,
		arg.UserID,
		arg.Code,
		arg.CodeType,
		arg.ExpiryDatetime,
		arg.CodeUsed,
		arg.CreatedAt,
	)
	var i VerifyCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.CodeType,
		&i.ExpiryDatetime,
		&i.CodeUsed,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE users
SET blocked = true,
    updated_at = now()
WHERE id = $1
RETURNING id, name, email_address, created_at, updated_at, _password, mobile_number, password_changed_at, logged_in_at, failed_login_count, state, platform_admin, current_session_id, auth_type, blocked, additional_information, password_expired, verified_phonenumber, default_editor_is_rte
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, deactivateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.MobileNumber,
		&i.PasswordChangedAt,
		&i.LoggedInAt,
		&i.FailedLoginCount,
		&i.State,
		&i.PlatformAdmin,
		&i.CurrentSessionID,
		&i.AuthType,
		&i.Blocked,
		&i.AdditionalInformation,
		&i.PasswordExpired,
		&i.VerifiedPhonenumber,
		&i.DefaultEditorIsRte,
	)
	return i, err
}

const deleteExpiredVerifyCodes = `-- name: DeleteExpiredVerifyCodes :execrows
DELETE FROM verify_codes
WHERE expiry_datetime < $1
`

func (q *Queries) DeleteExpiredVerifyCodes(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredVerifyCodes, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFido2Key = `-- name: DeleteFido2Key :execrows
DELETE FROM fido2_keys
WHERE id = $1
`

func (q *Queries) DeleteFido2Key(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFido2Key, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findUsersByEmail = `-- name: FindUsersByEmail :many
SELECT id, name, email_address, created_at, updated_at, _password, mobile_number, password_changed_at, logged_in_at, failed_login_count, state, platform_admin, current_session_id, auth_type, blocked, additional_information, password_expired, verified_phonenumber, default_editor_is_rte
FROM users
WHERE email_address ILIKE '%' || $1 || '%'
ORDER BY email_address ASC
`

func (q *Queries) FindUsersByEmail(ctx context.Context, emailQuery sql.NullString) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, findUsersByEmail, emailQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EmailAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Password,
			&i.MobileNumber,
			&i.PasswordChangedAt,
			&i.LoggedInAt,
			&i.FailedLoginCount,
			&i.State,
			&i.PlatformAdmin,
			&i.CurrentSessionID,
			&i.AuthType,
			&i.Blocked,
			&i.AdditionalInformation,
			&i.PasswordExpired,
			&i.VerifiedPhonenumber,
			&i.DefaultEditorIsRte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, email_address, created_at, updated_at, _password, mobile_number, password_changed_at, logged_in_at, failed_login_count, state, platform_admin, current_session_id, auth_type, blocked, additional_information, password_expired, verified_phonenumber, default_editor_is_rte
FROM users
ORDER BY created_at DESC
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EmailAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Password,
			&i.MobileNumber,
			&i.PasswordChangedAt,
			&i.LoggedInAt,
			&i.FailedLoginCount,
			&i.State,
			&i.PlatformAdmin,
			&i.CurrentSessionID,
			&i.AuthType,
			&i.Blocked,
			&i.AdditionalInformation,
			&i.PasswordExpired,
			&i.VerifiedPhonenumber,
			&i.DefaultEditorIsRte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFido2KeysByUserID = `-- name: GetFido2KeysByUserID :many
SELECT id, user_id, name, key, created_at, updated_at
FROM fido2_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFido2KeysByUserID(ctx context.Context, userID uuid.UUID) ([]Fido2Key, error) {
	rows, err := q.db.QueryContext(ctx, getFido2KeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fido2Key
	for rows.Next() {
		var i Fido2Key
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Key,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFido2Session = `-- name: GetFido2Session :one
SELECT user_id, session, created_at
FROM fido2_sessions
WHERE user_id = $1
`

func (q *Queries) GetFido2Session(ctx context.Context, userID uuid.UUID) (Fido2Session, error) {
	row := q.db.QueryRowContext(ctx, getFido2Session, userID)
	var i Fido2Session
	err := row.Scan(&i.UserID, &i.Session, &i.CreatedAt)
	return i, err
}

const getInvitedUsersByServiceID = `-- name: GetInvitedUsersByServiceID :many
SELECT id, email_address, user_id, service_id, created_at, status, permissions, auth_type, folder_permissions
FROM invited_users
WHERE service_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetInvitedUsersByServiceID(ctx context.Context, serviceID uuid.NullUUID) ([]InvitedUser, error) {
	rows, err := q.db.QueryContext(ctx, getInvitedUsersByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvitedUser
	for rows.Next() {
		var i InvitedUser
		if err := rows.Scan(
			&i.ID,
			&i.EmailAddress,
			&i.UserID,
			&i.ServiceID,
			&i.CreatedAt,
			&i.Status,
			&i.Permissions,
			&i.AuthType,
			&i.FolderPermissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoginEventsByUserID = `-- name: GetLoginEventsByUserID :many
SELECT id, user_id, data, created_at, updated_at
FROM login_events
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetLoginEventsByUserID(ctx context.Context, userID uuid.UUID) ([]LoginEvent, error) {
	rows, err := q.db.QueryContext(ctx, getLoginEventsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoginEvent
	for rows.Next() {
		var i LoginEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email_address, created_at, updated_at, _password, mobile_number, password_changed_at, logged_in_at, failed_login_count, state, platform_admin, current_session_id, auth_type, blocked, additional_information, password_expired, verified_phonenumber, default_editor_is_rte
FROM users
WHERE email_address = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, emailAddress string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, emailAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.MobileNumber,
		&i.PasswordChangedAt,
		&i.LoggedInAt,
		&i.FailedLoginCount,
		&i.State,
		&i.PlatformAdmin,
		&i.CurrentSessionID,
		&i.AuthType,
		&i.Blocked,
		&i.AdditionalInformation,
		&i.PasswordExpired,
		&i.VerifiedPhonenumber,
		&i.DefaultEditorIsRte,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email_address, created_at, updated_at, _password, mobile_number, password_changed_at, logged_in_at, failed_login_count, state, platform_admin, current_session_id, auth_type, blocked, additional_information, password_expired, verified_phonenumber, default_editor_is_rte
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.MobileNumber,
		&i.PasswordChangedAt,
		&i.LoggedInAt,
		&i.FailedLoginCount,
		&i.State,
		&i.PlatformAdmin,
		&i.CurrentSessionID,
		&i.AuthType,
		&i.Blocked,
		&i.AdditionalInformation,
		&i.PasswordExpired,
		&i.VerifiedPhonenumber,
		&i.DefaultEditorIsRte,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT permission
FROM permissions
WHERE service_id = $1
    AND user_id = $2
ORDER BY permission ASC
`

type GetUserPermissionsParams struct {
	ServiceID uuid.NullUUID `json:"service_id"`
	UserID    uuid.UUID     `json:"user_id"`
}

func (q *Queries) GetUserPermissions(ctx context.Context, arg GetUserPermissionsParams) ([]PermissionTypes, error) {
	rows, err := q.db.QueryContext(ctx, getUserPermissions, arg.ServiceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionTypes
	for rows.Next() {
		var permission PermissionTypes
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByServiceID = `-- name: GetUsersByServiceID :many
SELECT u.id, u.name, u.email_address, u.created_at, u.updated_at, u._password, u.mobile_number, u.password_changed_at, u.logged_in_at, u.failed_login_count, u.state, u.platform_admin, u.current_session_id, u.auth_type, u.blocked, u.additional_information, u.password_expired, u.verified_phonenumber, u.default_editor_is_rte
FROM users AS u
    JOIN user_to_service AS uts ON uts.user_id = u.id
WHERE uts.service_id = $1
ORDER BY u.name ASC
`

func (q *Queries) GetUsersByServiceID(ctx context.Context, serviceID uuid.NullUUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EmailAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Password,
			&i.MobileNumber,
			&i.PasswordChangedAt,
			&i.LoggedInAt,
			&i.FailedLoginCount,
			&i.State,
			&i.PlatformAdmin,
			&i.CurrentSessionID,
			&i.AuthType,
			&i.Blocked,
			&i.AdditionalInformation,
			&i.PasswordExpired,
			&i.VerifiedPhonenumber,
			&i.DefaultEditorIsRte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVerifyCode = `-- name: GetVerifyCode :one
SELECT id, user_id, _code, code_type, expiry_datetime, code_used, created_at
FROM verify_codes
WHERE user_id = $1
    AND code_type = $2
    AND coalesce(code_used, false) = false
ORDER BY created_at DESC
LIMIT 1
`

type GetVerifyCodeParams struct {
	UserID   uuid.UUID       `json:"user_id"`
	CodeType VerifyCodeTypes `json:"code_type"`
}

func (q *Queries) GetVerifyCode(ctx context.Context, arg GetVerifyCodeParams) (VerifyCode, error) {
	row := q.db.QueryRowContext(ctx, getVerifyCode, arg.UserID, arg.CodeType)
	var i VerifyCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.CodeType,
		&i.ExpiryDatetime,
		&i.CodeUsed,
		&i.CreatedAt,
	)
	return i, err
}

const markVerifyCodeUsed = `-- name: MarkVerifyCodeUsed :one
UPDATE verify_codes
SET code_used = true
WHERE id = $1
RETURNING id, user_id, _code, code_type, expiry_datetime, code_used, created_at
`

func (q *Queries) MarkVerifyCodeUsed(ctx context.Context, id uuid.UUID) (VerifyCode, error) {
	row := q.db.QueryRowContext(ctx, markVerifyCodeUsed, id)
	var i VerifyCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.CodeType,
		&i.ExpiryDatetime,
		&i.CodeUsed,
		&i.CreatedAt,
	)
	return i, err
}

const setFolderPermissions = `-- name: SetFolderPermissions :exec
WITH deleted AS (
    DELETE FROM user_folder_permissions
    WHERE service_id = $2
        AND user_id = $1
)
INSERT INTO user_folder_permissions (user_id, template_folder_id, service_id)
SELECT $1,
    folder_id,
    $2
FROM unnest($3::uuid []) AS folder_id
`

type SetFolderPermissionsParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	ServiceID uuid.UUID   `json:"service_id"`
	FolderIds []uuid.UUID `json:"folder_ids"`
}

func (q *Queries) SetFolderPermissions(ctx context.Context, arg SetFolderPermissionsParams) error {
	_, err := q.db.ExecContext(ctx, setFolderPermissions, arg.UserID, arg.ServiceID, pq.Array(arg.FolderIds))
	return err
}

const setUserPermissions = `-- name: SetUserPermissions :exec
WITH deleted AS (
    DELETE FROM permissions
    WHERE service_id = $1
        AND user_id = $2
)
INSERT INTO permissions (id, service_id, user_id, permission, created_at)
SELECT id,
    $1,
    $2,
    permission::public.permission_types,
    created_at
FROM jsonb_to_recordset($3::jsonb) AS t(
        id uuid,
        permission text,
        created_at timestamp
    )
`

type SetUserPermissionsParams struct {
	ServiceID       uuid.NullUUID   `json:"service_id"`
	UserID          uuid.UUID       `json:"user_id"`
	PermissionItems json.RawMessage `json:"permission_items"`
}

func (q *Queries) SetUserPermissions(ctx context.Context, arg SetUserPermissionsParams) error {
	_, err := q.db.ExecContext(ctx, setUserPermissions, arg.ServiceID, arg.UserID, arg.PermissionItems)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1,
    email_address = $2,
    updated_at = $3,
    _password = $4,
    mobile_number = $5,
    password_changed_at = $6,
    logged_in_at = $7,
    failed_login_count = $8,
    state = $9,
    platform_admin = $10,
    current_session_id = $11,
    auth_type = $12,
    blocked = $13,
    additional_information = $14,
    password_expired = $15,
    verified_phonenumber = $16,
    default_editor_is_rte = $17
WHERE id = $18
RETURNING id, name, email_address, created_at, updated_at, _password, mobile_number, password_changed_at, logged_in_at, failed_login_count, state, platform_admin, current_session_id, auth_type, blocked, additional_information, password_expired, verified_phonenumber, default_editor_is_rte
`

type UpdateUserParams struct {
	Name                  string          `json:"name"`
	EmailAddress          string          `json:"email_address"`
	UpdatedAt             sql.NullTime    `json:"updated_at"`
	Password              string          `json:"password"`
	MobileNumber          sql.NullString  `json:"mobile_number"`
	PasswordChangedAt     time.Time       `json:"password_changed_at"`
	LoggedInAt            sql.NullTime    `json:"logged_in_at"`
	FailedLoginCount      int32           `json:"failed_login_count"`
	State                 string          `json:"state"`
	PlatformAdmin         bool            `json:"platform_admin"`
	CurrentSessionID      uuid.NullUUID   `json:"current_session_id"`
	AuthType              string          `json:"auth_type"`
	Blocked               bool            `json:"blocked"`
	AdditionalInformation json.RawMessage `json:"additional_information"`
	PasswordExpired       bool            `json:"password_expired"`
	VerifiedPhonenumber   sql.NullBool    `json:"verified_phonenumber"`
	DefaultEditorIsRte    bool            `json:"default_editor_is_rte"`
	ID                    uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.EmailAddress,
		arg.UpdatedAt,
		arg.Password,
		arg.MobileNumber,
		arg.PasswordChangedAt,
		arg.LoggedInAt,
		arg.FailedLoginCount,
		arg.State,
		arg.PlatformAdmin,
		arg.CurrentSessionID,
		arg.AuthType,
		arg.Blocked,
		arg.AdditionalInformation,
		arg.PasswordExpired,
		arg.VerifiedPhonenumber,
		arg.DefaultEditorIsRte,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.MobileNumber,
		&i.PasswordChangedAt,
		&i.LoggedInAt,
		&i.FailedLoginCount,
		&i.State,
		&i.PlatformAdmin,
		&i.CurrentSessionID,
		&i.AuthType,
		&i.Blocked,
		&i.AdditionalInformation,
		&i.PasswordExpired,
		&i.VerifiedPhonenumber,
		&i.DefaultEditorIsRte,
	)
	return i, err
}
