// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package api_keys

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
        id,
        name,
        secret,
        service_id,
        expiry_date,
        created_at,
        created_by_id,
        updated_at,
        version,
        key_type,
        compromised_key_info,
        last_used_timestamp
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12
    )
RETURNING id, name, secret, service_id, expiry_date, created_at, created_by_id, updated_at, version, key_type, compromised_key_info, last_used_timestamp
`

type CreateAPIKeyParams struct {
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	Secret             string          `json:"secret"`
	ServiceID          uuid.UUID       `json:"service_id"`
	ExpiryDate         sql.NullTime    `json:"expiry_date"`
	CreatedAt          time.Time       `json:"created_at"`
	CreatedByID        uuid.UUID       `json:"created_by_id"`
	UpdatedAt          sql.NullTime    `json:"updated_at"`
	Version            int32           `json:"version"`
	KeyType            string          `json:"key_type"`
	CompromisedKeyInfo json.RawMessage `json:"compromised_key_info"`
	LastUsedTimestamp  sql.NullTime    `json:"last_used_timestamp"`
}

// partial unique index `uix_service_to_key_name` only applies to active keys (`expiry_date IS NULL`), so revoked names can be reused.
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.Secret,
		arg.ServiceID,
		arg.ExpiryDate,
		arg.CreatedAt,
		arg.CreatedByID,
		arg.UpdatedAt,
		arg.Version,
		arg.KeyType,
		arg.CompromisedKeyInfo,
		arg.LastUsedTimestamp,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Secret,
		&i.ServiceID,
		&i.ExpiryDate,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.Version,
		&i.KeyType,
		&i.CompromisedKeyInfo,
		&i.LastUsedTimestamp,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, name, secret, service_id, expiry_date, created_at, created_by_id, updated_at, version, key_type, compromised_key_info, last_used_timestamp
FROM api_keys
WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Secret,
		&i.ServiceID,
		&i.ExpiryDate,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.Version,
		&i.KeyType,
		&i.CompromisedKeyInfo,
		&i.LastUsedTimestamp,
	)
	return i, err
}

const getAPIKeyBySecret = `-- name: GetAPIKeyBySecret :one
SELECT id, name, secret, service_id, expiry_date, created_at, created_by_id, updated_at, version, key_type, compromised_key_info, last_used_timestamp
FROM api_keys
WHERE secret = $1
    AND expiry_date IS NULL
LIMIT 1
`

func (q *Queries) GetAPIKeyBySecret(ctx context.Context, secret string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyBySecret, secret)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Secret,
		&i.ServiceID,
		&i.ExpiryDate,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.Version,
		&i.KeyType,
		&i.CompromisedKeyInfo,
		&i.LastUsedTimestamp,
	)
	return i, err
}

const getAPIKeySummaryStats = `-- name: GetAPIKeySummaryStats :one
SELECT k.id,
    k.service_id,
    k.name,
    k.expiry_date,
    k.last_used_timestamp,
    count(n.id) AS notifications_sent
FROM api_keys AS k
    LEFT JOIN notifications AS n ON n.api_key_id = k.id
WHERE k.id = $1
GROUP BY k.id,
    k.service_id,
    k.name,
    k.expiry_date,
    k.last_used_timestamp
`

type GetAPIKeySummaryStatsRow struct {
	ID                uuid.UUID    `json:"id"`
	ServiceID         uuid.UUID    `json:"service_id"`
	Name              string       `json:"name"`
	ExpiryDate        sql.NullTime `json:"expiry_date"`
	LastUsedTimestamp sql.NullTime `json:"last_used_timestamp"`
	NotificationsSent int64        `json:"notifications_sent"`
}

func (q *Queries) GetAPIKeySummaryStats(ctx context.Context, id uuid.UUID) (GetAPIKeySummaryStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeySummaryStats, id)
	var i GetAPIKeySummaryStatsRow
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.ExpiryDate,
		&i.LastUsedTimestamp,
		&i.NotificationsSent,
	)
	return i, err
}

const getAPIKeysByServiceID = `-- name: GetAPIKeysByServiceID :many
SELECT id, name, secret, service_id, expiry_date, created_at, created_by_id, updated_at, version, key_type, compromised_key_info, last_used_timestamp
FROM api_keys
WHERE service_id = $1
    AND expiry_date IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAPIKeysByServiceID(ctx context.Context, serviceID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, getAPIKeysByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Secret,
			&i.ServiceID,
			&i.ExpiryDate,
			&i.CreatedAt,
			&i.CreatedByID,
			&i.UpdatedAt,
			&i.Version,
			&i.KeyType,
			&i.CompromisedKeyInfo,
			&i.LastUsedTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAPIKeysRankedByNotifications = `-- name: GetAPIKeysRankedByNotifications :many
SELECT k.id,
    k.service_id,
    k.name,
    count(n.id) AS notifications_sent
FROM api_keys AS k
    LEFT JOIN notifications AS n ON n.api_key_id = k.id
    AND n.created_at >= $1
GROUP BY k.id,
    k.service_id,
    k.name
ORDER BY notifications_sent DESC,
    k.name ASC
`

type GetAPIKeysRankedByNotificationsRow struct {
	ID                uuid.UUID `json:"id"`
	ServiceID         uuid.UUID `json:"service_id"`
	Name              string    `json:"name"`
	NotificationsSent int64     `json:"notifications_sent"`
}

func (q *Queries) GetAPIKeysRankedByNotifications(ctx context.Context, since time.Time) ([]GetAPIKeysRankedByNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAPIKeysRankedByNotifications, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAPIKeysRankedByNotificationsRow
	for rows.Next() {
		var i GetAPIKeysRankedByNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.NotificationsSent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAPIKeyHistory = `-- name: InsertAPIKeyHistory :exec
INSERT INTO api_keys_history (
        id,
        name,
        secret,
        service_id,
        expiry_date,
        created_at,
        updated_at,
        created_by_id,
        version,
        key_type,
        compromised_key_info,
        last_used_timestamp
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12
    )
`

type InsertAPIKeyHistoryParams struct {
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	Secret             string          `json:"secret"`
	ServiceID          uuid.UUID       `json:"service_id"`
	ExpiryDate         sql.NullTime    `json:"expiry_date"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          sql.NullTime    `json:"updated_at"`
	CreatedByID        uuid.UUID       `json:"created_by_id"`
	Version            int32           `json:"version"`
	KeyType            string          `json:"key_type"`
	CompromisedKeyInfo json.RawMessage `json:"compromised_key_info"`
	LastUsedTimestamp  sql.NullTime    `json:"last_used_timestamp"`
}

func (q *Queries) InsertAPIKeyHistory(ctx context.Context, arg InsertAPIKeyHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertAPIKeyHistory,
		arg.ID,
		arg.Name,
		arg.Secret,
		arg.ServiceID,
		arg.ExpiryDate,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedByID,
		arg.Version,
		arg.KeyType,
		arg.CompromisedKeyInfo,
		arg.LastUsedTimestamp,
	)
	return err
}

const recordAPIKeyCompromise = `-- name: RecordAPIKeyCompromise :one
UPDATE api_keys
SET compromised_key_info = $1,
    updated_at = now(),
    version = version + 1
WHERE id = $2
RETURNING id, name, secret, service_id, expiry_date, created_at, created_by_id, updated_at, version, key_type, compromised_key_info, last_used_timestamp
`

type RecordAPIKeyCompromiseParams struct {
	CompromisedKeyInfo json.RawMessage `json:"compromised_key_info"`
	ID                 uuid.UUID       `json:"id"`
}

func (q *Queries) RecordAPIKeyCompromise(ctx context.Context, arg RecordAPIKeyCompromiseParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, recordAPIKeyCompromise, arg.CompromisedKeyInfo, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Secret,
		&i.ServiceID,
		&i.ExpiryDate,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.Version,
		&i.KeyType,
		&i.CompromisedKeyInfo,
		&i.LastUsedTimestamp,
	)
	return i, err
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET expiry_date = now(),
    updated_at = now(),
    version = version + 1
WHERE id = $1
RETURNING id, name, secret, service_id, expiry_date, created_at, created_by_id, updated_at, version, key_type, compromised_key_info, last_used_timestamp
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, revokeAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Secret,
		&i.ServiceID,
		&i.ExpiryDate,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.Version,
		&i.KeyType,
		&i.CompromisedKeyInfo,
		&i.LastUsedTimestamp,
	)
	return i, err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :one
UPDATE api_keys
SET last_used_timestamp = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, name, secret, service_id, expiry_date, created_at, created_by_id, updated_at, version, key_type, compromised_key_info, last_used_timestamp
`

type UpdateAPIKeyLastUsedParams struct {
	LastUsedTimestamp sql.NullTime `json:"last_used_timestamp"`
	ID                uuid.UUID    `json:"id"`
}

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, updateAPIKeyLastUsed, arg.LastUsedTimestamp, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Secret,
		&i.ServiceID,
		&i.ExpiryDate,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.UpdatedAt,
		&i.Version,
		&i.KeyType,
		&i.CompromisedKeyInfo,
		&i.LastUsedTimestamp,
	)
	return i, err
}
