// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package services

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addUserToService = `-- name: AddUserToService :exec
INSERT INTO user_to_service (user_id, service_id)
VALUES ($1, $2)
`

type AddUserToServiceParams struct {
	UserID    uuid.NullUUID `json:"user_id"`
	ServiceID uuid.NullUUID `json:"service_id"`
}

func (q *Queries) AddUserToService(ctx context.Context, arg AddUserToServiceParams) error {
	_, err := q.db.ExecContext(ctx, addUserToService, arg.UserID, arg.ServiceID)
	return err
}

const archiveService = `-- name: ArchiveService :one
UPDATE services
SET name = name || '_archived_' || extract(
        epoch
        FROM now()
    )::bigint::text,
    active = false,
    updated_at = now()
WHERE id = $1
RETURNING name
`

func (q *Queries) ArchiveService(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, archiveService, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const countLiveServices = `-- name: CountLiveServices :one
SELECT count(*)::bigint
FROM services
WHERE active = true
    AND count_as_live = true
`

func (q *Queries) CountLiveServices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveServices)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createEmailReplyTo = `-- name: CreateEmailReplyTo :one
INSERT INTO service_email_reply_to (
        id,
        service_id,
        email_address,
        is_default,
        created_at,
        updated_at,
        archived
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    )
RETURNING id, service_id, email_address, is_default, created_at, updated_at, archived
`

type CreateEmailReplyToParams struct {
	ID           uuid.UUID    `json:"id"`
	ServiceID    uuid.UUID    `json:"service_id"`
	EmailAddress string       `json:"email_address"`
	IsDefault    bool         `json:"is_default"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	Archived     bool         `json:"archived"`
}

func (q *Queries) CreateEmailReplyTo(ctx context.Context, arg CreateEmailReplyToParams) (ServiceEmailReplyTo, error) {
	row := q.db.QueryRowContext(ctx, createEmailReplyTo,
		arg.ID,
		arg.ServiceID,
		arg.EmailAddress,
		arg.IsDefault,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Archived,
	)
	var i ServiceEmailReplyTo
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.EmailAddress,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const createSMSSender = `-- name: CreateSMSSender :one
INSERT INTO service_sms_senders (
        id,
        sms_sender,
        service_id,
        is_default,
        inbound_number_id,
        created_at,
        updated_at,
        archived
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    )
RETURNING id, sms_sender, service_id, is_default, inbound_number_id, created_at, updated_at, archived
`

type CreateSMSSenderParams struct {
	ID              uuid.UUID     `json:"id"`
	SmsSender       string        `json:"sms_sender"`
	ServiceID       uuid.UUID     `json:"service_id"`
	IsDefault       bool          `json:"is_default"`
	InboundNumberID uuid.NullUUID `json:"inbound_number_id"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       sql.NullTime  `json:"updated_at"`
	Archived        bool          `json:"archived"`
}

func (q *Queries) CreateSMSSender(ctx context.Context, arg CreateSMSSenderParams) (ServiceSmsSender, error) {
	row := q.db.QueryRowContext(ctx, createSMSSender,
		arg.ID,
		arg.SmsSender,
		arg.ServiceID,
		arg.IsDefault,
		arg.InboundNumberID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Archived,
	)
	var i ServiceSmsSender
	err := row.Scan(
		&i.ID,
		&i.SmsSender,
		&i.ServiceID,
		&i.IsDefault,
		&i.InboundNumberID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (
        id,
        name,
        created_at,
        updated_at,
        active,
        message_limit,
        restricted,
        email_from,
        created_by_id,
        version,
        research_mode,
        organisation_type,
        prefix_sms,
        crown,
        rate_limit,
        contact_link,
        consent_to_research,
        volume_email,
        volume_letter,
        volume_sms,
        count_as_live,
        go_live_at,
        go_live_user_id,
        organisation_id,
        sending_domain,
        default_branding_is_french,
        sms_daily_limit,
        organisation_notes,
        sensitive_service,
        email_annual_limit,
        sms_annual_limit,
        suspended_by_id,
        suspended_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32,
        $33
    )
RETURNING id, name, created_at, updated_at, active, message_limit, restricted, email_from, created_by_id, version, research_mode, organisation_type, prefix_sms, crown, rate_limit, contact_link, consent_to_research, volume_email, volume_letter, volume_sms, count_as_live, go_live_at, go_live_user_id, organisation_id, sending_domain, default_branding_is_french, sms_daily_limit, organisation_notes, sensitive_service, email_annual_limit, sms_annual_limit, suspended_by_id, suspended_at
`

type CreateServiceParams struct {
	ID                      uuid.UUID      `json:"id"`
	Name                    string         `json:"name"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               sql.NullTime   `json:"updated_at"`
	Active                  bool           `json:"active"`
	MessageLimit            int64          `json:"message_limit"`
	Restricted              bool           `json:"restricted"`
	EmailFrom               string         `json:"email_from"`
	CreatedByID             uuid.UUID      `json:"created_by_id"`
	Version                 int32          `json:"version"`
	ResearchMode            bool           `json:"research_mode"`
	OrganisationType        sql.NullString `json:"organisation_type"`
	PrefixSms               bool           `json:"prefix_sms"`
	Crown                   sql.NullBool   `json:"crown"`
	RateLimit               int32          `json:"rate_limit"`
	ContactLink             sql.NullString `json:"contact_link"`
	ConsentToResearch       sql.NullBool   `json:"consent_to_research"`
	VolumeEmail             sql.NullInt32  `json:"volume_email"`
	VolumeLetter            sql.NullInt32  `json:"volume_letter"`
	VolumeSms               sql.NullInt32  `json:"volume_sms"`
	CountAsLive             bool           `json:"count_as_live"`
	GoLiveAt                sql.NullTime   `json:"go_live_at"`
	GoLiveUserID            uuid.NullUUID  `json:"go_live_user_id"`
	OrganisationID          uuid.NullUUID  `json:"organisation_id"`
	SendingDomain           sql.NullString `json:"sending_domain"`
	DefaultBrandingIsFrench sql.NullBool   `json:"default_branding_is_french"`
	SmsDailyLimit           int64          `json:"sms_daily_limit"`
	OrganisationNotes       sql.NullString `json:"organisation_notes"`
	SensitiveService        sql.NullBool   `json:"sensitive_service"`
	EmailAnnualLimit        int64          `json:"email_annual_limit"`
	SmsAnnualLimit          int64          `json:"sms_annual_limit"`
	SuspendedByID           uuid.NullUUID  `json:"suspended_by_id"`
	SuspendedAt             sql.NullTime   `json:"suspended_at"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Active,
		arg.MessageLimit,
		arg.Restricted,
		arg.EmailFrom,
		arg.CreatedByID,
		arg.Version,
		arg.ResearchMode,
		arg.OrganisationType,
		arg.PrefixSms,
		arg.Crown,
		arg.RateLimit,
		arg.ContactLink,
		arg.ConsentToResearch,
		arg.VolumeEmail,
		arg.VolumeLetter,
		arg.VolumeSms,
		arg.CountAsLive,
		arg.GoLiveAt,
		arg.GoLiveUserID,
		arg.OrganisationID,
		arg.SendingDomain,
		arg.DefaultBrandingIsFrench,
		arg.SmsDailyLimit,
		arg.OrganisationNotes,
		arg.SensitiveService,
		arg.EmailAnnualLimit,
		arg.SmsAnnualLimit,
		arg.SuspendedByID,
		arg.SuspendedAt,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.MessageLimit,
		&i.Restricted,
		&i.EmailFrom,
		&i.CreatedByID,
		&i.Version,
		&i.ResearchMode,
		&i.OrganisationType,
		&i.PrefixSms,
		&i.Crown,
		&i.RateLimit,
		&i.ContactLink,
		&i.ConsentToResearch,
		&i.VolumeEmail,
		&i.VolumeLetter,
		&i.VolumeSms,
		&i.CountAsLive,
		&i.GoLiveAt,
		&i.GoLiveUserID,
		&i.OrganisationID,
		&i.SendingDomain,
		&i.DefaultBrandingIsFrench,
		&i.SmsDailyLimit,
		&i.OrganisationNotes,
		&i.SensitiveService,
		&i.EmailAnnualLimit,
		&i.SmsAnnualLimit,
		&i.SuspendedByID,
		&i.SuspendedAt,
	)
	return i, err
}

const deleteCallbackAPI = `-- name: DeleteCallbackAPI :execrows
DELETE FROM service_callback_api
WHERE id = $1
`

func (q *Queries) DeleteCallbackAPI(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCallbackAPI, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteInboundAPI = `-- name: DeleteInboundAPI :execrows
DELETE FROM service_inbound_api
WHERE id = $1
`

func (q *Queries) DeleteInboundAPI(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInboundAPI, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllServices = `-- name: GetAllServices :many
SELECT id, name, created_at, updated_at, active, message_limit, restricted, email_from, created_by_id, version, research_mode, organisation_type, prefix_sms, crown, rate_limit, contact_link, consent_to_research, volume_email, volume_letter, volume_sms, count_as_live, go_live_at, go_live_user_id, organisation_id, sending_domain, default_branding_is_french, sms_daily_limit, organisation_notes, sensitive_service, email_annual_limit, sms_annual_limit, suspended_by_id, suspended_at
FROM services
WHERE (
        NOT $1::boolean
        OR active = true
    )
ORDER BY name ASC
`

func (q *Queries) GetAllServices(ctx context.Context, onlyActive bool) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getAllServices, onlyActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Active,
			&i.MessageLimit,
			&i.Restricted,
			&i.EmailFrom,
			&i.CreatedByID,
			&i.Version,
			&i.ResearchMode,
			&i.OrganisationType,
			&i.PrefixSms,
			&i.Crown,
			&i.RateLimit,
			&i.ContactLink,
			&i.ConsentToResearch,
			&i.VolumeEmail,
			&i.VolumeLetter,
			&i.VolumeSms,
			&i.CountAsLive,
			&i.GoLiveAt,
			&i.GoLiveUserID,
			&i.OrganisationID,
			&i.SendingDomain,
			&i.DefaultBrandingIsFrench,
			&i.SmsDailyLimit,
			&i.OrganisationNotes,
			&i.SensitiveService,
			&i.EmailAnnualLimit,
			&i.SmsAnnualLimit,
			&i.SuspendedByID,
			&i.SuspendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCallbackAPIs = `-- name: GetCallbackAPIs :many
SELECT id, service_id, url, bearer_token, created_at, updated_at, updated_by_id, version, callback_type, is_suspended, suspended_at
FROM service_callback_api
WHERE service_id = $1
    AND (
        $2::text IS NULL
        OR callback_type = $2::text
    )
ORDER BY created_at ASC
`

type GetCallbackAPIsParams struct {
	ServiceID    uuid.UUID      `json:"service_id"`
	CallbackType sql.NullString `json:"callback_type"`
}

func (q *Queries) GetCallbackAPIs(ctx context.Context, arg GetCallbackAPIsParams) ([]ServiceCallbackApi, error) {
	rows, err := q.db.QueryContext(ctx, getCallbackAPIs, arg.ServiceID, arg.CallbackType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceCallbackApi
	for rows.Next() {
		var i ServiceCallbackApi
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Url,
			&i.BearerToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByID,
			&i.Version,
			&i.CallbackType,
			&i.IsSuspended,
			&i.SuspendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDataRetention = `-- name: GetDataRetention :many
SELECT id, service_id, notification_type, days_of_retention, created_at, updated_at
FROM service_data_retention
WHERE service_id = $1
ORDER BY notification_type
`

func (q *Queries) GetDataRetention(ctx context.Context, serviceID uuid.UUID) ([]ServiceDataRetention, error) {
	rows, err := q.db.QueryContext(ctx, getDataRetention, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceDataRetention
	for rows.Next() {
		var i ServiceDataRetention
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.NotificationType,
			&i.DaysOfRetention,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailReplyTo = `-- name: GetEmailReplyTo :many
SELECT id, service_id, email_address, is_default, created_at, updated_at, archived
FROM service_email_reply_to
WHERE service_id = $1
    AND archived = false
ORDER BY is_default DESC,
    created_at ASC
`

func (q *Queries) GetEmailReplyTo(ctx context.Context, serviceID uuid.UUID) ([]ServiceEmailReplyTo, error) {
	rows, err := q.db.QueryContext(ctx, getEmailReplyTo, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceEmailReplyTo
	for rows.Next() {
		var i ServiceEmailReplyTo
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.EmailAddress,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInboundAPI = `-- name: GetInboundAPI :one
SELECT id, service_id, url, bearer_token, created_at, updated_at, updated_by_id, version
FROM service_inbound_api
WHERE service_id = $1
LIMIT 1
`

func (q *Queries) GetInboundAPI(ctx context.Context, serviceID uuid.UUID) (ServiceInboundApi, error) {
	row := q.db.QueryRowContext(ctx, getInboundAPI, serviceID)
	var i ServiceInboundApi
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Url,
		&i.BearerToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByID,
		&i.Version,
	)
	return i, err
}

const getLiveServicesData = `-- name: GetLiveServicesData :many
SELECT id,
    name,
    active,
    count_as_live,
    go_live_at,
    suspended_at
FROM services
WHERE active = true
    AND count_as_live = true
ORDER BY name ASC
`

type GetLiveServicesDataRow struct {
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	Active      bool         `json:"active"`
	CountAsLive bool         `json:"count_as_live"`
	GoLiveAt    sql.NullTime `json:"go_live_at"`
	SuspendedAt sql.NullTime `json:"suspended_at"`
}

func (q *Queries) GetLiveServicesData(ctx context.Context) ([]GetLiveServicesDataRow, error) {
	rows, err := q.db.QueryContext(ctx, getLiveServicesData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLiveServicesDataRow
	for rows.Next() {
		var i GetLiveServicesDataRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CountAsLive,
			&i.GoLiveAt,
			&i.SuspendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyDataByService = `-- name: GetMonthlyDataByService :many
SELECT date_trunc('month', n.created_at)::date AS month,
    s.id AS service_id,
    s.name,
    count(n.id) AS notifications_sent
FROM services AS s
    LEFT JOIN notifications AS n ON n.service_id = s.id
WHERE n.created_at >= $1
    AND n.created_at < $2
GROUP BY 1,
    2,
    3
ORDER BY 1,
    3
`

type GetMonthlyDataByServiceParams struct {
	StartAt time.Time `json:"start_at"`
	EndAt   time.Time `json:"end_at"`
}

type GetMonthlyDataByServiceRow struct {
	Month             time.Time `json:"month"`
	ServiceID         uuid.UUID `json:"service_id"`
	Name              string    `json:"name"`
	NotificationsSent int64     `json:"notifications_sent"`
}

func (q *Queries) GetMonthlyDataByService(ctx context.Context, arg GetMonthlyDataByServiceParams) ([]GetMonthlyDataByServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyDataByService, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyDataByServiceRow
	for rows.Next() {
		var i GetMonthlyDataByServiceRow
		if err := rows.Scan(
			&i.Month,
			&i.ServiceID,
			&i.Name,
			&i.NotificationsSent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSMSSenders = `-- name: GetSMSSenders :many
SELECT id, sms_sender, service_id, is_default, inbound_number_id, created_at, updated_at, archived
FROM service_sms_senders
WHERE service_id = $1
    AND archived = false
ORDER BY is_default DESC,
    created_at ASC
`

func (q *Queries) GetSMSSenders(ctx context.Context, serviceID uuid.UUID) ([]ServiceSmsSender, error) {
	rows, err := q.db.QueryContext(ctx, getSMSSenders, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceSmsSender
	for rows.Next() {
		var i ServiceSmsSender
		if err := rows.Scan(
			&i.ID,
			&i.SmsSender,
			&i.ServiceID,
			&i.IsDefault,
			&i.InboundNumberID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSafelist = `-- name: GetSafelist :many
SELECT id, service_id, recipient_type, recipient, created_at
FROM service_safelist
WHERE service_id = $1
ORDER BY recipient_type,
    recipient
`

func (q *Queries) GetSafelist(ctx context.Context, serviceID uuid.UUID) ([]ServiceSafelist, error) {
	rows, err := q.db.QueryContext(ctx, getSafelist, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceSafelist
	for rows.Next() {
		var i ServiceSafelist
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.RecipientType,
			&i.Recipient,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSensitiveServiceIDs = `-- name: GetSensitiveServiceIDs :many
SELECT id
FROM services
WHERE sensitive_service = true
ORDER BY id
`

func (q *Queries) GetSensitiveServiceIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getSensitiveServiceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, name, created_at, updated_at, active, message_limit, restricted, email_from, created_by_id, version, research_mode, organisation_type, prefix_sms, crown, rate_limit, contact_link, consent_to_research, volume_email, volume_letter, volume_sms, count_as_live, go_live_at, go_live_user_id, organisation_id, sending_domain, default_branding_is_french, sms_daily_limit, organisation_notes, sensitive_service, email_annual_limit, sms_annual_limit, suspended_by_id, suspended_at
FROM services
WHERE id = $1
    AND (
        NOT $2::boolean
        OR active = true
    )
`

type GetServiceByIDParams struct {
	ID         uuid.UUID `json:"id"`
	OnlyActive bool      `json:"only_active"`
}

func (q *Queries) GetServiceByID(ctx context.Context, arg GetServiceByIDParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceByID, arg.ID, arg.OnlyActive)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.MessageLimit,
		&i.Restricted,
		&i.EmailFrom,
		&i.CreatedByID,
		&i.Version,
		&i.ResearchMode,
		&i.OrganisationType,
		&i.PrefixSms,
		&i.Crown,
		&i.RateLimit,
		&i.ContactLink,
		&i.ConsentToResearch,
		&i.VolumeEmail,
		&i.VolumeLetter,
		&i.VolumeSms,
		&i.CountAsLive,
		&i.GoLiveAt,
		&i.GoLiveUserID,
		&i.OrganisationID,
		&i.SendingDomain,
		&i.DefaultBrandingIsFrench,
		&i.SmsDailyLimit,
		&i.OrganisationNotes,
		&i.SensitiveService,
		&i.EmailAnnualLimit,
		&i.SmsAnnualLimit,
		&i.SuspendedByID,
		&i.SuspendedAt,
	)
	return i, err
}

const getServiceByIDAndUser = `-- name: GetServiceByIDAndUser :one
SELECT s.id, s.name, s.created_at, s.updated_at, s.active, s.message_limit, s.restricted, s.email_from, s.created_by_id, s.version, s.research_mode, s.organisation_type, s.prefix_sms, s.crown, s.rate_limit, s.contact_link, s.consent_to_research, s.volume_email, s.volume_letter, s.volume_sms, s.count_as_live, s.go_live_at, s.go_live_user_id, s.organisation_id, s.sending_domain, s.default_branding_is_french, s.sms_daily_limit, s.organisation_notes, s.sensitive_service, s.email_annual_limit, s.sms_annual_limit, s.suspended_by_id, s.suspended_at
FROM services AS s
    JOIN user_to_service AS uts ON uts.service_id = s.id
WHERE s.id = $1
    AND uts.user_id = $2
`

type GetServiceByIDAndUserParams struct {
	ServiceID uuid.UUID     `json:"service_id"`
	UserID    uuid.NullUUID `json:"user_id"`
}

func (q *Queries) GetServiceByIDAndUser(ctx context.Context, arg GetServiceByIDAndUserParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceByIDAndUser, arg.ServiceID, arg.UserID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.MessageLimit,
		&i.Restricted,
		&i.EmailFrom,
		&i.CreatedByID,
		&i.Version,
		&i.ResearchMode,
		&i.OrganisationType,
		&i.PrefixSms,
		&i.Crown,
		&i.RateLimit,
		&i.ContactLink,
		&i.ConsentToResearch,
		&i.VolumeEmail,
		&i.VolumeLetter,
		&i.VolumeSms,
		&i.CountAsLive,
		&i.GoLiveAt,
		&i.GoLiveUserID,
		&i.OrganisationID,
		&i.SendingDomain,
		&i.DefaultBrandingIsFrench,
		&i.SmsDailyLimit,
		&i.OrganisationNotes,
		&i.SensitiveService,
		&i.EmailAnnualLimit,
		&i.SmsAnnualLimit,
		&i.SuspendedByID,
		&i.SuspendedAt,
	)
	return i, err
}

const getServiceByIDWithAPIKeys = `-- name: GetServiceByIDWithAPIKeys :one
SELECT s.id, s.name, s.created_at, s.updated_at, s.active, s.message_limit, s.restricted, s.email_from, s.created_by_id, s.version, s.research_mode, s.organisation_type, s.prefix_sms, s.crown, s.rate_limit, s.contact_link, s.consent_to_research, s.volume_email, s.volume_letter, s.volume_sms, s.count_as_live, s.go_live_at, s.go_live_user_id, s.organisation_id, s.sending_domain, s.default_branding_is_french, s.sms_daily_limit, s.organisation_notes, s.sensitive_service, s.email_annual_limit, s.sms_annual_limit, s.suspended_by_id, s.suspended_at
FROM services AS s
WHERE s.id = $1
`

func (q *Queries) GetServiceByIDWithAPIKeys(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceByIDWithAPIKeys, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.MessageLimit,
		&i.Restricted,
		&i.EmailFrom,
		&i.CreatedByID,
		&i.Version,
		&i.ResearchMode,
		&i.OrganisationType,
		&i.PrefixSms,
		&i.Crown,
		&i.RateLimit,
		&i.ContactLink,
		&i.ConsentToResearch,
		&i.VolumeEmail,
		&i.VolumeLetter,
		&i.VolumeSms,
		&i.CountAsLive,
		&i.GoLiveAt,
		&i.GoLiveUserID,
		&i.OrganisationID,
		&i.SendingDomain,
		&i.DefaultBrandingIsFrench,
		&i.SmsDailyLimit,
		&i.OrganisationNotes,
		&i.SensitiveService,
		&i.EmailAnnualLimit,
		&i.SmsAnnualLimit,
		&i.SuspendedByID,
		&i.SuspendedAt,
	)
	return i, err
}

const getServiceByInboundNumber = `-- name: GetServiceByInboundNumber :one
SELECT s.id, s.name, s.created_at, s.updated_at, s.active, s.message_limit, s.restricted, s.email_from, s.created_by_id, s.version, s.research_mode, s.organisation_type, s.prefix_sms, s.crown, s.rate_limit, s.contact_link, s.consent_to_research, s.volume_email, s.volume_letter, s.volume_sms, s.count_as_live, s.go_live_at, s.go_live_user_id, s.organisation_id, s.sending_domain, s.default_branding_is_french, s.sms_daily_limit, s.organisation_notes, s.sensitive_service, s.email_annual_limit, s.sms_annual_limit, s.suspended_by_id, s.suspended_at
FROM services AS s
    JOIN inbound_numbers AS i ON i.service_id = s.id
WHERE i.number = $1
    AND i.active = true
`

func (q *Queries) GetServiceByInboundNumber(ctx context.Context, number string) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceByInboundNumber, number)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.MessageLimit,
		&i.Restricted,
		&i.EmailFrom,
		&i.CreatedByID,
		&i.Version,
		&i.ResearchMode,
		&i.OrganisationType,
		&i.PrefixSms,
		&i.Crown,
		&i.RateLimit,
		&i.ContactLink,
		&i.ConsentToResearch,
		&i.VolumeEmail,
		&i.VolumeLetter,
		&i.VolumeSms,
		&i.CountAsLive,
		&i.GoLiveAt,
		&i.GoLiveUserID,
		&i.OrganisationID,
		&i.SendingDomain,
		&i.DefaultBrandingIsFrench,
		&i.SmsDailyLimit,
		&i.OrganisationNotes,
		&i.SensitiveService,
		&i.EmailAnnualLimit,
		&i.SmsAnnualLimit,
		&i.SuspendedByID,
		&i.SuspendedAt,
	)
	return i, err
}

const getServicePermissions = `-- name: GetServicePermissions :many
SELECT permission
FROM service_permissions
WHERE service_id = $1
ORDER BY permission ASC
`

func (q *Queries) GetServicePermissions(ctx context.Context, serviceID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getServicePermissions, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServicesByPartialName = `-- name: GetServicesByPartialName :many
SELECT id, name, created_at, updated_at, active, message_limit, restricted, email_from, created_by_id, version, research_mode, organisation_type, prefix_sms, crown, rate_limit, contact_link, consent_to_research, volume_email, volume_letter, volume_sms, count_as_live, go_live_at, go_live_user_id, organisation_id, sending_domain, default_branding_is_french, sms_daily_limit, organisation_notes, sensitive_service, email_annual_limit, sms_annual_limit, suspended_by_id, suspended_at
FROM services
WHERE name ILIKE '%' || $1 || '%'
ORDER BY name ASC
`

func (q *Queries) GetServicesByPartialName(ctx context.Context, nameQuery sql.NullString) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getServicesByPartialName, nameQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Active,
			&i.MessageLimit,
			&i.Restricted,
			&i.EmailFrom,
			&i.CreatedByID,
			&i.Version,
			&i.ResearchMode,
			&i.OrganisationType,
			&i.PrefixSms,
			&i.Crown,
			&i.RateLimit,
			&i.ContactLink,
			&i.ConsentToResearch,
			&i.VolumeEmail,
			&i.VolumeLetter,
			&i.VolumeSms,
			&i.CountAsLive,
			&i.GoLiveAt,
			&i.GoLiveUserID,
			&i.OrganisationID,
			&i.SendingDomain,
			&i.DefaultBrandingIsFrench,
			&i.SmsDailyLimit,
			&i.OrganisationNotes,
			&i.SensitiveService,
			&i.EmailAnnualLimit,
			&i.SmsAnnualLimit,
			&i.SuspendedByID,
			&i.SuspendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServicesByUserID = `-- name: GetServicesByUserID :many
SELECT s.id, s.name, s.created_at, s.updated_at, s.active, s.message_limit, s.restricted, s.email_from, s.created_by_id, s.version, s.research_mode, s.organisation_type, s.prefix_sms, s.crown, s.rate_limit, s.contact_link, s.consent_to_research, s.volume_email, s.volume_letter, s.volume_sms, s.count_as_live, s.go_live_at, s.go_live_user_id, s.organisation_id, s.sending_domain, s.default_branding_is_french, s.sms_daily_limit, s.organisation_notes, s.sensitive_service, s.email_annual_limit, s.sms_annual_limit, s.suspended_by_id, s.suspended_at
FROM services AS s
    JOIN user_to_service AS uts ON uts.service_id = s.id
WHERE uts.user_id = $1
    AND (
        NOT $2::boolean
        OR s.active = true
    )
ORDER BY s.name ASC
`

type GetServicesByUserIDParams struct {
	UserID     uuid.NullUUID `json:"user_id"`
	OnlyActive bool          `json:"only_active"`
}

func (q *Queries) GetServicesByUserID(ctx context.Context, arg GetServicesByUserIDParams) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getServicesByUserID, arg.UserID, arg.OnlyActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Active,
			&i.MessageLimit,
			&i.Restricted,
			&i.EmailFrom,
			&i.CreatedByID,
			&i.Version,
			&i.ResearchMode,
			&i.OrganisationType,
			&i.PrefixSms,
			&i.Crown,
			&i.RateLimit,
			&i.ContactLink,
			&i.ConsentToResearch,
			&i.VolumeEmail,
			&i.VolumeLetter,
			&i.VolumeSms,
			&i.CountAsLive,
			&i.GoLiveAt,
			&i.GoLiveUserID,
			&i.OrganisationID,
			&i.SendingDomain,
			&i.DefaultBrandingIsFrench,
			&i.SmsDailyLimit,
			&i.OrganisationNotes,
			&i.SensitiveService,
			&i.EmailAnnualLimit,
			&i.SmsAnnualLimit,
			&i.SuspendedByID,
			&i.SuspendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertServicesHistoryRow = `-- name: InsertServicesHistoryRow :exec
INSERT INTO services_history (
        id,
        name,
        created_at,
        updated_at,
        active,
        message_limit,
        restricted,
        email_from,
        created_by_id,
        version,
        research_mode,
        organisation_type,
        prefix_sms,
        crown,
        rate_limit,
        contact_link,
        consent_to_research,
        volume_email,
        volume_letter,
        volume_sms,
        count_as_live,
        go_live_at,
        go_live_user_id,
        organisation_id,
        sending_domain,
        default_branding_is_french,
        sms_daily_limit,
        organisation_notes,
        sensitive_service,
        email_annual_limit,
        sms_annual_limit,
        suspended_by_id,
        suspended_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32,
        $33
    )
`

type InsertServicesHistoryRowParams struct {
	ID                      uuid.UUID      `json:"id"`
	Name                    string         `json:"name"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               sql.NullTime   `json:"updated_at"`
	Active                  bool           `json:"active"`
	MessageLimit            int64          `json:"message_limit"`
	Restricted              bool           `json:"restricted"`
	EmailFrom               string         `json:"email_from"`
	CreatedByID             uuid.UUID      `json:"created_by_id"`
	Version                 int32          `json:"version"`
	ResearchMode            bool           `json:"research_mode"`
	OrganisationType        sql.NullString `json:"organisation_type"`
	PrefixSms               sql.NullBool   `json:"prefix_sms"`
	Crown                   sql.NullBool   `json:"crown"`
	RateLimit               int32          `json:"rate_limit"`
	ContactLink             sql.NullString `json:"contact_link"`
	ConsentToResearch       sql.NullBool   `json:"consent_to_research"`
	VolumeEmail             sql.NullInt32  `json:"volume_email"`
	VolumeLetter            sql.NullInt32  `json:"volume_letter"`
	VolumeSms               sql.NullInt32  `json:"volume_sms"`
	CountAsLive             bool           `json:"count_as_live"`
	GoLiveAt                sql.NullTime   `json:"go_live_at"`
	GoLiveUserID            uuid.NullUUID  `json:"go_live_user_id"`
	OrganisationID          uuid.NullUUID  `json:"organisation_id"`
	SendingDomain           sql.NullString `json:"sending_domain"`
	DefaultBrandingIsFrench sql.NullBool   `json:"default_branding_is_french"`
	SmsDailyLimit           int64          `json:"sms_daily_limit"`
	OrganisationNotes       sql.NullString `json:"organisation_notes"`
	SensitiveService        sql.NullBool   `json:"sensitive_service"`
	EmailAnnualLimit        int64          `json:"email_annual_limit"`
	SmsAnnualLimit          int64          `json:"sms_annual_limit"`
	SuspendedByID           uuid.NullUUID  `json:"suspended_by_id"`
	SuspendedAt             sql.NullTime   `json:"suspended_at"`
}

func (q *Queries) InsertServicesHistoryRow(ctx context.Context, arg InsertServicesHistoryRowParams) error {
	_, err := q.db.ExecContext(ctx, insertServicesHistoryRow,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Active,
		arg.MessageLimit,
		arg.Restricted,
		arg.EmailFrom,
		arg.CreatedByID,
		arg.Version,
		arg.ResearchMode,
		arg.OrganisationType,
		arg.PrefixSms,
		arg.Crown,
		arg.RateLimit,
		arg.ContactLink,
		arg.ConsentToResearch,
		arg.VolumeEmail,
		arg.VolumeLetter,
		arg.VolumeSms,
		arg.CountAsLive,
		arg.GoLiveAt,
		arg.GoLiveUserID,
		arg.OrganisationID,
		arg.SendingDomain,
		arg.DefaultBrandingIsFrench,
		arg.SmsDailyLimit,
		arg.OrganisationNotes,
		arg.SensitiveService,
		arg.EmailAnnualLimit,
		arg.SmsAnnualLimit,
		arg.SuspendedByID,
		arg.SuspendedAt,
	)
	return err
}

const removeUserFromService = `-- name: RemoveUserFromService :execrows
DELETE FROM user_to_service
WHERE user_id = $1
    AND service_id = $2
`

type RemoveUserFromServiceParams struct {
	UserID    uuid.NullUUID `json:"user_id"`
	ServiceID uuid.NullUUID `json:"service_id"`
}

func (q *Queries) RemoveUserFromService(ctx context.Context, arg RemoveUserFromServiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeUserFromService, arg.UserID, arg.ServiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resumeService = `-- name: ResumeService :one
UPDATE services
SET suspended_at = NULL,
    suspended_by_id = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, name, created_at, updated_at, active, message_limit, restricted, email_from, created_by_id, version, research_mode, organisation_type, prefix_sms, crown, rate_limit, contact_link, consent_to_research, volume_email, volume_letter, volume_sms, count_as_live, go_live_at, go_live_user_id, organisation_id, sending_domain, default_branding_is_french, sms_daily_limit, organisation_notes, sensitive_service, email_annual_limit, sms_annual_limit, suspended_by_id, suspended_at
`

func (q *Queries) ResumeService(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRowContext(ctx, resumeService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.MessageLimit,
		&i.Restricted,
		&i.EmailFrom,
		&i.CreatedByID,
		&i.Version,
		&i.ResearchMode,
		&i.OrganisationType,
		&i.PrefixSms,
		&i.Crown,
		&i.RateLimit,
		&i.ContactLink,
		&i.ConsentToResearch,
		&i.VolumeEmail,
		&i.VolumeLetter,
		&i.VolumeSms,
		&i.CountAsLive,
		&i.GoLiveAt,
		&i.GoLiveUserID,
		&i.OrganisationID,
		&i.SendingDomain,
		&i.DefaultBrandingIsFrench,
		&i.SmsDailyLimit,
		&i.OrganisationNotes,
		&i.SensitiveService,
		&i.EmailAnnualLimit,
		&i.SmsAnnualLimit,
		&i.SuspendedByID,
		&i.SuspendedAt,
	)
	return i, err
}

const setServicePermissions = `-- name: SetServicePermissions :exec
WITH deleted AS (
    DELETE FROM service_permissions
    WHERE service_id = $1
)
INSERT INTO service_permissions (service_id, permission, created_at)
SELECT $1,
    permission,
    now()
FROM unnest($2::text []) AS permission
`

type SetServicePermissionsParams struct {
	ServiceID   uuid.UUID `json:"service_id"`
	Permissions []string  `json:"permissions"`
}

func (q *Queries) SetServicePermissions(ctx context.Context, arg SetServicePermissionsParams) error {
	_, err := q.db.ExecContext(ctx, setServicePermissions, arg.ServiceID, pq.Array(arg.Permissions))
	return err
}

const suspendService = `-- name: SuspendService :one
UPDATE services
SET suspended_at = now(),
    suspended_by_id = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, name, created_at, updated_at, active, message_limit, restricted, email_from, created_by_id, version, research_mode, organisation_type, prefix_sms, crown, rate_limit, contact_link, consent_to_research, volume_email, volume_letter, volume_sms, count_as_live, go_live_at, go_live_user_id, organisation_id, sending_domain, default_branding_is_french, sms_daily_limit, organisation_notes, sensitive_service, email_annual_limit, sms_annual_limit, suspended_by_id, suspended_at
`

type SuspendServiceParams struct {
	SuspendedByID uuid.NullUUID `json:"suspended_by_id"`
	ID            uuid.UUID     `json:"id"`
}

func (q *Queries) SuspendService(ctx context.Context, arg SuspendServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, suspendService, arg.SuspendedByID, arg.ID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.MessageLimit,
		&i.Restricted,
		&i.EmailFrom,
		&i.CreatedByID,
		&i.Version,
		&i.ResearchMode,
		&i.OrganisationType,
		&i.PrefixSms,
		&i.Crown,
		&i.RateLimit,
		&i.ContactLink,
		&i.ConsentToResearch,
		&i.VolumeEmail,
		&i.VolumeLetter,
		&i.VolumeSms,
		&i.CountAsLive,
		&i.GoLiveAt,
		&i.GoLiveUserID,
		&i.OrganisationID,
		&i.SendingDomain,
		&i.DefaultBrandingIsFrench,
		&i.SmsDailyLimit,
		&i.OrganisationNotes,
		&i.SensitiveService,
		&i.EmailAnnualLimit,
		&i.SmsAnnualLimit,
		&i.SuspendedByID,
		&i.SuspendedAt,
	)
	return i, err
}

const updateEmailReplyTo = `-- name: UpdateEmailReplyTo :one
UPDATE service_email_reply_to
SET email_address = $1,
    is_default = $2,
    updated_at = now(),
    archived = $3
WHERE id = $4
RETURNING id, service_id, email_address, is_default, created_at, updated_at, archived
`

type UpdateEmailReplyToParams struct {
	EmailAddress string    `json:"email_address"`
	IsDefault    bool      `json:"is_default"`
	Archived     bool      `json:"archived"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateEmailReplyTo(ctx context.Context, arg UpdateEmailReplyToParams) (ServiceEmailReplyTo, error) {
	row := q.db.QueryRowContext(ctx, updateEmailReplyTo,
		arg.EmailAddress,
		arg.IsDefault,
		arg.Archived,
		arg.ID,
	)
	var i ServiceEmailReplyTo
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.EmailAddress,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const updateSMSSender = `-- name: UpdateSMSSender :one
UPDATE service_sms_senders
SET sms_sender = $1,
    is_default = $2,
    inbound_number_id = $3,
    updated_at = now(),
    archived = $4
WHERE id = $5
RETURNING id, sms_sender, service_id, is_default, inbound_number_id, created_at, updated_at, archived
`

type UpdateSMSSenderParams struct {
	SmsSender       string        `json:"sms_sender"`
	IsDefault       bool          `json:"is_default"`
	InboundNumberID uuid.NullUUID `json:"inbound_number_id"`
	Archived        bool          `json:"archived"`
	ID              uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateSMSSender(ctx context.Context, arg UpdateSMSSenderParams) (ServiceSmsSender, error) {
	row := q.db.QueryRowContext(ctx, updateSMSSender,
		arg.SmsSender,
		arg.IsDefault,
		arg.InboundNumberID,
		arg.Archived,
		arg.ID,
	)
	var i ServiceSmsSender
	err := row.Scan(
		&i.ID,
		&i.SmsSender,
		&i.ServiceID,
		&i.IsDefault,
		&i.InboundNumberID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const updateSafelist = `-- name: UpdateSafelist :exec
WITH deleted AS (
    DELETE FROM service_safelist AS ss
    WHERE ss.service_id = $1
),
email_rows AS (
    SELECT x
    FROM jsonb_to_recordset($2::jsonb) AS x(id uuid, recipient text)
),
inserted_emails AS (
    INSERT INTO service_safelist (
            id,
            service_id,
            recipient_type,
            recipient,
            created_at
        )
    SELECT id,
        $1,
        'email'::public.recipient_type,
        recipient,
        now()
    FROM email_rows
),
phone_rows AS (
    SELECT x
    FROM jsonb_to_recordset($3::jsonb) AS x(id uuid, recipient text)
),
inserted_phones AS (
    INSERT INTO service_safelist (
            id,
            service_id,
            recipient_type,
            recipient,
            created_at
        )
    SELECT id,
        $1,
        'mobile'::public.recipient_type,
        recipient,
        now()
    FROM phone_rows
)
SELECT 1
`

type UpdateSafelistParams struct {
	TargetServiceID uuid.UUID       `json:"target_service_id"`
	EmailItems      json.RawMessage `json:"email_items"`
	PhoneItems      json.RawMessage `json:"phone_items"`
}

func (q *Queries) UpdateSafelist(ctx context.Context, arg UpdateSafelistParams) error {
	_, err := q.db.ExecContext(ctx, updateSafelist, arg.TargetServiceID, arg.EmailItems, arg.PhoneItems)
	return err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = $1,
    updated_at = $2,
    active = $3,
    message_limit = $4,
    restricted = $5,
    email_from = $6,
    version = $7,
    research_mode = $8,
    organisation_type = $9,
    prefix_sms = $10,
    crown = $11,
    rate_limit = $12,
    contact_link = $13,
    consent_to_research = $14,
    volume_email = $15,
    volume_letter = $16,
    volume_sms = $17,
    count_as_live = $18,
    go_live_at = $19,
    go_live_user_id = $20,
    organisation_id = $21,
    sending_domain = $22,
    default_branding_is_french = $23,
    sms_daily_limit = $24,
    organisation_notes = $25,
    sensitive_service = $26,
    email_annual_limit = $27,
    sms_annual_limit = $28,
    suspended_by_id = $29,
    suspended_at = $30
WHERE id = $31
RETURNING id, name, created_at, updated_at, active, message_limit, restricted, email_from, created_by_id, version, research_mode, organisation_type, prefix_sms, crown, rate_limit, contact_link, consent_to_research, volume_email, volume_letter, volume_sms, count_as_live, go_live_at, go_live_user_id, organisation_id, sending_domain, default_branding_is_french, sms_daily_limit, organisation_notes, sensitive_service, email_annual_limit, sms_annual_limit, suspended_by_id, suspended_at
`

type UpdateServiceParams struct {
	Name                    string         `json:"name"`
	UpdatedAt               sql.NullTime   `json:"updated_at"`
	Active                  bool           `json:"active"`
	MessageLimit            int64          `json:"message_limit"`
	Restricted              bool           `json:"restricted"`
	EmailFrom               string         `json:"email_from"`
	Version                 int32          `json:"version"`
	ResearchMode            bool           `json:"research_mode"`
	OrganisationType        sql.NullString `json:"organisation_type"`
	PrefixSms               bool           `json:"prefix_sms"`
	Crown                   sql.NullBool   `json:"crown"`
	RateLimit               int32          `json:"rate_limit"`
	ContactLink             sql.NullString `json:"contact_link"`
	ConsentToResearch       sql.NullBool   `json:"consent_to_research"`
	VolumeEmail             sql.NullInt32  `json:"volume_email"`
	VolumeLetter            sql.NullInt32  `json:"volume_letter"`
	VolumeSms               sql.NullInt32  `json:"volume_sms"`
	CountAsLive             bool           `json:"count_as_live"`
	GoLiveAt                sql.NullTime   `json:"go_live_at"`
	GoLiveUserID            uuid.NullUUID  `json:"go_live_user_id"`
	OrganisationID          uuid.NullUUID  `json:"organisation_id"`
	SendingDomain           sql.NullString `json:"sending_domain"`
	DefaultBrandingIsFrench sql.NullBool   `json:"default_branding_is_french"`
	SmsDailyLimit           int64          `json:"sms_daily_limit"`
	OrganisationNotes       sql.NullString `json:"organisation_notes"`
	SensitiveService        sql.NullBool   `json:"sensitive_service"`
	EmailAnnualLimit        int64          `json:"email_annual_limit"`
	SmsAnnualLimit          int64          `json:"sms_annual_limit"`
	SuspendedByID           uuid.NullUUID  `json:"suspended_by_id"`
	SuspendedAt             sql.NullTime   `json:"suspended_at"`
	ID                      uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, updateService,
		arg.Name,
		arg.UpdatedAt,
		arg.Active,
		arg.MessageLimit,
		arg.Restricted,
		arg.EmailFrom,
		arg.Version,
		arg.ResearchMode,
		arg.OrganisationType,
		arg.PrefixSms,
		arg.Crown,
		arg.RateLimit,
		arg.ContactLink,
		arg.ConsentToResearch,
		arg.VolumeEmail,
		arg.VolumeLetter,
		arg.VolumeSms,
		arg.CountAsLive,
		arg.GoLiveAt,
		arg.GoLiveUserID,
		arg.OrganisationID,
		arg.SendingDomain,
		arg.DefaultBrandingIsFrench,
		arg.SmsDailyLimit,
		arg.OrganisationNotes,
		arg.SensitiveService,
		arg.EmailAnnualLimit,
		arg.SmsAnnualLimit,
		arg.SuspendedByID,
		arg.SuspendedAt,
		arg.ID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.MessageLimit,
		&i.Restricted,
		&i.EmailFrom,
		&i.CreatedByID,
		&i.Version,
		&i.ResearchMode,
		&i.OrganisationType,
		&i.PrefixSms,
		&i.Crown,
		&i.RateLimit,
		&i.ContactLink,
		&i.ConsentToResearch,
		&i.VolumeEmail,
		&i.VolumeLetter,
		&i.VolumeSms,
		&i.CountAsLive,
		&i.GoLiveAt,
		&i.GoLiveUserID,
		&i.OrganisationID,
		&i.SendingDomain,
		&i.DefaultBrandingIsFrench,
		&i.SmsDailyLimit,
		&i.OrganisationNotes,
		&i.SensitiveService,
		&i.EmailAnnualLimit,
		&i.SmsAnnualLimit,
		&i.SuspendedByID,
		&i.SuspendedAt,
	)
	return i, err
}

const upsertCallbackAPI = `-- name: UpsertCallbackAPI :one
WITH updated AS (
    UPDATE service_callback_api
    SET url = $3,
        bearer_token = $4,
        updated_at = $6,
        updated_by_id = $7,
        version = $8,
        is_suspended = $10,
        suspended_at = $11
    WHERE service_id = $2
        AND callback_type IS NOT DISTINCT
    FROM $9
    RETURNING id, service_id, url, bearer_token, created_at, updated_at, updated_by_id, version, callback_type, is_suspended, suspended_at
)
INSERT INTO service_callback_api (
        id,
        service_id,
        url,
        bearer_token,
        created_at,
        updated_at,
        updated_by_id,
        version,
        callback_type,
        is_suspended,
        suspended_at
    )
SELECT $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
WHERE NOT EXISTS (
        SELECT 1
        FROM updated
    )
RETURNING id, service_id, url, bearer_token, created_at, updated_at, updated_by_id, version, callback_type, is_suspended, suspended_at
`

type UpsertCallbackAPIParams struct {
	ID           uuid.UUID      `json:"id"`
	ServiceID    uuid.UUID      `json:"service_id"`
	Url          string         `json:"url"`
	BearerToken  string         `json:"bearer_token"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	UpdatedByID  uuid.UUID      `json:"updated_by_id"`
	Version      int32          `json:"version"`
	CallbackType sql.NullString `json:"callback_type"`
	IsSuspended  sql.NullBool   `json:"is_suspended"`
	SuspendedAt  sql.NullTime   `json:"suspended_at"`
}

func (q *Queries) UpsertCallbackAPI(ctx context.Context, arg UpsertCallbackAPIParams) (ServiceCallbackApi, error) {
	row := q.db.QueryRowContext(ctx, upsertCallbackAPI,
		arg.ID,
		arg.ServiceID,
		arg.Url,
		arg.BearerToken,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UpdatedByID,
		arg.Version,
		arg.CallbackType,
		arg.IsSuspended,
		arg.SuspendedAt,
	)
	var i ServiceCallbackApi
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Url,
		&i.BearerToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByID,
		&i.Version,
		&i.CallbackType,
		&i.IsSuspended,
		&i.SuspendedAt,
	)
	return i, err
}

const upsertDataRetention = `-- name: UpsertDataRetention :one
WITH updated AS (
    UPDATE service_data_retention
    SET days_of_retention = $4,
        updated_at = now()
    WHERE service_id = $2
        AND notification_type = $3
    RETURNING id, service_id, notification_type, days_of_retention, created_at, updated_at
)
INSERT INTO service_data_retention (
        id,
        service_id,
        notification_type,
        days_of_retention,
        created_at,
        updated_at
    )
SELECT $1,
    $2,
    $3,
    $4,
    $5,
    $6
WHERE NOT EXISTS (
        SELECT 1
        FROM updated
    )
RETURNING id, service_id, notification_type, days_of_retention, created_at, updated_at
`

type UpsertDataRetentionParams struct {
	ID               uuid.UUID        `json:"id"`
	ServiceID        uuid.UUID        `json:"service_id"`
	NotificationType NotificationType `json:"notification_type"`
	DaysOfRetention  int32            `json:"days_of_retention"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        sql.NullTime     `json:"updated_at"`
}

func (q *Queries) UpsertDataRetention(ctx context.Context, arg UpsertDataRetentionParams) (ServiceDataRetention, error) {
	row := q.db.QueryRowContext(ctx, upsertDataRetention,
		arg.ID,
		arg.ServiceID,
		arg.NotificationType,
		arg.DaysOfRetention,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ServiceDataRetention
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.NotificationType,
		&i.DaysOfRetention,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInboundAPI = `-- name: UpsertInboundAPI :one
WITH updated AS (
    UPDATE service_inbound_api
    SET url = $3,
        bearer_token = $4,
        updated_at = $6,
        updated_by_id = $7,
        version = $8
    WHERE service_id = $2
    RETURNING id, service_id, url, bearer_token, created_at, updated_at, updated_by_id, version
)
INSERT INTO service_inbound_api (
        id,
        service_id,
        url,
        bearer_token,
        created_at,
        updated_at,
        updated_by_id,
        version
    )
SELECT $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
WHERE NOT EXISTS (
        SELECT 1
        FROM updated
    )
RETURNING id, service_id, url, bearer_token, created_at, updated_at, updated_by_id, version
`

type UpsertInboundAPIParams struct {
	ID          uuid.UUID    `json:"id"`
	ServiceID   uuid.UUID    `json:"service_id"`
	Url         string       `json:"url"`
	BearerToken string       `json:"bearer_token"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	UpdatedByID uuid.UUID    `json:"updated_by_id"`
	Version     int32        `json:"version"`
}

func (q *Queries) UpsertInboundAPI(ctx context.Context, arg UpsertInboundAPIParams) (ServiceInboundApi, error) {
	row := q.db.QueryRowContext(ctx, upsertInboundAPI,
		arg.ID,
		arg.ServiceID,
		arg.Url,
		arg.BearerToken,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UpdatedByID,
		arg.Version,
	)
	var i ServiceInboundApi
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Url,
		&i.BearerToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByID,
		&i.Version,
	)
	return i, err
}
