// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package templates

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const archiveTemplate = `-- name: ArchiveTemplate :one
UPDATE templates
SET archived = true,
    updated_at = now()
WHERE id = $1
RETURNING id, name, template_type, created_at, updated_at, content, service_id, subject, created_by_id, version, archived, process_type, service_letter_contact_id, hidden, postage, template_category_id, text_direction_rtl
`

func (q *Queries) ArchiveTemplate(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRowContext(ctx, archiveTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TemplateType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Content,
		&i.ServiceID,
		&i.Subject,
		&i.CreatedByID,
		&i.Version,
		&i.Archived,
		&i.ProcessType,
		&i.ServiceLetterContactID,
		&i.Hidden,
		&i.Postage,
		&i.TemplateCategoryID,
		&i.TextDirectionRtl,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (
        id,
        name,
        template_type,
        created_at,
        updated_at,
        content,
        service_id,
        subject,
        created_by_id,
        version,
        archived,
        process_type,
        service_letter_contact_id,
        hidden,
        postage,
        template_category_id,
        text_direction_rtl
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17
    )
RETURNING id, name, template_type, created_at, updated_at, content, service_id, subject, created_by_id, version, archived, process_type, service_letter_contact_id, hidden, postage, template_category_id, text_direction_rtl
`

type CreateTemplateParams struct {
	ID                     uuid.UUID      `json:"id"`
	Name                   string         `json:"name"`
	TemplateType           TemplateType   `json:"template_type"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
	Content                string         `json:"content"`
	ServiceID              uuid.UUID      `json:"service_id"`
	Subject                sql.NullString `json:"subject"`
	CreatedByID            uuid.UUID      `json:"created_by_id"`
	Version                int32          `json:"version"`
	Archived               bool           `json:"archived"`
	ProcessType            sql.NullString `json:"process_type"`
	ServiceLetterContactID uuid.NullUUID  `json:"service_letter_contact_id"`
	Hidden                 bool           `json:"hidden"`
	Postage                sql.NullString `json:"postage"`
	TemplateCategoryID     uuid.NullUUID  `json:"template_category_id"`
	TextDirectionRtl       bool           `json:"text_direction_rtl"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, createTemplate,
		arg.ID,
		arg.Name,
		arg.TemplateType,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Content,
		arg.ServiceID,
		arg.Subject,
		arg.CreatedByID,
		arg.Version,
		arg.Archived,
		arg.ProcessType,
		arg.ServiceLetterContactID,
		arg.Hidden,
		arg.Postage,
		arg.TemplateCategoryID,
		arg.TextDirectionRtl,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TemplateType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Content,
		&i.ServiceID,
		&i.Subject,
		&i.CreatedByID,
		&i.Version,
		&i.Archived,
		&i.ProcessType,
		&i.ServiceLetterContactID,
		&i.Hidden,
		&i.Postage,
		&i.TemplateCategoryID,
		&i.TextDirectionRtl,
	)
	return i, err
}

const createTemplateFolder = `-- name: CreateTemplateFolder :one
INSERT INTO template_folder (
        id,
        service_id,
        name,
        parent_id
    )
VALUES (
        $1,
        $2,
        $3,
        $4
    )
RETURNING id, service_id, name, parent_id
`

type CreateTemplateFolderParams struct {
	ID        uuid.UUID     `json:"id"`
	ServiceID uuid.UUID     `json:"service_id"`
	Name      string        `json:"name"`
	ParentID  uuid.NullUUID `json:"parent_id"`
}

func (q *Queries) CreateTemplateFolder(ctx context.Context, arg CreateTemplateFolderParams) (TemplateFolder, error) {
	row := q.db.QueryRowContext(ctx, createTemplateFolder,
		arg.ID,
		arg.ServiceID,
		arg.Name,
		arg.ParentID,
	)
	var i TemplateFolder
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.ParentID,
	)
	return i, err
}

const deleteTemplateFolder = `-- name: DeleteTemplateFolder :execrows
DELETE FROM template_folder
WHERE id = $1
`

func (q *Queries) DeleteTemplateFolder(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTemplateFolder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPrecompiledLetterTemplate = `-- name: GetPrecompiledLetterTemplate :one
SELECT id, name, template_type, created_at, updated_at, content, service_id, subject, created_by_id, version, archived, process_type, service_letter_contact_id, hidden, postage, template_category_id, text_direction_rtl
FROM templates
WHERE service_id = $1
    AND template_type = 'letter'
    AND archived = false
ORDER BY updated_at DESC NULLS LAST,
    created_at DESC
LIMIT 1
`

func (q *Queries) GetPrecompiledLetterTemplate(ctx context.Context, serviceID uuid.UUID) (Template, error) {
	row := q.db.QueryRowContext(ctx, getPrecompiledLetterTemplate, serviceID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TemplateType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Content,
		&i.ServiceID,
		&i.Subject,
		&i.CreatedByID,
		&i.Version,
		&i.Archived,
		&i.ProcessType,
		&i.ServiceLetterContactID,
		&i.Hidden,
		&i.Postage,
		&i.TemplateCategoryID,
		&i.TextDirectionRtl,
	)
	return i, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, name, template_type, created_at, updated_at, content, service_id, subject, created_by_id, version, archived, process_type, service_letter_contact_id, hidden, postage, template_category_id, text_direction_rtl
FROM templates
WHERE id = $1
    AND service_id = $2
`

type GetTemplateByIDParams struct {
	ID        uuid.UUID `json:"id"`
	ServiceID uuid.UUID `json:"service_id"`
}

func (q *Queries) GetTemplateByID(ctx context.Context, arg GetTemplateByIDParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByID, arg.ID, arg.ServiceID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TemplateType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Content,
		&i.ServiceID,
		&i.Subject,
		&i.CreatedByID,
		&i.Version,
		&i.Archived,
		&i.ProcessType,
		&i.ServiceLetterContactID,
		&i.Hidden,
		&i.Postage,
		&i.TemplateCategoryID,
		&i.TextDirectionRtl,
	)
	return i, err
}

const getTemplateByIDAndVersion = `-- name: GetTemplateByIDAndVersion :one
SELECT id, name, template_type, created_at, updated_at, content, service_id, subject, created_by_id, version, archived, process_type, service_letter_contact_id, hidden, postage, template_category_id, text_direction_rtl
FROM templates_history
WHERE id = $1
    AND version = $2
`

type GetTemplateByIDAndVersionParams struct {
	ID      uuid.UUID `json:"id"`
	Version int32     `json:"version"`
}

func (q *Queries) GetTemplateByIDAndVersion(ctx context.Context, arg GetTemplateByIDAndVersionParams) (TemplatesHistory, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByIDAndVersion, arg.ID, arg.Version)
	var i TemplatesHistory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TemplateType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Content,
		&i.ServiceID,
		&i.Subject,
		&i.CreatedByID,
		&i.Version,
		&i.Archived,
		&i.ProcessType,
		&i.ServiceLetterContactID,
		&i.Hidden,
		&i.Postage,
		&i.TemplateCategoryID,
		&i.TextDirectionRtl,
	)
	return i, err
}

const getTemplateFolders = `-- name: GetTemplateFolders :many
SELECT id, service_id, name, parent_id
FROM template_folder
WHERE service_id = $1
ORDER BY name ASC
`

func (q *Queries) GetTemplateFolders(ctx context.Context, serviceID uuid.UUID) ([]TemplateFolder, error) {
	rows, err := q.db.QueryContext(ctx, getTemplateFolders, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateFolder
	for rows.Next() {
		var i TemplateFolder
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateVersions = `-- name: GetTemplateVersions :many
SELECT id, name, template_type, created_at, updated_at, content, service_id, subject, created_by_id, version, archived, process_type, service_letter_contact_id, hidden, postage, template_category_id, text_direction_rtl
FROM templates_history
WHERE id = $1
ORDER BY version DESC
`

func (q *Queries) GetTemplateVersions(ctx context.Context, id uuid.UUID) ([]TemplatesHistory, error) {
	rows, err := q.db.QueryContext(ctx, getTemplateVersions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplatesHistory
	for rows.Next() {
		var i TemplatesHistory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TemplateType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Content,
			&i.ServiceID,
			&i.Subject,
			&i.CreatedByID,
			&i.Version,
			&i.Archived,
			&i.ProcessType,
			&i.ServiceLetterContactID,
			&i.Hidden,
			&i.Postage,
			&i.TemplateCategoryID,
			&i.TextDirectionRtl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplatesByServiceID = `-- name: GetTemplatesByServiceID :many
SELECT id, name, template_type, created_at, updated_at, content, service_id, subject, created_by_id, version, archived, process_type, service_letter_contact_id, hidden, postage, template_category_id, text_direction_rtl
FROM templates
WHERE service_id = $1
    AND archived = false
ORDER BY created_at DESC
`

func (q *Queries) GetTemplatesByServiceID(ctx context.Context, serviceID uuid.UUID) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, getTemplatesByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TemplateType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Content,
			&i.ServiceID,
			&i.Subject,
			&i.CreatedByID,
			&i.Version,
			&i.Archived,
			&i.ProcessType,
			&i.ServiceLetterContactID,
			&i.Hidden,
			&i.Postage,
			&i.TemplateCategoryID,
			&i.TextDirectionRtl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTemplateHistory = `-- name: InsertTemplateHistory :exec
INSERT INTO templates_history (
        id,
        name,
        template_type,
        created_at,
        updated_at,
        content,
        service_id,
        subject,
        created_by_id,
        version,
        archived,
        process_type,
        service_letter_contact_id,
        hidden,
        postage,
        template_category_id,
        text_direction_rtl
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17
    )
`

type InsertTemplateHistoryParams struct {
	ID                     uuid.UUID      `json:"id"`
	Name                   string         `json:"name"`
	TemplateType           TemplateType   `json:"template_type"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
	Content                string         `json:"content"`
	ServiceID              uuid.UUID      `json:"service_id"`
	Subject                sql.NullString `json:"subject"`
	CreatedByID            uuid.UUID      `json:"created_by_id"`
	Version                int32          `json:"version"`
	Archived               bool           `json:"archived"`
	ProcessType            sql.NullString `json:"process_type"`
	ServiceLetterContactID uuid.NullUUID  `json:"service_letter_contact_id"`
	Hidden                 bool           `json:"hidden"`
	Postage                sql.NullString `json:"postage"`
	TemplateCategoryID     uuid.NullUUID  `json:"template_category_id"`
	TextDirectionRtl       bool           `json:"text_direction_rtl"`
}

func (q *Queries) InsertTemplateHistory(ctx context.Context, arg InsertTemplateHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertTemplateHistory,
		arg.ID,
		arg.Name,
		arg.TemplateType,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Content,
		arg.ServiceID,
		arg.Subject,
		arg.CreatedByID,
		arg.Version,
		arg.Archived,
		arg.ProcessType,
		arg.ServiceLetterContactID,
		arg.Hidden,
		arg.Postage,
		arg.TemplateCategoryID,
		arg.TextDirectionRtl,
	)
	return err
}

const moveTemplateContents = `-- name: MoveTemplateContents :execrows
UPDATE template_folder_map
SET template_folder_id = $1
WHERE template_id = ANY($2::uuid [])
    OR template_folder_id = ANY($3::uuid [])
`

type MoveTemplateContentsParams struct {
	TargetFolderID uuid.NullUUID `json:"target_folder_id"`
	TemplateIds    []uuid.UUID   `json:"template_ids"`
	FolderIds      []uuid.UUID   `json:"folder_ids"`
}

func (q *Queries) MoveTemplateContents(ctx context.Context, arg MoveTemplateContentsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, moveTemplateContents, arg.TargetFolderID, pq.Array(arg.TemplateIds), pq.Array(arg.FolderIds))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET name = $1,
    updated_at = $2,
    content = $3,
    subject = $4,
    version = $5,
    archived = $6,
    process_type = $7,
    service_letter_contact_id = $8,
    hidden = $9,
    postage = $10,
    template_category_id = $11,
    text_direction_rtl = $12
WHERE id = $13
RETURNING id, name, template_type, created_at, updated_at, content, service_id, subject, created_by_id, version, archived, process_type, service_letter_contact_id, hidden, postage, template_category_id, text_direction_rtl
`

type UpdateTemplateParams struct {
	Name                   string         `json:"name"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
	Content                string         `json:"content"`
	Subject                sql.NullString `json:"subject"`
	Version                int32          `json:"version"`
	Archived               bool           `json:"archived"`
	ProcessType            sql.NullString `json:"process_type"`
	ServiceLetterContactID uuid.NullUUID  `json:"service_letter_contact_id"`
	Hidden                 bool           `json:"hidden"`
	Postage                sql.NullString `json:"postage"`
	TemplateCategoryID     uuid.NullUUID  `json:"template_category_id"`
	TextDirectionRtl       bool           `json:"text_direction_rtl"`
	ID                     uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, updateTemplate,
		arg.Name,
		arg.UpdatedAt,
		arg.Content,
		arg.Subject,
		arg.Version,
		arg.Archived,
		arg.ProcessType,
		arg.ServiceLetterContactID,
		arg.Hidden,
		arg.Postage,
		arg.TemplateCategoryID,
		arg.TextDirectionRtl,
		arg.ID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TemplateType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Content,
		&i.ServiceID,
		&i.Subject,
		&i.CreatedByID,
		&i.Version,
		&i.Archived,
		&i.ProcessType,
		&i.ServiceLetterContactID,
		&i.Hidden,
		&i.Postage,
		&i.TemplateCategoryID,
		&i.TextDirectionRtl,
	)
	return i, err
}

const updateTemplateFolder = `-- name: UpdateTemplateFolder :one
UPDATE template_folder
SET name = $1,
    parent_id = $2
WHERE id = $3
RETURNING id, service_id, name, parent_id
`

type UpdateTemplateFolderParams struct {
	Name     string        `json:"name"`
	ParentID uuid.NullUUID `json:"parent_id"`
	ID       uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateTemplateFolder(ctx context.Context, arg UpdateTemplateFolderParams) (TemplateFolder, error) {
	row := q.db.QueryRowContext(ctx, updateTemplateFolder, arg.Name, arg.ParentID, arg.ID)
	var i TemplateFolder
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.ParentID,
	)
	return i, err
}
