// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: template_categories.sql

package template_categories

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTemplateCategory = `-- name: CreateTemplateCategory :one
INSERT INTO template_categories (
        id,
        name_en,
        name_fr,
        description_en,
        description_fr,
        sms_process_type,
        email_process_type,
        hidden,
        created_at,
        updated_at,
        sms_sending_vehicle,
        created_by_id,
        updated_by_id
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13
    )
RETURNING id, name_en, name_fr, description_en, description_fr, sms_process_type, email_process_type, hidden, created_at, updated_at, sms_sending_vehicle, created_by_id, updated_by_id
`

type CreateTemplateCategoryParams struct {
	ID                uuid.UUID         `json:"id"`
	NameEn            string            `json:"name_en"`
	NameFr            string            `json:"name_fr"`
	DescriptionEn     sql.NullString    `json:"description_en"`
	DescriptionFr     sql.NullString    `json:"description_fr"`
	SmsProcessType    string            `json:"sms_process_type"`
	EmailProcessType  string            `json:"email_process_type"`
	Hidden            bool              `json:"hidden"`
	CreatedAt         sql.NullTime      `json:"created_at"`
	UpdatedAt         sql.NullTime      `json:"updated_at"`
	SmsSendingVehicle SmsSendingVehicle `json:"sms_sending_vehicle"`
	CreatedByID       uuid.UUID         `json:"created_by_id"`
	UpdatedByID       uuid.NullUUID     `json:"updated_by_id"`
}

func (q *Queries) CreateTemplateCategory(ctx context.Context, arg CreateTemplateCategoryParams) (TemplateCategory, error) {
	row := q.db.QueryRowContext(ctx, createTemplateCategory,
		arg.ID,
		arg.NameEn,
		arg.NameFr,
		arg.DescriptionEn,
		arg.DescriptionFr,
		arg.SmsProcessType,
		arg.EmailProcessType,
		arg.Hidden,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SmsSendingVehicle,
		arg.CreatedByID,
		arg.UpdatedByID,
	)
	var i TemplateCategory
	err := row.Scan(
		&i.ID,
		&i.NameEn,
		&i.NameFr,
		&i.DescriptionEn,
		&i.DescriptionFr,
		&i.SmsProcessType,
		&i.EmailProcessType,
		&i.Hidden,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SmsSendingVehicle,
		&i.CreatedByID,
		&i.UpdatedByID,
	)
	return i, err
}

const deleteTemplateCategory = `-- name: DeleteTemplateCategory :execrows
DELETE FROM template_categories
WHERE id = $1
`

func (q *Queries) DeleteTemplateCategory(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTemplateCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTemplateCategories = `-- name: GetTemplateCategories :many
SELECT id, name_en, name_fr, description_en, description_fr, sms_process_type, email_process_type, hidden, created_at, updated_at, sms_sending_vehicle, created_by_id, updated_by_id
FROM template_categories
WHERE (
        $1::boolean IS NULL
        OR hidden = $1::boolean
    )
ORDER BY name_en ASC
`

func (q *Queries) GetTemplateCategories(ctx context.Context, hidden sql.NullBool) ([]TemplateCategory, error) {
	rows, err := q.db.QueryContext(ctx, getTemplateCategories, hidden)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateCategory
	for rows.Next() {
		var i TemplateCategory
		if err := rows.Scan(
			&i.ID,
			&i.NameEn,
			&i.NameFr,
			&i.DescriptionEn,
			&i.DescriptionFr,
			&i.SmsProcessType,
			&i.EmailProcessType,
			&i.Hidden,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SmsSendingVehicle,
			&i.CreatedByID,
			&i.UpdatedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateCategoryByID = `-- name: GetTemplateCategoryByID :one
SELECT id, name_en, name_fr, description_en, description_fr, sms_process_type, email_process_type, hidden, created_at, updated_at, sms_sending_vehicle, created_by_id, updated_by_id
FROM template_categories
WHERE id = $1
`

func (q *Queries) GetTemplateCategoryByID(ctx context.Context, id uuid.UUID) (TemplateCategory, error) {
	row := q.db.QueryRowContext(ctx, getTemplateCategoryByID, id)
	var i TemplateCategory
	err := row.Scan(
		&i.ID,
		&i.NameEn,
		&i.NameFr,
		&i.DescriptionEn,
		&i.DescriptionFr,
		&i.SmsProcessType,
		&i.EmailProcessType,
		&i.Hidden,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SmsSendingVehicle,
		&i.CreatedByID,
		&i.UpdatedByID,
	)
	return i, err
}

const updateTemplateCategory = `-- name: UpdateTemplateCategory :one
UPDATE template_categories
SET name_en = $1,
    name_fr = $2,
    description_en = $3,
    description_fr = $4,
    sms_process_type = $5,
    email_process_type = $6,
    hidden = $7,
    updated_at = now(),
    sms_sending_vehicle = $8,
    updated_by_id = $9
WHERE id = $10
RETURNING id, name_en, name_fr, description_en, description_fr, sms_process_type, email_process_type, hidden, created_at, updated_at, sms_sending_vehicle, created_by_id, updated_by_id
`

type UpdateTemplateCategoryParams struct {
	NameEn            string            `json:"name_en"`
	NameFr            string            `json:"name_fr"`
	DescriptionEn     sql.NullString    `json:"description_en"`
	DescriptionFr     sql.NullString    `json:"description_fr"`
	SmsProcessType    string            `json:"sms_process_type"`
	EmailProcessType  string            `json:"email_process_type"`
	Hidden            bool              `json:"hidden"`
	SmsSendingVehicle SmsSendingVehicle `json:"sms_sending_vehicle"`
	UpdatedByID       uuid.NullUUID     `json:"updated_by_id"`
	ID                uuid.UUID         `json:"id"`
}

func (q *Queries) UpdateTemplateCategory(ctx context.Context, arg UpdateTemplateCategoryParams) (TemplateCategory, error) {
	row := q.db.QueryRowContext(ctx, updateTemplateCategory,
		arg.NameEn,
		arg.NameFr,
		arg.DescriptionEn,
		arg.DescriptionFr,
		arg.SmsProcessType,
		arg.EmailProcessType,
		arg.Hidden,
		arg.SmsSendingVehicle,
		arg.UpdatedByID,
		arg.ID,
	)
	var i TemplateCategory
	err := row.Scan(
		&i.ID,
		&i.NameEn,
		&i.NameFr,
		&i.DescriptionEn,
		&i.DescriptionFr,
		&i.SmsProcessType,
		&i.EmailProcessType,
		&i.Hidden,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SmsSendingVehicle,
		&i.CreatedByID,
		&i.UpdatedByID,
	)
	return i, err
}
