// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbound_sms.sql

package inbound

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addInboundNumber = `-- name: AddInboundNumber :one
UPDATE inbound_numbers
SET service_id = $1,
    active = true,
    updated_at = now()
WHERE id = $2
RETURNING id, number, provider, service_id, active, created_at, updated_at
`

type AddInboundNumberParams struct {
	ServiceID uuid.NullUUID `json:"service_id"`
	ID        uuid.UUID     `json:"id"`
}

func (q *Queries) AddInboundNumber(ctx context.Context, arg AddInboundNumberParams) (InboundNumber, error) {
	row := q.db.QueryRowContext(ctx, addInboundNumber, arg.ServiceID, arg.ID)
	var i InboundNumber
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Provider,
		&i.ServiceID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInboundSMS = `-- name: CreateInboundSMS :one
INSERT INTO inbound_sms (
        id,
        service_id,
        content,
        notify_number,
        user_number,
        created_at,
        provider_date,
        provider_reference,
        provider
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    )
RETURNING id, service_id, content, notify_number, user_number, created_at, provider_date, provider_reference, provider
`

type CreateInboundSMSParams struct {
	ID                uuid.UUID      `json:"id"`
	ServiceID         uuid.UUID      `json:"service_id"`
	Content           string         `json:"content"`
	NotifyNumber      string         `json:"notify_number"`
	UserNumber        string         `json:"user_number"`
	CreatedAt         time.Time      `json:"created_at"`
	ProviderDate      sql.NullTime   `json:"provider_date"`
	ProviderReference sql.NullString `json:"provider_reference"`
	Provider          string         `json:"provider"`
}

func (q *Queries) CreateInboundSMS(ctx context.Context, arg CreateInboundSMSParams) (InboundSm, error) {
	row := q.db.QueryRowContext(ctx, createInboundSMS,
		arg.ID,
		arg.ServiceID,
		arg.Content,
		arg.NotifyNumber,
		arg.UserNumber,
		arg.CreatedAt,
		arg.ProviderDate,
		arg.ProviderReference,
		arg.Provider,
	)
	var i InboundSm
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Content,
		&i.NotifyNumber,
		&i.UserNumber,
		&i.CreatedAt,
		&i.ProviderDate,
		&i.ProviderReference,
		&i.Provider,
	)
	return i, err
}

const deleteInboundSMSOlderThan = `-- name: DeleteInboundSMSOlderThan :execrows
DELETE FROM inbound_sms
WHERE created_at < $1
`

func (q *Queries) DeleteInboundSMSOlderThan(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInboundSMSOlderThan, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const disableInboundNumberForService = `-- name: DisableInboundNumberForService :one
UPDATE inbound_numbers
SET service_id = NULL,
    active = false,
    updated_at = now()
WHERE service_id = $1
    AND id = $2
RETURNING id, number, provider, service_id, active, created_at, updated_at
`

type DisableInboundNumberForServiceParams struct {
	ServiceID uuid.NullUUID `json:"service_id"`
	ID        uuid.UUID     `json:"id"`
}

func (q *Queries) DisableInboundNumberForService(ctx context.Context, arg DisableInboundNumberForServiceParams) (InboundNumber, error) {
	row := q.db.QueryRowContext(ctx, disableInboundNumberForService, arg.ServiceID, arg.ID)
	var i InboundNumber
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Provider,
		&i.ServiceID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvailableInboundNumbers = `-- name: GetAvailableInboundNumbers :many
SELECT id, number, provider, service_id, active, created_at, updated_at
FROM inbound_numbers
WHERE service_id IS NULL
    AND active = true
ORDER BY number ASC
`

func (q *Queries) GetAvailableInboundNumbers(ctx context.Context) ([]InboundNumber, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableInboundNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboundNumber
	for rows.Next() {
		var i InboundNumber
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Provider,
			&i.ServiceID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInboundNumberByServiceID = `-- name: GetInboundNumberByServiceID :one
SELECT id, number, provider, service_id, active, created_at, updated_at
FROM inbound_numbers
WHERE service_id = $1
    AND active = true
LIMIT 1
`

func (q *Queries) GetInboundNumberByServiceID(ctx context.Context, serviceID uuid.NullUUID) (InboundNumber, error) {
	row := q.db.QueryRowContext(ctx, getInboundNumberByServiceID, serviceID)
	var i InboundNumber
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Provider,
		&i.ServiceID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInboundNumbers = `-- name: GetInboundNumbers :many
SELECT id, number, provider, service_id, active, created_at, updated_at
FROM inbound_numbers
WHERE service_id = $1
ORDER BY number ASC
`

// inbound_sms.content is encrypted at rest and intentionally uses the physical column name `content`.
func (q *Queries) GetInboundNumbers(ctx context.Context, serviceID uuid.NullUUID) ([]InboundNumber, error) {
	rows, err := q.db.QueryContext(ctx, getInboundNumbers, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboundNumber
	for rows.Next() {
		var i InboundNumber
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Provider,
			&i.ServiceID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInboundSMSByID = `-- name: GetInboundSMSByID :one
SELECT id, service_id, content, notify_number, user_number, created_at, provider_date, provider_reference, provider
FROM inbound_sms
WHERE id = $1
`

func (q *Queries) GetInboundSMSByID(ctx context.Context, id uuid.UUID) (InboundSm, error) {
	row := q.db.QueryRowContext(ctx, getInboundSMSByID, id)
	var i InboundSm
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Content,
		&i.NotifyNumber,
		&i.UserNumber,
		&i.CreatedAt,
		&i.ProviderDate,
		&i.ProviderReference,
		&i.Provider,
	)
	return i, err
}

const getInboundSMSForService = `-- name: GetInboundSMSForService :many
SELECT id, service_id, content, notify_number, user_number, created_at, provider_date, provider_reference, provider
FROM inbound_sms
WHERE service_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetInboundSMSForServiceParams struct {
	ServiceID   uuid.UUID `json:"service_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

func (q *Queries) GetInboundSMSForService(ctx context.Context, arg GetInboundSMSForServiceParams) ([]InboundSm, error) {
	rows, err := q.db.QueryContext(ctx, getInboundSMSForService, arg.ServiceID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboundSm
	for rows.Next() {
		var i InboundSm
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Content,
			&i.NotifyNumber,
			&i.UserNumber,
			&i.CreatedAt,
			&i.ProviderDate,
			&i.ProviderReference,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInboundSMSSummary = `-- name: GetInboundSMSSummary :many
SELECT date_trunc('day', created_at)::date AS day,
    count(*) AS message_count
FROM inbound_sms
WHERE service_id = $1
GROUP BY 1
ORDER BY 1 DESC
`

type GetInboundSMSSummaryRow struct {
	Day          time.Time `json:"day"`
	MessageCount int64     `json:"message_count"`
}

func (q *Queries) GetInboundSMSSummary(ctx context.Context, serviceID uuid.UUID) ([]GetInboundSMSSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getInboundSMSSummary, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInboundSMSSummaryRow
	for rows.Next() {
		var i GetInboundSMSSummaryRow
		if err := rows.Scan(&i.Day, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostRecentInboundSMS = `-- name: GetMostRecentInboundSMS :one
SELECT id, service_id, content, notify_number, user_number, created_at, provider_date, provider_reference, provider
FROM inbound_sms
WHERE service_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetMostRecentInboundSMS(ctx context.Context, serviceID uuid.UUID) (InboundSm, error) {
	row := q.db.QueryRowContext(ctx, getMostRecentInboundSMS, serviceID)
	var i InboundSm
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Content,
		&i.NotifyNumber,
		&i.UserNumber,
		&i.CreatedAt,
		&i.ProviderDate,
		&i.ProviderReference,
		&i.Provider,
	)
	return i, err
}
