// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package notifications

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const bulkInsertNotifications = `-- name: BulkInsertNotifications :exec
WITH rows AS (
    SELECT x
    FROM jsonb_to_recordset($1::jsonb) AS x(
            id uuid,
            recipient text,
            job_id uuid,
            service_id uuid,
            template_id uuid,
            created_at timestamp,
            sent_at timestamp,
            sent_by text,
            updated_at timestamp,
            reference_value text,
            template_version integer,
            job_row_number integer,
            personalisation text,
            api_key_id uuid,
            key_type text,
            notification_type public.notification_type,
            billable_units integer,
            client_reference text,
            international boolean,
            phone_prefix text,
            rate_multiplier numeric,
            notification_status text,
            normalised_to text,
            created_by_id uuid,
            reply_to_text text,
            postage text,
            provider_response text,
            queue_name text,
            feedback_type public.notification_feedback_types,
            feedback_subtype public.notification_feedback_subtypes,
            ses_feedback_id text,
            ses_feedback_date timestamp,
            sms_total_message_price double precision,
            sms_total_carrier_fee double precision,
            sms_iso_country_code text,
            sms_carrier_name text,
            sms_message_encoding text,
            sms_origination_phone_number text,
            feedback_reason text
        )
)
INSERT INTO notifications (
        id,
        "to",
        job_id,
        service_id,
        template_id,
        created_at,
        sent_at,
        sent_by,
        updated_at,
        reference,
        template_version,
        job_row_number,
        _personalisation,
        api_key_id,
        key_type,
        notification_type,
        billable_units,
        client_reference,
        international,
        phone_prefix,
        rate_multiplier,
        notification_status,
        normalised_to,
        created_by_id,
        reply_to_text,
        postage,
        provider_response,
        queue_name,
        feedback_type,
        feedback_subtype,
        ses_feedback_id,
        ses_feedback_date,
        sms_total_message_price,
        sms_total_carrier_fee,
        sms_iso_country_code,
        sms_carrier_name,
        sms_message_encoding,
        sms_origination_phone_number,
        feedback_reason
    )
SELECT id,
    recipient,
    job_id,
    service_id,
    template_id,
    created_at,
    sent_at,
    sent_by,
    updated_at,
    reference_value,
    template_version,
    job_row_number,
    personalisation,
    api_key_id,
    key_type,
    notification_type,
    billable_units,
    client_reference,
    international,
    phone_prefix,
    rate_multiplier,
    notification_status,
    normalised_to,
    created_by_id,
    reply_to_text,
    postage,
    provider_response,
    queue_name,
    feedback_type,
    feedback_subtype,
    ses_feedback_id,
    ses_feedback_date,
    sms_total_message_price,
    sms_total_carrier_fee,
    sms_iso_country_code,
    sms_carrier_name,
    sms_message_encoding,
    sms_origination_phone_number,
    feedback_reason
FROM rows
`

func (q *Queries) BulkInsertNotifications(ctx context.Context, items json.RawMessage) error {
	_, err := q.db.ExecContext(ctx, bulkInsertNotifications, items)
	return err
}

const bulkUpdateNotificationStatuses = `-- name: BulkUpdateNotificationStatuses :execrows
WITH updates AS (
    SELECT u
    FROM jsonb_to_recordset($1::jsonb) AS u(
            id uuid,
            notification_status text,
            sent_by text,
            feedback_reason text
        )
)
UPDATE notifications AS n
SET notification_status = u.notification_status,
    sent_by = COALESCE(u.sent_by, n.sent_by),
    feedback_reason = COALESCE(u.feedback_reason, n.feedback_reason),
    updated_at = now()
FROM updates AS u
WHERE n.id = u.id
`

func (q *Queries) BulkUpdateNotificationStatuses(ctx context.Context, items json.RawMessage) (int64, error) {
	result, err := q.db.ExecContext(ctx, bulkUpdateNotificationStatuses, items)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
        id,
        "to",
        job_id,
        service_id,
        template_id,
        created_at,
        sent_at,
        sent_by,
        updated_at,
        reference,
        template_version,
        job_row_number,
        _personalisation,
        api_key_id,
        key_type,
        notification_type,
        billable_units,
        client_reference,
        international,
        phone_prefix,
        rate_multiplier,
        notification_status,
        normalised_to,
        created_by_id,
        reply_to_text,
        postage,
        provider_response,
        queue_name,
        feedback_type,
        feedback_subtype,
        ses_feedback_id,
        ses_feedback_date,
        sms_total_message_price,
        sms_total_carrier_fee,
        sms_iso_country_code,
        sms_carrier_name,
        sms_message_encoding,
        sms_origination_phone_number,
        feedback_reason
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32,
        $33,
        $34,
        $35,
        $36,
        $37,
        $38,
        $39
    )
RETURNING id, "to", job_id, service_id, template_id, created_at, sent_at, sent_by, updated_at, reference, template_version, job_row_number, _personalisation, api_key_id, key_type, notification_type, billable_units, client_reference, international, phone_prefix, rate_multiplier, notification_status, normalised_to, created_by_id, reply_to_text, postage, provider_response, queue_name, feedback_type, feedback_subtype, ses_feedback_id, ses_feedback_date, sms_total_message_price, sms_total_carrier_fee, sms_iso_country_code, sms_carrier_name, sms_message_encoding, sms_origination_phone_number, feedback_reason
`

type CreateNotificationParams struct {
	ID                        uuid.UUID                        `json:"id"`
	Recipient                 string                           `json:"recipient"`
	JobID                     uuid.NullUUID                    `json:"job_id"`
	ServiceID                 uuid.NullUUID                    `json:"service_id"`
	TemplateID                uuid.NullUUID                    `json:"template_id"`
	CreatedAt                 time.Time                        `json:"created_at"`
	SentAt                    sql.NullTime                     `json:"sent_at"`
	SentBy                    sql.NullString                   `json:"sent_by"`
	UpdatedAt                 sql.NullTime                     `json:"updated_at"`
	Reference                 sql.NullString                   `json:"reference"`
	TemplateVersion           int32                            `json:"template_version"`
	JobRowNumber              sql.NullInt32                    `json:"job_row_number"`
	Personalisation           sql.NullString                   `json:"personalisation"`
	ApiKeyID                  uuid.NullUUID                    `json:"api_key_id"`
	KeyType                   string                           `json:"key_type"`
	NotificationType          NotificationType                 `json:"notification_type"`
	BillableUnits             int32                            `json:"billable_units"`
	ClientReference           sql.NullString                   `json:"client_reference"`
	International             sql.NullBool                     `json:"international"`
	PhonePrefix               sql.NullString                   `json:"phone_prefix"`
	RateMultiplier            sql.NullString                   `json:"rate_multiplier"`
	NotificationStatus        sql.NullString                   `json:"notification_status"`
	NormalisedTo              sql.NullString                   `json:"normalised_to"`
	CreatedByID               uuid.NullUUID                    `json:"created_by_id"`
	ReplyToText               sql.NullString                   `json:"reply_to_text"`
	Postage                   sql.NullString                   `json:"postage"`
	ProviderResponse          sql.NullString                   `json:"provider_response"`
	QueueName                 sql.NullString                   `json:"queue_name"`
	FeedbackType              NullNotificationFeedbackTypes    `json:"feedback_type"`
	FeedbackSubtype           NullNotificationFeedbackSubtypes `json:"feedback_subtype"`
	SesFeedbackID             sql.NullString                   `json:"ses_feedback_id"`
	SesFeedbackDate           sql.NullTime                     `json:"ses_feedback_date"`
	SmsTotalMessagePrice      sql.NullFloat64                  `json:"sms_total_message_price"`
	SmsTotalCarrierFee        sql.NullFloat64                  `json:"sms_total_carrier_fee"`
	SmsIsoCountryCode         sql.NullString                   `json:"sms_iso_country_code"`
	SmsCarrierName            sql.NullString                   `json:"sms_carrier_name"`
	SmsMessageEncoding        sql.NullString                   `json:"sms_message_encoding"`
	SmsOriginationPhoneNumber sql.NullString                   `json:"sms_origination_phone_number"`
	FeedbackReason            sql.NullString                   `json:"feedback_reason"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.ID,
		arg.Recipient,
		arg.JobID,
		arg.ServiceID,
		arg.TemplateID,
		arg.CreatedAt,
		arg.SentAt,
		arg.SentBy,
		arg.UpdatedAt,
		arg.Reference,
		arg.TemplateVersion,
		arg.JobRowNumber,
		arg.Personalisation,
		arg.ApiKeyID,
		arg.KeyType,
		arg.NotificationType,
		arg.BillableUnits,
		arg.ClientReference,
		arg.International,
		arg.PhonePrefix,
		arg.RateMultiplier,
		arg.NotificationStatus,
		arg.NormalisedTo,
		arg.CreatedByID,
		arg.ReplyToText,
		arg.Postage,
		arg.ProviderResponse,
		arg.QueueName,
		arg.FeedbackType,
		arg.FeedbackSubtype,
		arg.SesFeedbackID,
		arg.SesFeedbackDate,
		arg.SmsTotalMessagePrice,
		arg.SmsTotalCarrierFee,
		arg.SmsIsoCountryCode,
		arg.SmsCarrierName,
		arg.SmsMessageEncoding,
		arg.SmsOriginationPhoneNumber,
		arg.FeedbackReason,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.To,
		&i.JobID,
		&i.ServiceID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.SentAt,
		&i.SentBy,
		&i.UpdatedAt,
		&i.Reference,
		&i.TemplateVersion,
		&i.JobRowNumber,
		&i.Personalisation,
		&i.ApiKeyID,
		&i.KeyType,
		&i.NotificationType,
		&i.BillableUnits,
		&i.ClientReference,
		&i.International,
		&i.PhonePrefix,
		&i.RateMultiplier,
		&i.NotificationStatus,
		&i.NormalisedTo,
		&i.CreatedByID,
		&i.ReplyToText,
		&i.Postage,
		&i.ProviderResponse,
		&i.QueueName,
		&i.FeedbackType,
		&i.FeedbackSubtype,
		&i.SesFeedbackID,
		&i.SesFeedbackDate,
		&i.SmsTotalMessagePrice,
		&i.SmsTotalCarrierFee,
		&i.SmsIsoCountryCode,
		&i.SmsCarrierName,
		&i.SmsMessageEncoding,
		&i.SmsOriginationPhoneNumber,
		&i.FeedbackReason,
	)
	return i, err
}

const deleteNotificationsOlderThanRetention = `-- name: DeleteNotificationsOlderThanRetention :execrows
DELETE FROM notifications
WHERE notification_type = $1
    AND created_at < $2
`

type DeleteNotificationsOlderThanRetentionParams struct {
	NotificationType NotificationType `json:"notification_type"`
	Cutoff           time.Time        `json:"cutoff"`
}

func (q *Queries) DeleteNotificationsOlderThanRetention(ctx context.Context, arg DeleteNotificationsOlderThanRetentionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNotificationsOlderThanRetention, arg.NotificationType, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBounceRateTimeSeries = `-- name: GetBounceRateTimeSeries :many
SELECT date_trunc('day', created_at)::date AS day,
    count(*) FILTER (
        WHERE feedback_type = 'hard-bounce'
    ) AS hard_bounces,
    count(*) FILTER (
        WHERE feedback_type = 'soft-bounce'
    ) AS soft_bounces,
    count(*) AS total_notifications
FROM notifications
WHERE service_id = $1
    AND created_at >= $2
GROUP BY 1
ORDER BY 1
`

type GetBounceRateTimeSeriesParams struct {
	ServiceID uuid.NullUUID `json:"service_id"`
	Since     time.Time     `json:"since"`
}

type GetBounceRateTimeSeriesRow struct {
	Day                time.Time `json:"day"`
	HardBounces        int64     `json:"hard_bounces"`
	SoftBounces        int64     `json:"soft_bounces"`
	TotalNotifications int64     `json:"total_notifications"`
}

func (q *Queries) GetBounceRateTimeSeries(ctx context.Context, arg GetBounceRateTimeSeriesParams) ([]GetBounceRateTimeSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getBounceRateTimeSeries, arg.ServiceID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBounceRateTimeSeriesRow
	for rows.Next() {
		var i GetBounceRateTimeSeriesRow
		if err := rows.Scan(
			&i.Day,
			&i.HardBounces,
			&i.SoftBounces,
			&i.TotalNotifications,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHardBouncesForService = `-- name: GetHardBouncesForService :many
SELECT id, "to", job_id, service_id, template_id, created_at, sent_at, sent_by, updated_at, reference, template_version, job_row_number, _personalisation, api_key_id, key_type, notification_type, billable_units, client_reference, international, phone_prefix, rate_multiplier, notification_status, normalised_to, created_by_id, reply_to_text, postage, provider_response, queue_name, feedback_type, feedback_subtype, ses_feedback_id, ses_feedback_date, sms_total_message_price, sms_total_carrier_fee, sms_iso_country_code, sms_carrier_name, sms_message_encoding, sms_origination_phone_number, feedback_reason
FROM notifications
WHERE service_id = $1
    AND feedback_type = 'hard-bounce'
    AND created_at >= $2
ORDER BY created_at DESC
`

type GetHardBouncesForServiceParams struct {
	ServiceID uuid.NullUUID `json:"service_id"`
	Since     time.Time     `json:"since"`
}

func (q *Queries) GetHardBouncesForService(ctx context.Context, arg GetHardBouncesForServiceParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getHardBouncesForService, arg.ServiceID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.To,
			&i.JobID,
			&i.ServiceID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.SentAt,
			&i.SentBy,
			&i.UpdatedAt,
			&i.Reference,
			&i.TemplateVersion,
			&i.JobRowNumber,
			&i.Personalisation,
			&i.ApiKeyID,
			&i.KeyType,
			&i.NotificationType,
			&i.BillableUnits,
			&i.ClientReference,
			&i.International,
			&i.PhonePrefix,
			&i.RateMultiplier,
			&i.NotificationStatus,
			&i.NormalisedTo,
			&i.CreatedByID,
			&i.ReplyToText,
			&i.Postage,
			&i.ProviderResponse,
			&i.QueueName,
			&i.FeedbackType,
			&i.FeedbackSubtype,
			&i.SesFeedbackID,
			&i.SesFeedbackDate,
			&i.SmsTotalMessagePrice,
			&i.SmsTotalCarrierFee,
			&i.SmsIsoCountryCode,
			&i.SmsCarrierName,
			&i.SmsMessageEncoding,
			&i.SmsOriginationPhoneNumber,
			&i.FeedbackReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastNotificationAddedForJobID = `-- name: GetLastNotificationAddedForJobID :one
SELECT id, "to", job_id, service_id, template_id, created_at, sent_at, sent_by, updated_at, reference, template_version, job_row_number, _personalisation, api_key_id, key_type, notification_type, billable_units, client_reference, international, phone_prefix, rate_multiplier, notification_status, normalised_to, created_by_id, reply_to_text, postage, provider_response, queue_name, feedback_type, feedback_subtype, ses_feedback_id, ses_feedback_date, sms_total_message_price, sms_total_carrier_fee, sms_iso_country_code, sms_carrier_name, sms_message_encoding, sms_origination_phone_number, feedback_reason
FROM notifications
WHERE job_id = $1
ORDER BY created_at DESC,
    id DESC
LIMIT 1
`

func (q *Queries) GetLastNotificationAddedForJobID(ctx context.Context, jobID uuid.NullUUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getLastNotificationAddedForJobID, jobID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.To,
		&i.JobID,
		&i.ServiceID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.SentAt,
		&i.SentBy,
		&i.UpdatedAt,
		&i.Reference,
		&i.TemplateVersion,
		&i.JobRowNumber,
		&i.Personalisation,
		&i.ApiKeyID,
		&i.KeyType,
		&i.NotificationType,
		&i.BillableUnits,
		&i.ClientReference,
		&i.International,
		&i.PhonePrefix,
		&i.RateMultiplier,
		&i.NotificationStatus,
		&i.NormalisedTo,
		&i.CreatedByID,
		&i.ReplyToText,
		&i.Postage,
		&i.ProviderResponse,
		&i.QueueName,
		&i.FeedbackType,
		&i.FeedbackSubtype,
		&i.SesFeedbackID,
		&i.SesFeedbackDate,
		&i.SmsTotalMessagePrice,
		&i.SmsTotalCarrierFee,
		&i.SmsIsoCountryCode,
		&i.SmsCarrierName,
		&i.SmsMessageEncoding,
		&i.SmsOriginationPhoneNumber,
		&i.FeedbackReason,
	)
	return i, err
}

const getLastTemplateUsage = `-- name: GetLastTemplateUsage :one
SELECT id, "to", job_id, service_id, template_id, created_at, sent_at, sent_by, updated_at, reference, template_version, job_row_number, _personalisation, api_key_id, key_type, notification_type, billable_units, client_reference, international, phone_prefix, rate_multiplier, notification_status, normalised_to, created_by_id, reply_to_text, postage, provider_response, queue_name, feedback_type, feedback_subtype, ses_feedback_id, ses_feedback_date, sms_total_message_price, sms_total_carrier_fee, sms_iso_country_code, sms_carrier_name, sms_message_encoding, sms_origination_phone_number, feedback_reason
FROM notifications
WHERE template_id = $1
    AND service_id = $2
    AND notification_type = $3
ORDER BY created_at DESC
LIMIT 1
`

type GetLastTemplateUsageParams struct {
	TemplateID       uuid.NullUUID    `json:"template_id"`
	ServiceID        uuid.NullUUID    `json:"service_id"`
	NotificationType NotificationType `json:"notification_type"`
}

func (q *Queries) GetLastTemplateUsage(ctx context.Context, arg GetLastTemplateUsageParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getLastTemplateUsage, arg.TemplateID, arg.ServiceID, arg.NotificationType)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.To,
		&i.JobID,
		&i.ServiceID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.SentAt,
		&i.SentBy,
		&i.UpdatedAt,
		&i.Reference,
		&i.TemplateVersion,
		&i.JobRowNumber,
		&i.Personalisation,
		&i.ApiKeyID,
		&i.KeyType,
		&i.NotificationType,
		&i.BillableUnits,
		&i.ClientReference,
		&i.International,
		&i.PhonePrefix,
		&i.RateMultiplier,
		&i.NotificationStatus,
		&i.NormalisedTo,
		&i.CreatedByID,
		&i.ReplyToText,
		&i.Postage,
		&i.ProviderResponse,
		&i.QueueName,
		&i.FeedbackType,
		&i.FeedbackSubtype,
		&i.SesFeedbackID,
		&i.SesFeedbackDate,
		&i.SmsTotalMessagePrice,
		&i.SmsTotalCarrierFee,
		&i.SmsIsoCountryCode,
		&i.SmsCarrierName,
		&i.SmsMessageEncoding,
		&i.SmsOriginationPhoneNumber,
		&i.FeedbackReason,
	)
	return i, err
}

const getMonthlyNotificationStats = `-- name: GetMonthlyNotificationStats :many
SELECT date_trunc('month', created_at)::date AS month,
    notification_type,
    notification_status,
    count(*) AS notification_count,
    coalesce(sum(billable_units), 0)::bigint AS billable_units
FROM notifications
WHERE service_id = $1
    AND extract(
        year
        FROM created_at
    ) = $2
GROUP BY 1,
    2,
    3
ORDER BY 1,
    2,
    3
`

type GetMonthlyNotificationStatsParams struct {
	ServiceID uuid.NullUUID `json:"service_id"`
	Year      time.Time     `json:"year"`
}

type GetMonthlyNotificationStatsRow struct {
	Month              time.Time        `json:"month"`
	NotificationType   NotificationType `json:"notification_type"`
	NotificationStatus sql.NullString   `json:"notification_status"`
	NotificationCount  int64            `json:"notification_count"`
	BillableUnits      int64            `json:"billable_units"`
}

func (q *Queries) GetMonthlyNotificationStats(ctx context.Context, arg GetMonthlyNotificationStatsParams) ([]GetMonthlyNotificationStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyNotificationStats, arg.ServiceID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyNotificationStatsRow
	for rows.Next() {
		var i GetMonthlyNotificationStatsRow
		if err := rows.Scan(
			&i.Month,
			&i.NotificationType,
			&i.NotificationStatus,
			&i.NotificationCount,
			&i.BillableUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, "to", job_id, service_id, template_id, created_at, sent_at, sent_by, updated_at, reference, template_version, job_row_number, _personalisation, api_key_id, key_type, notification_type, billable_units, client_reference, international, phone_prefix, rate_multiplier, notification_status, normalised_to, created_by_id, reply_to_text, postage, provider_response, queue_name, feedback_type, feedback_subtype, ses_feedback_id, ses_feedback_date, sms_total_message_price, sms_total_carrier_fee, sms_iso_country_code, sms_carrier_name, sms_message_encoding, sms_origination_phone_number, feedback_reason
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.To,
		&i.JobID,
		&i.ServiceID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.SentAt,
		&i.SentBy,
		&i.UpdatedAt,
		&i.Reference,
		&i.TemplateVersion,
		&i.JobRowNumber,
		&i.Personalisation,
		&i.ApiKeyID,
		&i.KeyType,
		&i.NotificationType,
		&i.BillableUnits,
		&i.ClientReference,
		&i.International,
		&i.PhonePrefix,
		&i.RateMultiplier,
		&i.NotificationStatus,
		&i.NormalisedTo,
		&i.CreatedByID,
		&i.ReplyToText,
		&i.Postage,
		&i.ProviderResponse,
		&i.QueueName,
		&i.FeedbackType,
		&i.FeedbackSubtype,
		&i.SesFeedbackID,
		&i.SesFeedbackDate,
		&i.SmsTotalMessagePrice,
		&i.SmsTotalCarrierFee,
		&i.SmsIsoCountryCode,
		&i.SmsCarrierName,
		&i.SmsMessageEncoding,
		&i.SmsOriginationPhoneNumber,
		&i.FeedbackReason,
	)
	return i, err
}

const getNotificationFromHistory = `-- name: GetNotificationFromHistory :one
SELECT id, job_id, job_row_number, service_id, template_id, template_version, api_key_id, key_type, notification_type, created_at, sent_at, sent_by, updated_at, reference, billable_units, client_reference, international, phone_prefix, rate_multiplier, notification_status, created_by_id, postage, queue_name, feedback_type, feedback_subtype, ses_feedback_id, ses_feedback_date, sms_total_message_price, sms_total_carrier_fee, sms_iso_country_code, sms_carrier_name, sms_message_encoding, sms_origination_phone_number, feedback_reason
FROM notification_history
WHERE id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetNotificationFromHistory(ctx context.Context, id uuid.UUID) (NotificationHistory, error) {
	row := q.db.QueryRowContext(ctx, getNotificationFromHistory, id)
	var i NotificationHistory
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.JobRowNumber,
		&i.ServiceID,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.ApiKeyID,
		&i.KeyType,
		&i.NotificationType,
		&i.CreatedAt,
		&i.SentAt,
		&i.SentBy,
		&i.UpdatedAt,
		&i.Reference,
		&i.BillableUnits,
		&i.ClientReference,
		&i.International,
		&i.PhonePrefix,
		&i.RateMultiplier,
		&i.NotificationStatus,
		&i.CreatedByID,
		&i.Postage,
		&i.QueueName,
		&i.FeedbackType,
		&i.FeedbackSubtype,
		&i.SesFeedbackID,
		&i.SesFeedbackDate,
		&i.SmsTotalMessagePrice,
		&i.SmsTotalCarrierFee,
		&i.SmsIsoCountryCode,
		&i.SmsCarrierName,
		&i.SmsMessageEncoding,
		&i.SmsOriginationPhoneNumber,
		&i.FeedbackReason,
	)
	return i, err
}

const getNotificationsByReference = `-- name: GetNotificationsByReference :many
SELECT id, "to", job_id, service_id, template_id, created_at, sent_at, sent_by, updated_at, reference, template_version, job_row_number, _personalisation, api_key_id, key_type, notification_type, billable_units, client_reference, international, phone_prefix, rate_multiplier, notification_status, normalised_to, created_by_id, reply_to_text, postage, provider_response, queue_name, feedback_type, feedback_subtype, ses_feedback_id, ses_feedback_date, sms_total_message_price, sms_total_carrier_fee, sms_iso_country_code, sms_carrier_name, sms_message_encoding, sms_origination_phone_number, feedback_reason
FROM notifications
WHERE reference = $1
ORDER BY created_at DESC
`

func (q *Queries) GetNotificationsByReference(ctx context.Context, reference sql.NullString) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByReference, reference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.To,
			&i.JobID,
			&i.ServiceID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.SentAt,
			&i.SentBy,
			&i.UpdatedAt,
			&i.Reference,
			&i.TemplateVersion,
			&i.JobRowNumber,
			&i.Personalisation,
			&i.ApiKeyID,
			&i.KeyType,
			&i.NotificationType,
			&i.BillableUnits,
			&i.ClientReference,
			&i.International,
			&i.PhonePrefix,
			&i.RateMultiplier,
			&i.NotificationStatus,
			&i.NormalisedTo,
			&i.CreatedByID,
			&i.ReplyToText,
			&i.Postage,
			&i.ProviderResponse,
			&i.QueueName,
			&i.FeedbackType,
			&i.FeedbackSubtype,
			&i.SesFeedbackID,
			&i.SesFeedbackDate,
			&i.SmsTotalMessagePrice,
			&i.SmsTotalCarrierFee,
			&i.SmsIsoCountryCode,
			&i.SmsCarrierName,
			&i.SmsMessageEncoding,
			&i.SmsOriginationPhoneNumber,
			&i.FeedbackReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsByServiceID = `-- name: GetNotificationsByServiceID :many
SELECT id, "to", job_id, service_id, template_id, created_at, sent_at, sent_by, updated_at, reference, template_version, job_row_number, _personalisation, api_key_id, key_type, notification_type, billable_units, client_reference, international, phone_prefix, rate_multiplier, notification_status, normalised_to, created_by_id, reply_to_text, postage, provider_response, queue_name, feedback_type, feedback_subtype, ses_feedback_id, ses_feedback_date, sms_total_message_price, sms_total_carrier_fee, sms_iso_country_code, sms_carrier_name, sms_message_encoding, sms_origination_phone_number, feedback_reason
FROM notifications
WHERE service_id = $1
    AND (
        $2::public.notification_type IS NULL
        OR notification_type = $2::public.notification_type
    )
    AND (
        $3::text IS NULL
        OR notification_status = $3::text
    )
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type GetNotificationsByServiceIDParams struct {
	ServiceID          uuid.NullUUID        `json:"service_id"`
	NotificationType   NullNotificationType `json:"notification_type"`
	NotificationStatus sql.NullString       `json:"notification_status"`
	OffsetCount        int32                `json:"offset_count"`
	LimitCount         int32                `json:"limit_count"`
}

func (q *Queries) GetNotificationsByServiceID(ctx context.Context, arg GetNotificationsByServiceIDParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByServiceID,
		arg.ServiceID,
		arg.NotificationType,
		arg.NotificationStatus,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.To,
			&i.JobID,
			&i.ServiceID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.SentAt,
			&i.SentBy,
			&i.UpdatedAt,
			&i.Reference,
			&i.TemplateVersion,
			&i.JobRowNumber,
			&i.Personalisation,
			&i.ApiKeyID,
			&i.KeyType,
			&i.NotificationType,
			&i.BillableUnits,
			&i.ClientReference,
			&i.International,
			&i.PhonePrefix,
			&i.RateMultiplier,
			&i.NotificationStatus,
			&i.NormalisedTo,
			&i.CreatedByID,
			&i.ReplyToText,
			&i.Postage,
			&i.ProviderResponse,
			&i.QueueName,
			&i.FeedbackType,
			&i.FeedbackSubtype,
			&i.SesFeedbackID,
			&i.SesFeedbackDate,
			&i.SmsTotalMessagePrice,
			&i.SmsTotalCarrierFee,
			&i.SmsIsoCountryCode,
			&i.SmsCarrierName,
			&i.SmsMessageEncoding,
			&i.SmsOriginationPhoneNumber,
			&i.FeedbackReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsCreatedSince = `-- name: GetNotificationsCreatedSince :many
SELECT id, "to", job_id, service_id, template_id, created_at, sent_at, sent_by, updated_at, reference, template_version, job_row_number, _personalisation, api_key_id, key_type, notification_type, billable_units, client_reference, international, phone_prefix, rate_multiplier, notification_status, normalised_to, created_by_id, reply_to_text, postage, provider_response, queue_name, feedback_type, feedback_subtype, ses_feedback_id, ses_feedback_date, sms_total_message_price, sms_total_carrier_fee, sms_iso_country_code, sms_carrier_name, sms_message_encoding, sms_origination_phone_number, feedback_reason
FROM notifications
WHERE created_at >= $1
    AND (
        $2::text IS NULL
        OR notification_status = $2::text
    )
ORDER BY created_at ASC
`

type GetNotificationsCreatedSinceParams struct {
	Since              time.Time      `json:"since"`
	NotificationStatus sql.NullString `json:"notification_status"`
}

func (q *Queries) GetNotificationsCreatedSince(ctx context.Context, arg GetNotificationsCreatedSinceParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsCreatedSince, arg.Since, arg.NotificationStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.To,
			&i.JobID,
			&i.ServiceID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.SentAt,
			&i.SentBy,
			&i.UpdatedAt,
			&i.Reference,
			&i.TemplateVersion,
			&i.JobRowNumber,
			&i.Personalisation,
			&i.ApiKeyID,
			&i.KeyType,
			&i.NotificationType,
			&i.BillableUnits,
			&i.ClientReference,
			&i.International,
			&i.PhonePrefix,
			&i.RateMultiplier,
			&i.NotificationStatus,
			&i.NormalisedTo,
			&i.CreatedByID,
			&i.ReplyToText,
			&i.Postage,
			&i.ProviderResponse,
			&i.QueueName,
			&i.FeedbackType,
			&i.FeedbackSubtype,
			&i.SesFeedbackID,
			&i.SesFeedbackDate,
			&i.SmsTotalMessagePrice,
			&i.SmsTotalCarrierFee,
			&i.SmsIsoCountryCode,
			&i.SmsCarrierName,
			&i.SmsMessageEncoding,
			&i.SmsOriginationPhoneNumber,
			&i.FeedbackReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsForJob = `-- name: GetNotificationsForJob :many
SELECT id, "to", job_id, service_id, template_id, created_at, sent_at, sent_by, updated_at, reference, template_version, job_row_number, _personalisation, api_key_id, key_type, notification_type, billable_units, client_reference, international, phone_prefix, rate_multiplier, notification_status, normalised_to, created_by_id, reply_to_text, postage, provider_response, queue_name, feedback_type, feedback_subtype, ses_feedback_id, ses_feedback_date, sms_total_message_price, sms_total_carrier_fee, sms_iso_country_code, sms_carrier_name, sms_message_encoding, sms_origination_phone_number, feedback_reason
FROM notifications
WHERE job_id = $1
    AND (
        $2::text IS NULL
        OR notification_status = $2::text
    )
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type GetNotificationsForJobParams struct {
	JobID              uuid.NullUUID  `json:"job_id"`
	NotificationStatus sql.NullString `json:"notification_status"`
	OffsetCount        int32          `json:"offset_count"`
	LimitCount         int32          `json:"limit_count"`
}

func (q *Queries) GetNotificationsForJob(ctx context.Context, arg GetNotificationsForJobParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsForJob,
		arg.JobID,
		arg.NotificationStatus,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.To,
			&i.JobID,
			&i.ServiceID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.SentAt,
			&i.SentBy,
			&i.UpdatedAt,
			&i.Reference,
			&i.TemplateVersion,
			&i.JobRowNumber,
			&i.Personalisation,
			&i.ApiKeyID,
			&i.KeyType,
			&i.NotificationType,
			&i.BillableUnits,
			&i.ClientReference,
			&i.International,
			&i.PhonePrefix,
			&i.RateMultiplier,
			&i.NotificationStatus,
			&i.NormalisedTo,
			&i.CreatedByID,
			&i.ReplyToText,
			&i.Postage,
			&i.ProviderResponse,
			&i.QueueName,
			&i.FeedbackType,
			&i.FeedbackSubtype,
			&i.SesFeedbackID,
			&i.SesFeedbackDate,
			&i.SmsTotalMessagePrice,
			&i.SmsTotalCarrierFee,
			&i.SmsIsoCountryCode,
			&i.SmsCarrierName,
			&i.SmsMessageEncoding,
			&i.SmsOriginationPhoneNumber,
			&i.FeedbackReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateUsageMonthly = `-- name: GetTemplateUsageMonthly :many
SELECT date_trunc('month', created_at)::date AS month,
    template_id,
    template_version,
    count(*) AS notification_count
FROM notifications
WHERE service_id = $1
    AND extract(
        year
        FROM created_at
    ) = $2
GROUP BY 1,
    2,
    3
ORDER BY 1,
    2,
    3
`

type GetTemplateUsageMonthlyParams struct {
	ServiceID uuid.NullUUID `json:"service_id"`
	Year      time.Time     `json:"year"`
}

type GetTemplateUsageMonthlyRow struct {
	Month             time.Time     `json:"month"`
	TemplateID        uuid.NullUUID `json:"template_id"`
	TemplateVersion   int32         `json:"template_version"`
	NotificationCount int64         `json:"notification_count"`
}

func (q *Queries) GetTemplateUsageMonthly(ctx context.Context, arg GetTemplateUsageMonthlyParams) ([]GetTemplateUsageMonthlyRow, error) {
	rows, err := q.db.QueryContext(ctx, getTemplateUsageMonthly, arg.ServiceID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTemplateUsageMonthlyRow
	for rows.Next() {
		var i GetTemplateUsageMonthlyRow
		if err := rows.Scan(
			&i.Month,
			&i.TemplateID,
			&i.TemplateVersion,
			&i.NotificationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNotificationHistory = `-- name: InsertNotificationHistory :exec
INSERT INTO notification_history (
        id,
        job_id,
        job_row_number,
        service_id,
        template_id,
        template_version,
        api_key_id,
        key_type,
        notification_type,
        created_at,
        sent_at,
        sent_by,
        updated_at,
        reference,
        billable_units,
        client_reference,
        international,
        phone_prefix,
        rate_multiplier,
        notification_status,
        created_by_id,
        postage,
        queue_name,
        feedback_type,
        feedback_subtype,
        ses_feedback_id,
        ses_feedback_date,
        sms_total_message_price,
        sms_total_carrier_fee,
        sms_iso_country_code,
        sms_carrier_name,
        sms_message_encoding,
        sms_origination_phone_number,
        feedback_reason
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32,
        $33,
        $34
    )
`

type InsertNotificationHistoryParams struct {
	ID                        uuid.UUID                        `json:"id"`
	JobID                     uuid.NullUUID                    `json:"job_id"`
	JobRowNumber              sql.NullInt32                    `json:"job_row_number"`
	ServiceID                 uuid.NullUUID                    `json:"service_id"`
	TemplateID                uuid.NullUUID                    `json:"template_id"`
	TemplateVersion           int32                            `json:"template_version"`
	ApiKeyID                  uuid.NullUUID                    `json:"api_key_id"`
	KeyType                   string                           `json:"key_type"`
	NotificationType          NotificationType                 `json:"notification_type"`
	CreatedAt                 time.Time                        `json:"created_at"`
	SentAt                    sql.NullTime                     `json:"sent_at"`
	SentBy                    sql.NullString                   `json:"sent_by"`
	UpdatedAt                 sql.NullTime                     `json:"updated_at"`
	Reference                 sql.NullString                   `json:"reference"`
	BillableUnits             int32                            `json:"billable_units"`
	ClientReference           sql.NullString                   `json:"client_reference"`
	International             sql.NullBool                     `json:"international"`
	PhonePrefix               sql.NullString                   `json:"phone_prefix"`
	RateMultiplier            sql.NullString                   `json:"rate_multiplier"`
	NotificationStatus        sql.NullString                   `json:"notification_status"`
	CreatedByID               uuid.NullUUID                    `json:"created_by_id"`
	Postage                   sql.NullString                   `json:"postage"`
	QueueName                 sql.NullString                   `json:"queue_name"`
	FeedbackType              NullNotificationFeedbackTypes    `json:"feedback_type"`
	FeedbackSubtype           NullNotificationFeedbackSubtypes `json:"feedback_subtype"`
	SesFeedbackID             sql.NullString                   `json:"ses_feedback_id"`
	SesFeedbackDate           sql.NullTime                     `json:"ses_feedback_date"`
	SmsTotalMessagePrice      sql.NullFloat64                  `json:"sms_total_message_price"`
	SmsTotalCarrierFee        sql.NullFloat64                  `json:"sms_total_carrier_fee"`
	SmsIsoCountryCode         sql.NullString                   `json:"sms_iso_country_code"`
	SmsCarrierName            sql.NullString                   `json:"sms_carrier_name"`
	SmsMessageEncoding        sql.NullString                   `json:"sms_message_encoding"`
	SmsOriginationPhoneNumber sql.NullString                   `json:"sms_origination_phone_number"`
	FeedbackReason            sql.NullString                   `json:"feedback_reason"`
}

func (q *Queries) InsertNotificationHistory(ctx context.Context, arg InsertNotificationHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertNotificationHistory,
		arg.ID,
		arg.JobID,
		arg.JobRowNumber,
		arg.ServiceID,
		arg.TemplateID,
		arg.TemplateVersion,
		arg.ApiKeyID,
		arg.KeyType,
		arg.NotificationType,
		arg.CreatedAt,
		arg.SentAt,
		arg.SentBy,
		arg.UpdatedAt,
		arg.Reference,
		arg.BillableUnits,
		arg.ClientReference,
		arg.International,
		arg.PhonePrefix,
		arg.RateMultiplier,
		arg.NotificationStatus,
		arg.CreatedByID,
		arg.Postage,
		arg.QueueName,
		arg.FeedbackType,
		arg.FeedbackSubtype,
		arg.SesFeedbackID,
		arg.SesFeedbackDate,
		arg.SmsTotalMessagePrice,
		arg.SmsTotalCarrierFee,
		arg.SmsIsoCountryCode,
		arg.SmsCarrierName,
		arg.SmsMessageEncoding,
		arg.SmsOriginationPhoneNumber,
		arg.FeedbackReason,
	)
	return err
}

const timeoutSendingNotifications = `-- name: TimeoutSendingNotifications :many
UPDATE notifications
SET notification_status = 'temporary-failure',
    updated_at = now()
WHERE notification_status = 'sending'
    AND COALESCE(updated_at, created_at) < $1
RETURNING id
`

func (q *Queries) TimeoutSendingNotifications(ctx context.Context, cutoff sql.NullTime) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, timeoutSendingNotifications, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationStatusByID = `-- name: UpdateNotificationStatusByID :one
UPDATE notifications
SET notification_status = $1,
    sent_by = COALESCE($2, sent_by),
    feedback_reason = COALESCE($3, feedback_reason),
    updated_at = now()
WHERE id = $4
RETURNING id, "to", job_id, service_id, template_id, created_at, sent_at, sent_by, updated_at, reference, template_version, job_row_number, _personalisation, api_key_id, key_type, notification_type, billable_units, client_reference, international, phone_prefix, rate_multiplier, notification_status, normalised_to, created_by_id, reply_to_text, postage, provider_response, queue_name, feedback_type, feedback_subtype, ses_feedback_id, ses_feedback_date, sms_total_message_price, sms_total_carrier_fee, sms_iso_country_code, sms_carrier_name, sms_message_encoding, sms_origination_phone_number, feedback_reason
`

type UpdateNotificationStatusByIDParams struct {
	NotificationStatus sql.NullString `json:"notification_status"`
	SentBy             sql.NullString `json:"sent_by"`
	FeedbackReason     sql.NullString `json:"feedback_reason"`
	ID                 uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateNotificationStatusByID(ctx context.Context, arg UpdateNotificationStatusByIDParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, updateNotificationStatusByID,
		arg.NotificationStatus,
		arg.SentBy,
		arg.FeedbackReason,
		arg.ID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.To,
		&i.JobID,
		&i.ServiceID,
		&i.TemplateID,
		&i.CreatedAt,
		&i.SentAt,
		&i.SentBy,
		&i.UpdatedAt,
		&i.Reference,
		&i.TemplateVersion,
		&i.JobRowNumber,
		&i.Personalisation,
		&i.ApiKeyID,
		&i.KeyType,
		&i.NotificationType,
		&i.BillableUnits,
		&i.ClientReference,
		&i.International,
		&i.PhonePrefix,
		&i.RateMultiplier,
		&i.NotificationStatus,
		&i.NormalisedTo,
		&i.CreatedByID,
		&i.ReplyToText,
		&i.Postage,
		&i.ProviderResponse,
		&i.QueueName,
		&i.FeedbackType,
		&i.FeedbackSubtype,
		&i.SesFeedbackID,
		&i.SesFeedbackDate,
		&i.SmsTotalMessagePrice,
		&i.SmsTotalCarrierFee,
		&i.SmsIsoCountryCode,
		&i.SmsCarrierName,
		&i.SmsMessageEncoding,
		&i.SmsOriginationPhoneNumber,
		&i.FeedbackReason,
	)
	return i, err
}

const updateNotificationStatusByReference = `-- name: UpdateNotificationStatusByReference :many
UPDATE notifications
SET notification_status = $1,
    updated_at = now()
WHERE reference = $2
RETURNING id, "to", job_id, service_id, template_id, created_at, sent_at, sent_by, updated_at, reference, template_version, job_row_number, _personalisation, api_key_id, key_type, notification_type, billable_units, client_reference, international, phone_prefix, rate_multiplier, notification_status, normalised_to, created_by_id, reply_to_text, postage, provider_response, queue_name, feedback_type, feedback_subtype, ses_feedback_id, ses_feedback_date, sms_total_message_price, sms_total_carrier_fee, sms_iso_country_code, sms_carrier_name, sms_message_encoding, sms_origination_phone_number, feedback_reason
`

type UpdateNotificationStatusByReferenceParams struct {
	NotificationStatus sql.NullString `json:"notification_status"`
	Reference          sql.NullString `json:"reference"`
}

func (q *Queries) UpdateNotificationStatusByReference(ctx context.Context, arg UpdateNotificationStatusByReferenceParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, updateNotificationStatusByReference, arg.NotificationStatus, arg.Reference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.To,
			&i.JobID,
			&i.ServiceID,
			&i.TemplateID,
			&i.CreatedAt,
			&i.SentAt,
			&i.SentBy,
			&i.UpdatedAt,
			&i.Reference,
			&i.TemplateVersion,
			&i.JobRowNumber,
			&i.Personalisation,
			&i.ApiKeyID,
			&i.KeyType,
			&i.NotificationType,
			&i.BillableUnits,
			&i.ClientReference,
			&i.International,
			&i.PhonePrefix,
			&i.RateMultiplier,
			&i.NotificationStatus,
			&i.NormalisedTo,
			&i.CreatedByID,
			&i.ReplyToText,
			&i.Postage,
			&i.ProviderResponse,
			&i.QueueName,
			&i.FeedbackType,
			&i.FeedbackSubtype,
			&i.SesFeedbackID,
			&i.SesFeedbackDate,
			&i.SmsTotalMessagePrice,
			&i.SmsTotalCarrierFee,
			&i.SmsIsoCountryCode,
			&i.SmsCarrierName,
			&i.SmsMessageEncoding,
			&i.SmsOriginationPhoneNumber,
			&i.FeedbackReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
